### ISSUE TITLE
Possibility to list only reports w/ changes

### ISSUE THREAD

**Issue by spanneberg** [voxpupuli/puppetboard#127]
It would be nice to only see the n latest reports that contain changes, instead of the latest n reports only. In a masterless and cron-driven setup, you see a lot of empty reports, and the ones containing the changes dissappear quite quickly from the list.

**Comment by dklueh** [comment]
That would be great!

**Comment by rafaelhenrique** [comment]
spanneberg how i can reply this scenario on puppet?? I have any empty reports too, but i dont know why this occur... you can explain to me? I can try solve that

**Comment by rtib** [comment]
The agent reports every single run. In the case that there was no change and no failure, the report doesn't contain any events. The App will always show the latest 10 reports, however, in normal operation they should not contain any events. It would be useful to list not just the latest 10 reports, but the latest 10 reports containing events.

**Comment by daenney** [comment]
Yes it would but it's not that trivial, it's also a lot of data. We might have to sift through months of reports depending on how much you evict from PuppetDB to find 10 reports where something happened. This all depends on how dynamic your infrastructure is. The reason we're not doing it right now is because it's just too slow.

**Comment by rtib** [comment]
That might be true, and the choice to use puppetboard in front of competitors is mainly driven by its responsiveness. About the stored reports, however, I found no reason to set PuppetDB with a report-ttl higher than 30d. I think, that's about DB-Sizing. If someone needs to keep reports more than 30 days he must care about archiving. I understand PuppetDB as an operational database handling actual hot data interesting for operations. From an operations point of view there is nothing interesting in reports from months ago (I'm even not interested in what last week has happened).

**Comment by rtib** [comment]
Do You have a patch for that? Would it be possible to publish this feature in a separate branch?

**Comment by rafaelhenrique** [comment]
There are ways to ignore empty reports with queries in puppetdb ... if you want I can try to create a branch with this solution ... is of interest?

**Comment by rtib** [comment]
I'm definitely interested.

**Comment by rafaelhenrique** [comment]
I can create branch for this daenney?? That's ok for you?

**Comment by rafaelhenrique** [comment]
I can create paramether IGNORE_EMPTY_REPORTS on default_settings.py with values True|False... it would be cool

**Comment by daenney** [comment]
You can always create a branch and send a PR, you don't need my permission for that :smile:.

**Comment by rafaelhenrique** [comment]
Ok ... im new on github :/ ... thanks

**Comment by daenney** [comment]
@rafaelhenrique Ah, in that case have a look at https://guides.github.com/introduction/flow/ and https://help.github.com/articles/fork-a-repo/

**Comment by rafaelhenrique** [comment]
Read now ;)... my first PR on Spoon-Knife hahaha. Thanks

**Comment by rafaelhenrique** [comment]
I can not associate the PR #129 to this issue :/... this is normal ? :/

**Comment by daenney** [comment]
Well yeah, you can't just "add code" to an issue. Though by mentioning the issue in your PR you've linked them.

**Comment by rafaelhenrique** [comment]
Ok.. thanks

**Comment by rtib** [comment]
I've just reviewed the PR... :+1:

**Comment by corey-hammerton** [comment]
PuppetBoard >= 0.1.0 lists report status on nodes pages and the Reports tab is fully functional with pagination. Closing issue with this update and due to lack of activity.
