### ISSUE TITLE
Donut view for node states

### ISSUE THREAD

**Issue by raphink** [voxpupuli/puppetboard#159]
It would be great to be able to visualize node states with a donut view (like Foreman).

This can easily be achieved using c3js (already used in Puppet board): http://c3js.org/samples/chart_donut.html

I would assign this to myself, just as a reminder to code it someday (unless someone else wants to do it).

**Comment by simca114** [comment]
Where exactly is this visual desired? Im seeing a place for one in the overview page displaying the information for the failed, changed and unreported information. Anywhere else?

**Comment by raphink** [comment]
I'm thinking of the overview page indeed. Maybe a donut of resource types in the node view/report view too.

**Comment by corey-hammerton** [comment]
The Overview page is not a problem, the node/report views however need some work in order to be more efficient. 

It can definitely be done after https://github.com/voxpupuli/puppetboard/issues/202

**Comment by corey-hammerton** [comment]
Because the 0.2.0 release will include massive software updates I feel it is best to delay this request until a future release. Hopefully still in the 0.2.x releases.

I'm sorry for the continuing delay.

**Comment by corey-hammerton** [comment]
Is this still desired?

**Comment by raphink** [comment]
Haven't worked on it, but it could certainly be nice.

**Comment by manuq** [comment]
I think a better option is a bar chart of daily runs: #308

**Comment by mterzo** [comment]
I've updated the default_settings.py so that this can now be configured.  We may want to come back and add something to the GRAPH_FACTS array so that you can specify the type of graph you want per fact.
