### ISSUE TITLE
Sign latest release with gpg

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppetboard#174]
@corey-hammerton I'm currently packaging puppetboard for archlinux, could you sign the latest release with gpg [like described here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)? I could implement this in the package to increase the security and authenticity.

**Comment by corey-hammerton** [comment]
I like the idea, but as far as I am aware none of the other packages that we maintain are signed with GPG keys. Also there is no guarantee that some of the dependency packages are signed either.

We'll keep this in the backlog regardless, maybe if/when we get to 1.0 releases.

**Comment by bastelfreak** [comment]
Yes I know, but I thing we need to start somewhere (chicken-and-egg problem)

**Comment by mterzo** [comment]
Going to sign this next release.

**Comment by mterzo** [comment]
Signed!

https://pypi.python.org/pypi/puppetboard
