### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by llowder** [voxpupuli/puppetboard#197]
I recently updated to V 0.1.0 and I see new tabs - inventory, Catalogs and Environments.

However, in the readme these are not mentioned (I checked version 0.1.0, 0.1.1, and master) and not in the screenshot.

There is also no documentation on how to enable the Catalogs and whether or not that can be done independently of the Query tab.

**Comment by corey-hammerton** [comment]
One of the downsides with my development environment is that I have only up to 2 nodes so the screenshots that I can provide will not be full of content. 

However, we will update the readme for the 0.1.2 release.
