### ISSUE TITLE
More easily view all reports

### ISSUE THREAD

**Issue by br00tal** [voxpupuli/puppetboard#202]
Sorry if this has been discussed before, or if there's a way to achieve what I'm looking for.  This is more of an enhancement, not really an issue.

One aspect of Puppet Dashboard that was nice was being able to view a node's entire report/run history, all the way back to it's first (uploaded) report.  With Puppetboard, if I want to do something similar, I essentially have to set REPORTS_COUNT to be the same or higher than the TTL for reports in PuppetDB's config (for instance, if Puppet runs every 30 minutes, PuppetDB is configured with a 30d TTL for reports, and I want to see all 30 days of reports, I'd have to set REPORTS_COUNT to 1440).  The consequence of that is, on every node's "details" page (/node) and the Reports page (/reports), Puppetboard will show that many reports, since both use REPORTS_COUNT to display the last n reports.

I realize on the Reports page I can use the "first, next, last" navigation at the bottom to shift through reports, but it doesn't allow for very effective filtering, as it only filters the current page.  I also can't filter based on the run status (i.e. noop, changed, unchanged, etc.).

It'd be great to somehow separate those two pages (maybe two variables?) and on either page (probably the node's page as that would seem to make the most sense) be able to go back to the beginning of the reports/run history.

I'd be receptive to various ways of accomplishing this via Puppetboard.  Thanks for the great software.  It's definitely going in the right direction.

**Comment by corey-hammerton** [comment]
This is a good suggestion, I would like to implement this but I appears to be a hefty change. It would be best to release this in the next minor (semantic versioning) release.

**Comment by br00tal** [comment]
That's fair.  I figured it'd be a relatively large change.  The 0.2.0 milestone makes perfect sense to me.

**Comment by andrewfraley** [comment]
I'd like to suggest that the node's page use REPORTS_COUNT as the number of reports per page, and paginate the rest of the node's reports.

**Comment by br00tal** [comment]
The paginate idea sounds good, but it'd be best if the user could still search/filter throughout the entire history of stored reports.  For example, if someone wanted to search for "grub" to find any changes/reports containing that text, it shouldn't simply search the current page, but search the entire reports history, or at least provide an option to search the entire history.

**Comment by corey-hammerton** [comment]
There are a couple of options that we can implement:

1. Add a menu to the /reports pages to select between the default number (10), 25, 50, 100, All. The table filter on the page will then allow you to filter on report status

1. Add an optional query string value to filter on report status, like how the /nodes page works. This will affect the PuppetDB query and results. 

I will look into both options, but if you have a specific requirement or idea please specify.

**Comment by br00tal** [comment]
The first option seems like it'd address the bulk of my request.  Also, would it be possible to do something similar on the /node/<hostname> page?  It'd be nice to be able to view the full report history stored for individual servers, and to me the /node/<hostname> page makes sense to add it there.

**Comment by corey-hammerton** [comment]
In the /nodes page there is a Book icon at the right side of each node where you can query the available reports for a node. I can easily add a link on the /node/ page. I'll put it in the same PR when I'm able to work on it.

**Comment by corey-hammerton** [comment]
@br00tal Please see #245

**Comment by br00tal** [comment]
Thanks.  This looks good to me.  Appreciate you adding this functionality.
