### ISSUE TITLE
Update documentation on front page to add ENABLE_CATALOG

### ISSUE THREAD

**Issue by divad** [voxpupuli/puppetboard#206]
The front page on the wiki for puppetboard lists some important config options, but doesn't list the one most users will want to change: ENABLE_CATALOG. Can the documentation be updated to add that? Its in the default_settings.py file of course but not everybody will think of looking there.

**Comment by corey-hammerton** [comment]
There are several configuration options that were added to PuppetBoard that so far have not been documented. Closing this in favour of https://github.com/voxpupuli/puppetboard/issues/197
