### ISSUE TITLE
The v0.1.2 pip package does not install from pypi. Possible packaging issue?

### ISSUE THREAD

**Issue by jbehrends** [voxpupuli/puppetboard#223]
If you do a search for "puppetboard" at pypi you don't see the v0.1.2 package:
https://pypi.python.org/pypi?%3Aaction=search&term=puppetboard&submit=search

And if you click on the v0.1.1 version you see a reference to the latest version being 0.1.2:
https://pypi.python.org/pypi/puppetboard/0.1.1

If I use pip to perform a search of puppetboard, or even try to install puppetboard on a new clean machine I only get 0.1.1:
```
$ sudo pip search puppetboard
puppetboard     - Web frontend for PuppetDB
  INSTALLED: 0.1.1 (latest)
$
```

So I'm not sure what's up..  But it feels like something is wrong with the uploaded package of 0.1.2 at pypi.

**Comment by corey-hammerton** [comment]
I have noticed this too.

**Comment by blewa** [comment]
+1!

**Comment by corey-hammerton** [comment]
0.1.3 has been unofficially released. It contains the fixes that should have been included in 0.1.2, there is no difference otherwise.

**Comment by corey-hammerton** [comment]
Are you still experiencing this problem?

**Comment by jbehrends** [comment]
I installed pip package 0.1.3 without issue.  Everything is working great!

**Comment by corey-hammerton** [comment]
Awesome!.
