### ISSUE TITLE
Support for PuppetDB 4.0.0

### ISSUE THREAD

**Issue by apazga** [voxpupuli/puppetboard#224]
Hi!

Just reporting this little error on "Overview" tab after updating to PuppetDB 4.0.0.
Using latest puppetboard version from pip.

![puppetboard_puppetdb4 0](https://cloud.githubusercontent.com/assets/6894350/13878552/818dd318-ed12-11e5-8455-a4ae4f60dd04.png)

The others tabs seems to work fine as usual.

Best regards!
Abel.

**Comment by corey-hammerton** [comment]
PuppetDB 4.0 has a brand new major release, puppetboard and pypuppetdb are built for PuppetDB 3.x. PuppetDB 4.0.0 and higher are not supported yet.

**Comment by apazga** [comment]
Thanks @corey-hammerton.
Just added the issue for tracking the possible future support for PuppetDB >4.
Are there plans to support it soon? If is not planned shortly, don't worry, close the issue and I'll check the repo regularly.

**Comment by corey-hammerton** [comment]
It is definitely on the roadmap but I do not know presently when those new versions will be released. 

Please keep this issue open for our tracking.

Can you please paste some log entries showing the errors?

**Comment by erikanderson** [comment]
Having the same issue. I will look at it this weekend

**Comment by apazga** [comment]
My puppetboard log when you click on "Overview" tab.

```
==> /var/log/httpd/puppetboard.error.log <==
[Mon Mar 21 08:36:07.584460 2016] [:error] [pid 31550] INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: puppetdb.mycompanydomain.com
[Mon Mar 21 08:36:07.608437 2016] [:error] [pid 31550] ERROR:pypuppetdb.api:{
[Mon Mar 21 08:36:07.608501 2016] [:error] [pid 31550]   "error" : "No information is known about mbean puppetlabs.puppetdb.query.population:type=default,name=num-nodes"
[Mon Mar 21 08:36:07.608521 2016] [:error] [pid 31550] } puppetdb.mycompanydomain.com:8080 over HTTP.
```

**Comment by octomike** [comment]
If you made the same mistake as myself and upgraded puppetdb without a proper schema backup, here is a quickfix to get the Overview page working again :laughing: 

Luckily the prefix is defined in puppetboard so we don't have to touch pypuppetdb to work around this.

```diff
diff --git a/puppetboard/app.py b/puppetboard/app.py
index e651924..6934a2e 100644
--- a/puppetboard/app.py
+++ b/puppetboard/app.py
@@ -3,6 +3,7 @@ from __future__ import absolute_import
 
 import logging
 import collections
 try:
     from urllib import unquote
 except ImportError:
@@ -142,16 +143,16 @@ def index(env):
     if env == '*':
         query = None
 
-        prefix = 'puppetlabs.puppetdb.query.population'
+        prefix = 'puppetlabs.puppetdb.population'
         num_nodes = get_or_abort(
             puppetdb.metric,
-            "{0}{1}".format(prefix, ':type=default,name=num-nodes'))
+            "{0}{1}".format(prefix, ':name=num-nodes'))
         num_resources = get_or_abort(
             puppetdb.metric,
-            "{0}{1}".format(prefix, ':type=default,name=num-resources'))
+            "{0}{1}".format(prefix, ':name=num-resources'))
         avg_resources_node = get_or_abort(
             puppetdb.metric,
-            "{0}{1}".format(prefix, ':type=default,name=avg-resources-per-node'))
+            "{0}{1}".format(prefix, ':name=avg-resources-per-node'))
         metrics['num_nodes'] = num_nodes['Value']
         metrics['num_resources'] = num_resources['Value']
         metrics['avg_resources_node'] = "{0:10.0f}".format(
```

**Comment by apazga** [comment]
:+1: Yeah, that worked.
Perfect workaround for using it by now with PuppetDB 4, until the fix come!
Thanks @octomike

**Comment by erikanderson** [comment]
Major props @octomike, this is why I love OSS

**Comment by corey-hammerton** [comment]
Fixed by https://github.com/voxpupuli/puppetboard/pull/228
