### ISSUE TITLE
Proxying via Nginx (sub-URI issues)

### ISSUE THREAD

**Issue by HenryCook** [voxpupuli/puppetboard#225]
Hi All,

I've managed to set up Puppetboard using a mixture of Gunicorn and Nginx, thanks to the fantastic documentation provided. 

Now my problem arises when I want to proxy using Nginx from another host to the Puppetboard instance. The idea is that we have a url like `http://monitoring.company.com/` and then each base-URI is a different tool e.g. `http://monitoring.company.com/puppetboard/. Here's an example of the Nginx proxying config:

```
 # Proxy /puppetboard to Puppetboard
      location /puppetboard/ {
        proxy_pass http://puppetboard.location.com:8079/;
      }
```

That snippet above directs me to the base of Puppetboard, but as soon as I select another tab (lets say 'node'), I get a 502 gateway error because Nginx was expecting `/puppetboard/node` and not `/node` which is fair enough. Another issue is that the static files aren't available because again it's being served from `/static` and not `/puppetboard/static`.

To remedy the situation I fudged `app.py` and prepended a `route_prefix` to each route (not something I'm proud of and something I'm hoping to avoid). You can find the amended `app.py` [here](https://gist.github.com/HenryCook/d4c9794fe32b6d618620)

This still doesn't solve my static files problem as it all displays, but not how it's meant to.

I can see a similar question has been asked previously in issue #74 however I'm hoping to roll out Puppetboard and proxy via the 'over-arching' Nginx proxy.

Is there a way to somehow change the static url so it also takes the set `route_prefix`? I can imagine there are far better ways around this issue so I'd appreciate any help on this.

We're using Puppetboard version 0.0.5 as our PuppetDB version is 2.3, so apologise if a fix has been released for this in a newer version of Puppetboard.

Thanks for any help you can provide!

**Comment by corey-hammerton** [comment]
I'm no expert in Nginx or gunicorn but it looks to me like your receiving web server is expecting / and /node instead of /puppetboard/ and /puppetboard/node respectively. Perhaps you need to configure a URL prefix in your puppetboard.location.com:8079 server configuration. 

This does not appear to be a programming issue.

**Comment by HenryCook** [comment]
Thanks for the reply.

I've tried a few things in terms of `rewrite` and `proxy_pass`, however nothing's solved the issue I'm experiencing. Can imagine this is solve-able via Nginx but I've hit a brick wall. Due to the nature of the Nginx proxy we have in place, it already has multiple locations and rewrites, so I'm hoping to not introduce any more unnecessary complexities.

Think I'm going to approach this from a different angle and not use the proxy as it's only causing headaches, and I can then ditch the ugly `route_prefix` too.

I understand this isn't a programming issue, was just looking for a potential fix, as there's probably a smarter solution to what I was doing.

Really appreciate the help.

**Comment by BcTpe4HbIu** [comment]
If I understand correctly, there must be some parameter in puppetboard config to specify root of application. At least because nginx unable to replace all links in application response to match real root.

**Comment by HenryCook** [comment]
That's correct.

Would this be via the use of Flask's [configuration management](http://flask.pocoo.org/docs/0.10/config/)?

From what I understand, I need to set `app.config["APPLICATION_ROOT"] = "/puppetboard"` in `app.py`.

**Comment by BcTpe4HbIu** [comment]
```APPLICATION_ROOT = '/puppetboard'``` in the settings file should be enough.

**Comment by HenryCook** [comment]
That's great, I'll give it a go and let you know how I got on.

**Comment by HenryCook** [comment]
While that amends the root of Puppetboard I'm still experiencing the issue of the static files not being accessible. Reason being is that the Nginx proxy_pass is essentially wanting `/puppetboard/static` and not `/static`. Please correct me if I'm wrong though.

I think I'm just going to use a separate server block in Nginx with a different hostname like http://puppetboard.company.com to serve it, as opposed to sub directories via locations.

**Comment by BcTpe4HbIu** [comment]
@HenryCook Your nginx config should already have /static location. You should change it to /puppetboard/static.

**Comment by HenryCook** [comment]
I have changed the Nginx config that is serving Gunicorn from `/static` to `/puppetboard/static` which works as I want it to, but the Nginx proxy to that is still exhibiting the previous issue of static files not being served. See below for the proxy's config.

```
 # Proxy /puppetboard to Puppetboard
      location /puppetboard/ {
        proxy_pass http://puppetboard.location.com:8079/puppetboard/;
      }
```

I've tried different variations with and without slashes, and also the puppetboard root but no dice.

Really do appreciate your help but I think I'm just going to do what I said previously mentioned, and split it out via hostname rather than go down the sub dir route.

**Comment by HenryCook** [comment]
Just wanted to leave a little comment with how I resolved the issue via the Nginx proxy.

```
# Proxy /puppetboard to Puppetboard
      location /puppetboard/ {
        proxy_pass http://monitoring.company.com:1234/puppetboard/;
      }

# Proxy to display all static content for Puppetboard to display properly.
      location /static/ {
        proxy_pass http://monitoring.company.com:1234;
      }
``` 

After applying the `APPLICATION_ROOT` fix as kindly stated by BcTpe4HbIu, I was able to set the base to '/puppetboard' and then pass an request for 'static' to go to the host stated above.

Please note that there is no trailing slash for the '/static/' proxy_pass.

The only issue with this solution is that ANYTHING requesting resources from '/static/' will be sent to that host on that port. Not great, but is working for the time being.

**Comment by BcTpe4HbIu** [comment]
After some research I found that you can specify url for static folder only on [application object creation](https://github.com/voxpupuli/puppetboard/blob/master/puppetboard/app.py#L28). There is a [parameter for application object constructor](http://flask.pocoo.org/docs/0.10/api/#application-object) and no way to change it later.

**Comment by m4ce** [comment]
I also had to get this working and bumped into most of issues previously outlined. I did publish my work on this at https://github.com/m4ce/docker-puppetboard . I've enabled puppetboard in a sub-location (/puppetboard) and got both templates and static files to work.
