### ISSUE TITLE
After upgrade to 0.1.2 error 500 in all facts

### ISSUE THREAD

**Issue by betorvs** [voxpupuli/puppetboard#238]
Hi all!
I upgraded to 0.1.2 from 0.1.1 and now I receive error in all facts, like architeture, lsbrelease, domain.
I change log level to debug and find this:
[Wed May 11 18:08:17.643928 2016] [:error] [pid 29196:tid 139886690535168] ERROR:puppetboard.app:Exception on /fact/architecture [GET]
[Wed May 11 18:08:17.643963 2016] [:error] [pid 29196:tid 139886690535168] Traceback (most recent call last):
[Wed May 11 18:08:17.643972 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Wed May 11 18:08:17.643979 2016] [:error] [pid 29196:tid 139886690535168]     response = self.full_dispatch_request()
[Wed May 11 18:08:17.643985 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed May 11 18:08:17.643991 2016] [:error] [pid 29196:tid 139886690535168]     rv = self.handle_user_exception(e)
[Wed May 11 18:08:17.643997 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Wed May 11 18:08:17.644003 2016] [:error] [pid 29196:tid 139886690535168]     reraise(exc_type, exc_value, tb)
[Wed May 11 18:08:17.644009 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed May 11 18:08:17.644015 2016] [:error] [pid 29196:tid 139886690535168]     rv = self.dispatch_request()
[Wed May 11 18:08:17.644021 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed May 11 18:08:17.644049 2016] [:error] [pid 29196:tid 139886690535168]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed May 11 18:08:17.644062 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 689, in fact
[Wed May 11 18:08:17.644068 2016] [:error] [pid 29196:tid 139886690535168]     name=fact, query=query))]
[Wed May 11 18:08:17.644073 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/utils.py", line 42, in yield_or_stop
[Wed May 11 18:08:17.644079 2016] [:error] [pid 29196:tid 139886690535168]     yield next(generator)
[Wed May 11 18:08:17.644083 2016] [:error] [pid 29196:tid 139886690535168]   File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/__init__.py", line 534, in facts
[Wed May 11 18:08:17.644089 2016] [:error] [pid 29196:tid 139886690535168]     facts = self._query('facts', query=query, **kwargs)
[Wed May 11 18:08:17.644098 2016] [:error] [pid 29196:tid 139886690535168] TypeError: _query() got multiple values for keyword argument 'query'
[Wed May 11 18:08:17.644241 2016] [:error] [pid 29196:tid 139886690535168] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None

Any ideas?? Can anyone help me?

**Comment by corey-hammerton** [comment]
It looks like you are suffering from a bug introduced https://github.com/voxpupuli/pypuppetdb/issues/67

Please log a ticket with https://github.com/voxpupuli/pypuppetdb. In the meantime please downgrade your version of pypuppetdb to 0.2.1

**Comment by betorvs** [comment]
Hi @corey-hammerton thanks for the solution.
(I do this, if anyone need: pip install -I pypuppetdb==0.2.1).

**Comment by corey-hammerton** [comment]
Closing this issue as it does not apply to this project.
