### ISSUE TITLE
pie chart aggregates data incorrectly

### ISSUE THREAD

**Issue by chris-bmj** [voxpupuli/puppetboard#246]
The fact pie charts seem to have a maximum of 16 labelled categories, with the 16th being 'other'.  I can understand why it might make sense to limit the number of categories visible (though I think it should probably be a higher number than this) but the real problem is that it aggregates them incorrectly, to my mind at least.  

Surely the 'other' category should be made up of the categories with the smallest sizes should it not? In other words so the largest 15 categories should be displayed with labels, then the remaining categories aggregated into 'others'.  This is not what happens though, instead it seems to put categories into 'others' at random, so the largest two or three might be aggregated into 'others' while multiple tiny categories are shown.  This renders the chart meaningless much of the time.

**Comment by sigmunau** [comment]
This sounds like a duplicate report of an issue I reported and submitted a fix for. But this fix got rejected for some unknown reason: https://github.com/voxpupuli/puppetboard/pull/130

**Comment by corey-hammerton** [comment]
@sigmunau another PR was submitted recently with the exact same changes as the one you submitted what was merged. https://github.com/voxpupuli/puppetboard/pull/242

**Comment by juniorsysadmin** [comment]
Possibly fixed by #242
