### ISSUE TITLE
Reports not showing in puppetboard.

### ISSUE THREAD

**Issue by Hemantt91** [voxpupuli/puppetboard#253]
I am running puppetdb(2.3) and puppetboard(0.0.5) on the same machine. All is working good but 
Reports is not showing in puppetboard. It is showing (What you were looking for could not be found in PuppetDB.)
Seems like reports are Disable 
Attaching some screen shots here :
![puppetboarderror](https://cloud.githubusercontent.com/assets/6639174/15885065/17e29926-2d72-11e6-87f9-704839ffa9e4.png)

Some one please help me

**Comment by corey-hammerton** [comment]
Some of the possible causes:

- The timezone on your nodes is different than others (unlikely though)
- The time on your nodes is out of sync. Please ensure that ntp or some other time-syncing service is running
- The puppet services have report = false in their configurations, must be true.

**Comment by corey-hammerton** [comment]
To ensure that reports are being sent to PuppetDB run the following command:

`curl http://<puppetdb_host>:<puppetdb_port>/v3/reports`

**Comment by Hemantt91** [comment]
Thank you corey. 

We can close this for now.
