### ISSUE TITLE
puppetboard support for puppetdb 4?

### ISSUE THREAD

**Issue by xtimmu** [voxpupuli/puppetboard#254]
The README says: As of version 0.1.0 and higher, Puppetboard requires PuppetDB 3.
I assume this does not mean "at least 3", but only 3?

Is there a plan to support PuppetDB 4

**Comment by mcanevet** [comment]
@xtimmu master works fine with PuppetDB 4 (see https://github.com/voxpupuli/pypuppetdb/issues/66)

**Comment by corey-hammerton** [comment]
Version 0.2.0 will have breaking support for PuppetDB 4.0. It should be release this weekend or soon thereafter.

**Comment by xtimmu** [comment]
Awesome! Thanks.
