### ISSUE TITLE
Can't connect to puppetdb (ERROR:pypuppetdb.api:Not Found 127.0.0.1:8080 over HTTP)

### ISSUE THREAD

**Issue by Fooobar23** [voxpupuli/puppetboard#255]
apt-cache policy puppetdb
puppetdb:
  Installed: 2.3.8-1puppetlabs1
  Candidate: 2.3.8-1puppetlabs1
  Version table:

ss -tlnp | grep :8080
LISTEN     0      50         ::ffff:127.0.0.1:8080                    :::*      users:(("java",11983,17))

telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

ERROR my Apache Log:

[Fri Jun 17 13:34:41.029410 2016] [:error] [pid 4783] [client 10.131.0.185:41957] NotFound: 404: Not Found
[Fri Jun 17 13:34:42.665628 2016] [:error] [pid 4779] [client 10.131.0.185:41958] [2016-06-17 13:34:42,662] ERROR in app: Exception on / [GET]
[Fri Jun 17 13:34:42.665650 2016] [:error] [pid 4779] [client 10.131.0.185:41958] Traceback (most recent call last):
[Fri Jun 17 13:34:42.665656 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
[Fri Jun 17 13:34:42.665661 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     response = self.full_dispatch_request()
[Fri Jun 17 13:34:42.665666 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[Fri Jun 17 13:34:42.665671 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     rv = self.handle_user_exception(e)
[Fri Jun 17 13:34:42.665691 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1539, in handle_user_exception
[Fri Jun 17 13:34:42.665697 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     return self.handle_http_exception(e)
[Fri Jun 17 13:34:42.665701 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1498, in handle_http_exception
[Fri Jun 17 13:34:42.665706 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     return handler(e)
[Fri Jun 17 13:34:42.665711 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 108, in not_found
[Fri Jun 17 13:34:42.665715 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     envs = environments()
[Fri Jun 17 13:34:42.665914 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 71, in environments
[Fri Jun 17 13:34:42.665921 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     envs = get_or_abort(puppetdb.environments)
[Fri Jun 17 13:34:42.665926 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/utils.py", line 26, in get_or_abort
[Fri Jun 17 13:34:42.665931 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     abort(e.response.status_code)
[Fri Jun 17 13:34:42.665947 2016] [:error] [pid 4779] [client 10.131.0.185:41958]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 646, in __call__
[Fri Jun 17 13:34:42.665952 2016] [:error] [pid 4779] [client 10.131.0.185:41958]     raise self.mapping[code](*args, **kwargs)
[Fri Jun 17 13:34:42.665957 2016] [:error] [pid 4779] [client 10.131.0.185:41958] NotFound: 404: Not Found

#####################################

[Fri Jun 17 13:34:42.578892 2016] [:error] [pid 4779] INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
[Fri Jun 17 13:34:42.640418 2016] [:error] [pid 4779] ERROR:pypuppetdb.api:Not Found 127.0.0.1:8080 over HTTP.
[Fri Jun 17 13:34:42.661654 2016] [:error] [pid 4779] ERROR:pypuppetdb.api:Not Found 127.0.0.1:8080 over HTTP.
[Fri Jun 17 13:34:42.666040 2016] [:error] [pid 4779] ERROR:puppetboard.app:Exception on / [GET]
[Fri Jun 17 13:34:42.666051 2016] [:error] [pid 4779] Traceback (most recent call last):
[Fri Jun 17 13:34:42.666056 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
[Fri Jun 17 13:34:42.666060 2016] [:error] [pid 4779]     response = self.full_dispatch_request()
[Fri Jun 17 13:34:42.666065 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[Fri Jun 17 13:34:42.666069 2016] [:error] [pid 4779]     rv = self.handle_user_exception(e)
[Fri Jun 17 13:34:42.666074 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1539, in handle_user_exception
[Fri Jun 17 13:34:42.666079 2016] [:error] [pid 4779]     return self.handle_http_exception(e)
[Fri Jun 17 13:34:42.666083 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1498, in handle_http_exception
[Fri Jun 17 13:34:42.666087 2016] [:error] [pid 4779]     return handler(e)
[Fri Jun 17 13:34:42.666091 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 108, in not_found
[Fri Jun 17 13:34:42.666096 2016] [:error] [pid 4779]     envs = environments()
[Fri Jun 17 13:34:42.666100 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 71, in environments
[Fri Jun 17 13:34:42.666104 2016] [:error] [pid 4779]     envs = get_or_abort(puppetdb.environments)
[Fri Jun 17 13:34:42.666108 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/utils.py", line 26, in get_or_abort
[Fri Jun 17 13:34:42.666149 2016] [:error] [pid 4779]     abort(e.response.status_code)
[Fri Jun 17 13:34:42.666154 2016] [:error] [pid 4779]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 646, in __call__
[Fri Jun 17 13:34:42.666158 2016] [:error] [pid 4779]     raise self.mapping[code](*args, **kwargs)
[Fri Jun 17 13:34:42.666163 2016] [:error] [pid 4779] NotFound: 404: Not Found
[Fri Jun 17 13:34:42.681297 2016] [:error] [pid 4779] ERROR:pypuppetdb.api:Not Found 127.0.0.1:8080 over HTTP.

What is here the problem?

**Comment by corey-hammerton** [comment]
What version of PuppetBoard have you installed?

Version 0.0.5 is the latest version that supports PuppetDB < 3.0

**Comment by Fooobar23** [comment]
Hi,

i tested it with 0.0.5 and the same behavior.

**Comment by corey-hammerton** [comment]
Please ensure that your server isn't holding onto cached or pre-compiled code and submit your logs.

**Comment by currupipi** [comment]
Hi, I had the same problem and I reinstalled  puppetboard forcing version 0.0.5 (because my puppetb is actually < 3.0)  and now is working, many thanks for the advise of compatibility

Cheers

**Comment by corey-hammerton** [comment]
Closing this ticket as it involves known compatibility issues.
