### ISSUE TITLE
Internal Server Error on Metrics links

### ISSUE THREAD

**Issue by silver-james** [voxpupuli/puppetboard#258]
Hi!
I've installed Puppetboard recently and it's working fine, excepting the Metrics tab
When I click on a link, it returns "Internal Server Error"

![captura de pantalla de 2016-06-21 10-24-39](https://cloud.githubusercontent.com/assets/6978992/16222812/6a9e1a64-379a-11e6-99d5-1a871f1a3098.png)
![captura de pantalla de 2016-06-21 10-25-34](https://cloud.githubusercontent.com/assets/6978992/16222824/81c4015e-379a-11e6-8d42-b4c7d675be42.png)

The others tabs (facts, reports, catalogs...) works fine, so I assume that connection to PuppetDB is OK

Thanks for your help!

**Comment by corey-hammerton** [comment]
What information is available in your Web server logs?
Can you see anything in the PuppetDB logs?

**Comment by silver-james** [comment]
Apache error log:
[httpd-error_log.txt](https://github.com/voxpupuli/puppetboard/files/327125/httpd-error_log.txt)

PuppetDB access log:
[puppetdb-access_log.txt](https://github.com/voxpupuli/puppetboard/files/327128/puppetdb-access_log.txt)

All services (PuppetDB and HTTPD) are in the same server

**Comment by corey-hammerton** [comment]
What software versions are you running? (Of Puppetboard, pypuppetdb, PuppetDB)

**Comment by silver-james** [comment]
Puppetboard 0.1.3
Pypuppetdb 0.2.3
PuppetDB 4.1.0-1

El 22/6/2016 15:11, Corey Hammerton <notifications@github.com> escribió:

What software versions are you running? (Of Puppetboard, pypuppetdb, PuppetDB)

**Comment by silver-james** [comment]
I haven't patched anything. I installed it using pip and set the config files.

Thanks. I'll wait for version 0.2.0
