### ISSUE TITLE
pep8/pylint + travis ci

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppetboard#266]
Created a first stab at a travis ci config and stock style guide.

https://travis-ci.org/mterzo/puppetboard

Do you have a preference on coding standard?  I looked at puppetdb, and I didn't see any python style guides.

**Comment by juniorsysadmin** [comment]
PEP8 + pylint sounds good

**Comment by juniorsysadmin** [comment]
Also docs say that Puppet 2.6 is supported as well as Puppet 2.7, so you may need to use an earlier version of pylint to reflect this.

**Comment by mterzo** [comment]
Support for Python 2.6? You said puppet.

**Comment by juniorsysadmin** [comment]
> Support for Python 2.6? You said puppet. 

Sorry I meant Python not Puppet. Fixed

**Comment by mterzo** [comment]
Are you expecting me to start writing tests?

**Comment by corey-hammerton** [comment]
Sorry, I haven't had a chance to work on the project. 

I do not expect you to write test cases, in fact this is much more than what we previously had for Puppetboard. Thank you for your work.

**Comment by corey-hammerton** [comment]
Travis CI has been successfully integrated.
