### ISSUE TITLE
Display report events as string rather than unicode

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppetboard#281]
Currently the array content of a report events is parsed in Python as unicode and end up displayed as such in the /report view. 

``` html
<td>{{event.item['old']}}</td>
<td>{{event.item['new']}}</td>
```

Can end up shown as [u'text'].

I don't know if that applies to other types or just some edge cases like array of strings.
Should this be tackled in PuppetBoard or pypuppetdb's generator yielding Events?

**Comment by gdubicki** [comment]
Closing as outdated. Please reopen if you still experience such problem with the current version of the Puppetboard.
