### ISSUE TITLE
Overview and Nodes views fail for default ENV 

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppetboard#287]
For some reason, the 'Overview' and 'Nodes' views fail when browsing for the default environment (production).
The problem seems to be 'node.latest_report_hash' in line 92 in index.html and line 31 in nodes.html.
I get such an error:
```shell
BuildError: Could not build url for endpoint 'report' with values ['env', 'node_name']. Did you forget to specify values ['report_id']?
```
It takes 3 parameters, the third one being a report_id doesn't exist.
Adding a check in the 'if' block surrounding these two lines in their templates is enough to fix the issue for me:
```html
{% if node.report_timestamp and node.latest_report_hash%}
```

**Comment by corey-hammerton** [comment]
It looks to me like you are running on a newer version of PuppetBoard with an old version of PuppetDB.

What version of software are you running?
Puppetboard
Pypuppetdb
PuppetDB

NOTE: PuppetBoard 0.2.0 only supports PuppetDB 4.x. PuppetBoard 0.1.0 only supports PuppetDB 3.x

**Comment by tux-o-matic** [comment]
Guess that's it. I'm on PuppetDB 3.0.2. But then I'm surprised at the level of compatibility between PuppetBoard 0.2.0 and the endpoints of PuppetDB 3. 
By just modifying two lines I seem to have everything working in PuppetBoard.

Since those two modified lines seem to bring backward compatibility, isn't a PR possible?

**Comment by corey-hammerton** [comment]
PuppetLabs tend to release breaking changes between major versions, in the case of PuppetDB 3 and 4 the paths to population related metrics have changed. 

It is true that most things will work on PuppetDB 3.x and PuppetBoard 0.2.x, some things will not. It is easier for code maintainability to enforce the breaking changes between major version release of PuppetDB. A backward compatibility PR will not be possible. Please refer to the [PuppetDB Release Notes](https://docs.puppet.com/puppetdb/4.1/release_notes.html) for more details.

**Comment by corey-hammerton** [comment]
Will close this issue since it is a known backwards compatibility issue and will not fix.
