### ISSUE TITLE
Show current environment in nav bar

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppetboard#290]
People pointed out to me that having the current environment in the URL path isn't obvious enough (and not there when in the default environment).
It would be nice if the current environment name was shown in the nav bar next to the dropdown selector.

**Comment by corey-hammerton** [comment]
The current environment is shown in the dropdown menu options with bold letters and different shading.

To your request showing the environment name next to the dropdown selector expands the width of the navbar almost to the point of overflowing the screen, depending on the name. I do agree with you that we should make the current environment more obvious. How do you suggest we do that?

**Comment by tux-o-matic** [comment]
@corey-hammerton Maybe to be more clear, the suggestion/problem is to have the current environment shown in the UI at all time without needing to click on the dropdown.

If we're restricted by the current dimensions, we could be:
- Replace "Environments" by the name of the current environment.
- Change the background color of the slot used by the drop down and/or change to bold to increase attention to the fact that the slot has a more specific role.
