### ISSUE TITLE
Odd fact quoting array of hashes

### ISSUE THREAD

**Issue by james-powis** [voxpupuli/puppetboard#292]
I apologize if this is a PEBCAK issue,

puppetboard display of fact key and value of a hash nested inside an array index are displayed in u'<text>' quoting fashion, example:
`[{u'used_KB': u'21291908', u'avail_KB': u'83941612', u'mount_point': u'/', u'file_system': u'/dev/mapper/vg00-lv_root', u'size_KB': u'110866696'}, {u'used_KB': u'62596', u'avail_KB': u'399456', u'mount_point': u'/boot', u'file_system': u'/dev/sda1', u'size_KB': u'487652'}, {u'used_KB': u'290944', u'avail_KB': u'7415508', u'mount_point': u'/home', u'file_system': u'/dev/mapper/vg00-lv_home', u'size_KB': u'8125880'}, {u'used_KB': u'23396', u'avail_KB': u'1870420', u'mount_point': u'/tmp', u'file_system': u'/dev/mapper/vg00-lv_tmp', u'size_KB': u'1998672'}, {u'used_KB': u'228020', u'avail_KB': u'7478432', u'mount_point': u'/var', u'file_system': u'/dev/mapper/vg00-lv_var', u'size_KB': u'8125880'}]`

This is using the following snipet to store the custom code (abbreviated):
```Ruby
      file_system = str[0]
      disk_size  = str[1]
      disk_used  = str[2]
      disk_avail = str[3]
      mount_points = {
        "mount_point" => mount_point,
        "size_KB"     => disk_size,
        "used_KB"     => disk_used,
        "avail_KB"    => disk_avail,
        "file_system" => file_system,
      }
      fact_data.push(mount_points)
      setcode do
         fact_data
      end
```

I can confirm that the data within puppetdb appears at first glance to not be weird in any way:
```Puppet
> curl -X GET https://localhost:8081/pdb/query/v4/facts/mounts 
[ {
  "certname" : "test-node",
  "environment" : "production",
  "name" : "mounts",
  "value" : [ {
    "avail_KB" : "83941644",
    "file_system" : "/dev/mapper/vg00-lv_root",
    "mount_point" : "/",
    "size_KB" : "110866696",
    "used_KB" : "21291876"
  }, {
    "avail_KB" : "399456",
    "file_system" : "/dev/sda1",
    "mount_point" : "/boot",
    "size_KB" : "487652",
    "used_KB" : "62596"
  }, {
    "avail_KB" : "7415520",
    "file_system" : "/dev/mapper/vg00-lv_home",
    "mount_point" : "/home",
    "size_KB" : "8125880",
    "used_KB" : "290932"
  }, {
    "avail_KB" : "1870420",
    "file_system" : "/dev/mapper/vg00-lv_tmp",
    "mount_point" : "/tmp",
    "size_KB" : "1998672",
    "used_KB" : "23396"
  }, {
    "avail_KB" : "7478440",
    "file_system" : "/dev/mapper/vg00-lv_var",
    "mount_point" : "/var",
    "size_KB" : "8125880",
    "used_KB" : "228012"
  } ]
} ]
```

I don't even know where to begin to ascertain if this is an issue with puppetboard displaying array of hashes structured facts or if something else is to blame (like the fact code).

**Comment by corey-hammerton** [comment]
This has been an issue since PuppetDB started supporting structured facts and we've not found an easy way to query them. 

With PuppetDB 4.2 dot notation and a new Inventory endpoint are available, support for these is planned for the 0.3.0 release. 

In the meantime closing this in favour of #83
