### ISSUE TITLE
JSON of Radiator view

### ISSUE THREAD

**Issue by peelman** [voxpupuli/puppetboard#303]
the Radiator view is a great addition to v0.2.0, thank you for that.  One tweak I'd ask is a JSON endpoint (basically respond to server.tld/radiator.json) that returns the same data, just unformatted and in raw JSON.

Any thoughts?

**Comment by mterzo** [comment]
#319 added this feature.

**Comment by peelman** [comment]
This doesn't seem to have made it into the 0.2.1 release.

**Comment by mterzo** [comment]
it was. Set the accept header to application/Json and it will return Json data.
