### ISSUE TITLE
Looking for Volunteers

### ISSUE THREAD

**Issue by corey-hammerton** [voxpupuli/puppetboard#305]
I regret having to make this request. Due to changing circumstances in my life I will no longer be an active maintainer on this project. I still hope to contribute code but it will be at an infrequent rate. I have greatly enjoyed being a part of this project, helping to push it into the PuppetDB 3.x generation and beyone.

Anyone who wishes to step up please provide the following:
- [ ] Github username
- [ ] Pypi username

As @daenney mentioned in #132  we expect this project to remain in the voxpupuli community since this project was started by members of the Puppet Community and should remain there.

**Comment by mterzo** [comment]
No one has stepped up.  I've only contributed a tiny portion of code to this project but would like to see it well maintained.  I'm can to help, I'm `mterzo` on both. Though I have never published a module to pypi.

**Comment by daenney** [comment]
@mterzo Have a look at http://python-packaging.readthedocs.io in that case and https://packaging.python.org/distributing/ for the upload parts.

**Comment by daenney** [comment]
In general even without an official maintainer I don't expect this to be a large problem since we have a whole collective of Puppeteers that can merge things for this.

**Comment by mterzo** [comment]
Alright. I've been on/off the slack channel.  IRC has better interaction?

**Comment by daenney** [comment]
Yes, it's usually much more busy over there since most folks prefer IRC.

**Comment by corey-hammerton** [comment]
@mterzo I have granted you permissions to maintain the pypi packages, however, I cannot add you to the group because I'm not an organization owner. Will need help from @daenney for this.

Sorry for the delay.

**Comment by mterzo** [comment]
Thanks @corey-hammerton.

**Comment by bastelfreak** [comment]
Hai @mterzo. I invited you to the Vox Pupuli org and granted you write access to this repo. @corey-hammerton did you mean the tools/python group? That is the one I used now for Mike.

**Comment by corey-hammerton** [comment]
Yes. Thank you @bastelfreak

**Comment by juniorsysadmin** [comment]
Closing, I think this is done
