### ISSUE TITLE
Error if no production env

### ISSUE THREAD

**Issue by cfasnacht** [voxpupuli/puppetboard#307]
The browser shows an error if the production environment doesn't exist. My puppet master runs on development and I didn't yet have any production nodes. 
Error: 404
Not found
Not found in Puppetdb something

**Comment by corey-hammerton** [comment]
Add to your `settings.py` file the `DEFAULT_ENVIRONMENT` setting and change it to 'development' or '*'. It is set to 'production' by default.

**Comment by cfasnacht** [comment]
Thanks I allready found out about development. I would just like if you could throw an error, I search for quite some time because I thought I have an error in my Puppetdb or Puppetboard configuration.
Thanks I didn't try *.
