### ISSUE TITLE
Bar chart of daily run status

### ISSUE THREAD

**Issue by manuq** [voxpupuli/puppetboard#308]
I'm pushing my company to move from the old puppet-dashboard to this puppetboard. One of the things we miss is the chart of daily run status. The chart is great to get an overall picture of the nodes status as the time pass, not only the instant information given by the main page or the radiator.

I have coded the bar chart it in a fork I have with customizations. But I think this one can be useful for everyone. If there is interest I'll be happy to provide a clean commit. It looks like this:

![daily-reports-overview](https://cloud.githubusercontent.com/assets/83944/19579649/0e988668-9722-11e6-8e64-af8944625b1b.png)

![daily-reports-certname](https://cloud.githubusercontent.com/assets/83944/19579661/160c2e54-9722-11e6-8bb1-395d76b03728.png)

And relies on c3.js which is already used in other parts.

**Comment by mterzo** [comment]
In your view I do t see how the math adds up. Your population is 900 nodes but you have 3500 unchanged for the day.

I'm guessing that is not related to nodes but the number of executions of puppet.

**Comment by manuq** [comment]
@mterzo yes is the number of executions.

The queries are these:
```
QUERY_STATUS_COUNT_ALL = ('["extract", [["function","count"], "status"], '
                          '["and", [">=","start_time","{start}"], ["<","start_time","{end}"]], '
                          '["group_by", "status"]]')

QUERY_STATUS_COUNT_CERTNAME = ('["extract", [["function","count"], "status"], '
                               '["and", ["=","certname","{certname}"], [">=","start_time","{start}"], ["<","start_time","{end}"]], '
                               '["group_by", "status"]]')

```

**Comment by mterzo** [comment]
I see the idea you are going for.  Im trying to understand the benefit when applying it to my environment.  In theory where all your nodes are checking in its just n * checks a day. 

Change the window and grouping to be more granular you could show herding.

**Comment by manuq** [comment]
For reference this is how this looked like in the old board:

![daily-reports-overview-old](https://cloud.githubusercontent.com/assets/83944/19609584/528d662a-97d8-11e6-974d-492fb4fc8caa.png)
![daily-reports-certname-old](https://cloud.githubusercontent.com/assets/83944/19609587/56c91ca2-97d8-11e6-8c92-c822508aad06.png)


There is also a curve for the duration time in the nodes page. But I haven't found it useful.

**Comment by corey-hammerton** [comment]
This is definitely something I've kind of wanted. Please create a clean PR.

**Comment by mterzo** [comment]
Oh, the runtime looks nifty.  Nice to see spike of load on the server or find when updates are taking a long time.  updates times taking a long time could "gum" up the works.  I haven't had a chance to look at your PR.  You've done all the hard work to start the graph for herding.

**Comment by raphink** [comment]
That looks nice. Definitely a useful feature.

**Comment by manuq** [comment]
Closing this because #311  was merged.
