### ISSUE TITLE
Hub.docker.com integration

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppetboard#312]
Adding hooks to build docker images ever push or tag should create a new container. 

Something like this 

![img_1023](https://cloud.githubusercontent.com/assets/360013/19737173/64954a62-9b80-11e6-916b-cdbfb5db669b.PNG)

**Comment by nibalizer** [comment]
What is this a request for?

**Comment by mterzo** [comment]
This is to allow CD of docker images on ever check into master a docker container will be created by hub.docker and tagged latest.  When tags are added to the repo those tags will build a container and tagged at that release.

This is to allow docker deployments form #310 and #288.

**Comment by bbriggs** [comment]
talked with @mterzo about this in IRC today. Once we get #288 and/or #310 merged, I'll set up CD to deploy a new image on successful tagged builds on master.

**Comment by bbriggs** [comment]
We need to get @mterzo and @tux-o-matic to work out and agree to the scopes of their respective PRs, though.

**Comment by mterzo** [comment]
@bbriggs II tagged @tux-o-matic on my recent changes of my PR.  My PR was based off his.  I wanted to cherry-pick some of his commits but when I ended up rebasing I was going to loose them all.  He pointed me at the gunicorn setup which is awesome.

**Comment by mterzo** [comment]
#310 just need to enable the building hooks.

**Comment by bbriggs** [comment]
ack

**Comment by mterzo** [comment]
I've enabled This off my hub account for now.  I'm going to update the docs pointing to this repo.
