### ISSUE TITLE
Unknown OpenSSL error

### ISSUE THREAD

**Issue by nfeutry** [voxpupuli/puppetboard#313]
I'm trying to install puppetboard and I always get an `InternalError: Unknown OpenSSL error`

```
mod_wsgi (pid=3677): Target WSGI script '/var/www/localhost/htdocs/puppetboard/wsgi.py' cannot be loaded as Python module.
 mod_wsgi (pid=3677): Exception occurred processing WSGI script '/var/www/localhost/htdocs/puppetboard/wsgi.py'.
 Traceback (most recent call last):
   File "/var/www/localhost/htdocs/puppetboard/wsgi.py", line 6, in <module>
     from puppetboard.app import app as application
   File "/usr/lib64/python2.7/site-packages/puppetboard/app.py", line 19, in <module>
     from pypuppetdb import connect
   File "/usr/lib64/python2.7/site-packages/pypuppetdb/__init__.py", line 61, in <module>
     from pypuppetdb.api import BaseAPI
   File "/usr/lib64/python2.7/site-packages/pypuppetdb/api.py", line 6, in <module>
     import requests
   File "/usr/lib64/python2.7/site-packages/requests/__init__.py", line 53, in <module>
     from .packages.urllib3.contrib import pyopenssl
   File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
     import OpenSSL.SSL
   File "/usr/lib64/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
     from OpenSSL import rand, crypto, SSL
   File "/usr/lib64/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
     from OpenSSL._util import (
   File "/usr/lib64/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
     from cryptography.hazmat.bindings.openssl.binding import Binding
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 225, in <module>
     Binding.init_static_locks()
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 181, in init_static_locks
     cls._ensure_ffi_initialized()
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 176, in _ensure_ffi_initialized
     cls._register_osrandom_engine()
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 141, in _register_osrandom_engine
     _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 63, in _openssl_assert
     errors_with_text
 InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line'), _OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line')
```

How can I find what is causing this issue ?

Apache/2.2.31
OpenSSL/1.0.2j
mod_wsgi/4.4.21
Python/2.7.10
puppetdb/4.0.2
puppetboard/0.2.0

**Comment by mterzo** [comment]
What version of: urllib3.  your OpenSSL maybe updated but your python library was linked to what used to be installed.

**Comment by nfeutry** [comment]
urllib3 is 1.12 
request version is 2.8.1 and pyopenssl is 16.2.0

**Comment by mterzo** [comment]
Can you look at this article and see if it helps. 

http://raspberrypi.stackexchange.com/questions/28176/python-and-openssl-error-on-import

**Comment by mterzo** [comment]
Any update on this, @nfeutry?  I really think something is wrong with your ssl libs and python.

**Comment by nfeutry** [comment]
Yes, I tried a few thing suggested in the link. Mostly uninstall/reinstall libs with/without pip. 
It did not fix the error but when I refresh 5 or 6 six time in a row, it starts working for a few minutes and break randomly after (don't know if it was the case before, I may not have tried hard enough).

I will try on a fresh install to see if it change something.

**Comment by mterzo** [comment]
The last line of that trace is interesting. 


 InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line'), _OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line')

**Comment by nfeutry** [comment]
Yes, but I don't know wich `other library is not cleaning up the OpenSSL error stack` or how to find out. 
I have also checked all pem on the server and found none with `no start line`. 

And I don't understand how it can work sometimes but never on the first try.

**Comment by mterzo** [comment]
Very odd. Do you mind sharing your mod wsgi and settings.py?

Also how is your puppetdb DNS/load balancer. configured. Wondering if you have something causing a round robin on puppetboard trying to connect to the API.

**Comment by mterzo** [comment]
I found this as well. 

https://github.com/pyca/cryptography/issues/3275

**Comment by nfeutry** [comment]
Here is my wsgi.py: 
```from __future__ import absolute_import
import os

# Needed if a settings.py file exists
os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/localhost/htdocs/puppetboard/settings.py'
from puppetboard.app import app as application
application.secret_key = '1gf5s2yJ6sFcvY28D4mGt2hF'
```
and settings.py : 
```PUPPETDB_HOST = 'localhost'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = None
PUPPETDB_CERT = None
PUPPETDB_TIMEOUT = 20
DEFAULT_ENVIRONMENT = 'production'
DEV_LISTEN_HOST = '0.0.0.0'
DEV_LISTEN_PORT = 5000
UNRESPONSIVE_HOURS = 2
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
LOGLEVEL = 'debug'
REPORTS_COUNT = 10
OFFLINE_MODE = False
ENABLE_CATALOG = False
```

But whatever I put in the settings, the behaviour does not change. If I mess with the settings file , I can have the `Unknown SSL error` before the `Syntax Error` happen.
There is no loadbalancing/roundrobin in my installation, everything run on the same server. But yes It really looks like that.

**Comment by mterzo** [comment]
Your not even using SSL to talk to puppetdb.  This looks to be something going on with your system and it's python libraries.  https://github.com/pyca/cryptography/issues/2699

Do you have m2crypto installed?  Which distro is this?

**Comment by nfeutry** [comment]
m2crypto is not installed. The only *ssl* or *crypt* lib installed was pycrypto and I removed without any change.

I'm using gentoo.

**Comment by mterzo** [comment]
@nfeutry, I'm not sure how to fix your issue.  It looks to be a messed up crypto problem on gentoo and python.

**Comment by nfeutry** [comment]
Good news, I have successfully installed a functional puppetboard based on the puppet module. 
Bad news, I still don't known why my manual installations all failed with the same error. 

I have absolutely no clue where this comes from. It does not seems to be related with puppetboard, I guess we can close this issue.

Thanks for your time and all the leads you shared!
