### ISSUE TITLE
Overview is empty everything else seems to work fine

### ISSUE THREAD

**Issue by edikmkoyan** [voxpupuli/puppetboard#315]
Not Found

What you were looking for could not be found in PuppetDB

```
[puppet]~> dpkg -l | grep puppet
ii  puppet-agent                       1.8.0-1trusty                     amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppetdb                           4.3.0-1puppetlabs1                all          Puppet Labs puppetdb
ii  puppetdb-termini                   4.3.0-1puppetlabs1                all          Termini for puppetdb
ii  puppetlabs-release                 1.1-1                             all          "Package to install Puppet Labs gpg key and apt repo"
ii  puppetlabs-release-pc1             1.1.0-4trusty                     all          Release packages for the Puppet Labs PC1 repository
ii  puppetserver                       2.7.0-1puppetlabs1                all          Puppet Labs puppetserver
```

**Comment by corey-hammerton** [comment]
Puppet by default configures the 'production' environment in `puppet.conf`, what is `DEFAULT_ENVIRONMENT` puppetboard setting configured to and what is the `environment` setting in puppet.conf?

**Comment by edikmkoyan** [comment]
@corey-hammerton 
[puppet]/etc/puppetlabs/puppet> vim puppet.conf

## puppetserver main config file 
[master]
vardir = /opt/puppetlabs/server/data/puppetserver
logdir = /var/log/puppetlabs/puppetserver
rundir = /var/run/puppetlabs/puppetserver
pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
codedir = /etc/puppetlabs/code
storeconfigs = true
storeconfigs_backend = puppetdb
## change server/node name for your enviroment
[main]
certname = puppet.example.lab
server = puppet.example.lab
environment = production
runinterval = 30m
report = true
reports = puppetdb
-----------------------------------------------

[puppet]/etc/puppetlabs/puppet> vim /var/www/puppetboard/settings.py 

import os

PUPPETDB_HOST = 'localhost'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = True
PUPPETDB_KEY = None
PUPPETDB_CERT = None
PUPPETDB_TIMEOUT = 20
SECRET_KEY = os.urandom(24)
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
DEV_COFFEE_LOCATION = 'coffee'
UNRESPONSIVE_HOURS = 2
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
LOGLEVEL = 'info'
REPORTS_COUNT = 10
OFFLINE_MODE = False
ENABLE_CATALOG = True
GRAPH_FACTS = ['architecture',
               'domain',
               'lsbcodename',
               'lsbdistcodename',
               'lsbdistid',
               'lsbdistrelease',
               'lsbmajdistrelease',
               'netmask',
               'osfamily',
               'puppetversion',
               'processorcount']
INVENTORY_FACTS = [ ('Hostname',       'fqdn'              ),
                    ('IP Address',     'ipaddress'         ),
                    ('OS',             'lsbdistdescription'),
                    ('Architecture',   'hardwaremodel'     ),
                    ('Kernel Version', 'kernelrelease'     ),
                    ('Puppet Version', 'puppetversion'     ), ]

**Comment by corey-hammerton** [comment]
Which version of Puppetboard are you running?

**Comment by edikmkoyan** [comment]
@corey-hammerton 0.1.0

**Comment by corey-hammerton** [comment]
The issue is that PuppetBoard 0.1.x only supports PuppetDB 3.x. Please upgrade your PuppetBoard instance(s) to the latest 0.2.x series, this will resolve your issue.
