### ISSUE TITLE
Problem generating secret_key

### ISSUE THREAD

**Issue by ksemaev** [voxpupuli/puppetboard#317]
May be I,m doing smth wrong, but on Ubuntu 14.04.5 LTS the script
"import os
print os.random(24)"

gives that output:
"Traceback (most recent call last):
  File "test", line 3, in <module>
    print os.random(24)
AttributeError: 'module' object has no attribute 'random'"

Please advice)

**Comment by mterzo** [comment]
Did you put quotes around the text in an editor?

**Comment by mterzo** [comment]
Oh. See me #309. 

print os.urandom(24)

**Comment by ksemaev** [comment]
Thank you!

**Comment by ksemaev** [comment]
Do i need to put into script some translation to HEX or smth? Because it gives strange symbols on output. like: Y▒▒▒E}▒▒|▒"▒ƥa-D#▒

**Comment by mterzo** [comment]
That's your term type.

If you want printable characters you can follow:

http://stackoverflow.com/questions/7479442/high-quality-simple-random-password-generator

**Comment by ksemaev** [comment]
sorry for beeing stupied but your readme says "Copy the output and add the following to your wsgi.py". So I should make the characters printable first as you recommended with last link?
