### ISSUE TITLE
Node OS name only correct on Linux

### ISSUE THREAD

**Issue by jordigg** [voxpupuli/puppetboard#339]
On the Inventory tab, OS attribute is set as `undef` for Windows and Mac. For Linux it's shown correctly.
The node facts are correct and show Windows and Mac together with their release versions.

**Comment by corey-hammerton** [comment]
Compare the fact name in `default_settings.py` and/or your `settings.py` and find a consistent fact name to configure. in `INVENTORY_FACTS`

**Comment by jordigg** [comment]
Oh I see now, thanks @corey-hammerton though was pointing to a specific fact that was "universal" on all platforms.
Will create a custom one myself and use it on the `INVENTORY_FACTS` to list it on the inventory.
Thanks and sorry for opening this issue!
