### ISSUE TITLE
Breadcrumb UI overlap on node.

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppetboard#340]
Paging for reports now overlaps one node.

<img width="300" alt="breadcrumb_too_wide" src="https://cloud.githubusercontent.com/assets/360013/22429173/b731db8a-e6d7-11e6-83cd-97301f760aa2.png">
<img width="300" alt="breadcrumb_overlap" src="https://cloud.githubusercontent.com/assets/360013/22429174/b73fa2b0-e6d7-11e6-9d3f-cb9616f25f64.png">

**Comment by mterzo** [comment]
@redref Have you seen this?

**Comment by redref** [comment]
@mterzo nope. Reports page is also impacted on (tiny) mobile devices.

May not be easy to fix. Found the same issue on datatables example : https://datatables.net/examples/styling/semanticui.html

**Comment by mterzo** [comment]
I removed the pages in the crumbs, so it's only [Previous][Next] buttons, that folds better.

**Comment by redref** [comment]
For the record, removing "column" class in either elements solve our problem.

But this is wrapped in datatables.semantic.js code.

**Comment by mterzo** [comment]
In the JS call you can specify the class to be used, i'll see if that helps.

**Comment by mterzo** [comment]
Nope, doesn't look like I can't change the class though options to datable.  I'm gonna leave it by only setting the page options to simple.

**Comment by mterzo** [comment]
@redref Can you look at the changes I made in #341.
