### ISSUE TITLE
flask incompatability ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppetboard#370]
Just trying to install puppetboard on centos 7 - and after puppet has run pip install -r requirements.txt.. when I run puppetboard we get:
[Tue Mar 14 17:36:13.718032 2017] [:error] [pid 29154] /srv/puppetboard/puppetboard/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Tue Mar 14 17:36:13.718097 2017] [:error] [pid 29154]   from flask.ext.wtf import Form
[Tue Mar 14 17:36:13.746226 2017] [:error] [pid 29154] /srv/puppetboard/puppetboard/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Tue Mar 14 17:36:13.746252 2017] [:error] [pid 29154]   class QueryForm(Form):
[Tue Mar 14 17:36:13.746313 2017] [:error] [pid 29154] /srv/puppetboard/puppetboard/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Tue Mar 14 17:36:13.746319 2017] [:error] [pid 29154]   class CatalogForm(Form):
[Tue Mar 14 17:36:13.750260 2017] [:error] [pid 29154] [remote 10.47.45.131:224] mod_wsgi (pid=29154): Target WSGI script '/srv/puppetboard/puppetboard/wsgi.py' cannot be loaded as Python module.
[Tue Mar 14 17:36:13.750285 2017] [:error] [pid 29154] [remote 10.47.45.131:224] mod_wsgi (pid=29154): Exception occurred processing WSGI script '/srv/puppetboard/puppetboard/wsgi.py'.
[Tue Mar 14 17:36:13.750308 2017] [:error] [pid 29154] [remote 10.47.45.131:224] Traceback (most recent call last):
[Tue Mar 14 17:36:13.750326 2017] [:error] [pid 29154] [remote 10.47.45.131:224]   File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
[Tue Mar 14 17:36:13.750379 2017] [:error] [pid 29154] [remote 10.47.45.131:224]     from puppetboard.app import app as application
[Tue Mar 14 17:36:13.750390 2017] [:error] [pid 29154] [remote 10.47.45.131:224]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 106, in <module>
[Tue Mar 14 17:36:13.750584 2017] [:error] [pid 29154] [remote 10.47.45.131:224]     abort.mapping[204] = NoContent
[Tue Mar 14 17:36:13.750605 2017] [:error] [pid 29154] [remote 10.47.45.131:224] AttributeError: 'function' object has no attribute 'mapping'
[Tue Mar 14 17:36:14.006092 2017] [:error] [pid 29154] [remote 10.47.45.131:208] mod_wsgi (pid=29154): Target WSGI script '/srv/puppetboard/puppetboard/wsgi.py' cannot be loaded as Python module.
[Tue Mar 14 17:36:14.006130 2017] [:error] [pid 29154] [remote 10.47.45.131:208] mod_wsgi (pid=29154): Exception occurred processing WSGI script '/srv/puppetboard/puppetboard/wsgi.py'.
[Tue Mar 14 17:36:14.006151 2017] [:error] [pid 29154] [remote 10.47.45.131:208] Traceback (most recent call last):
[Tue Mar 14 17:36:14.006181 2017] [:error] [pid 29154] [remote 10.47.45.131:208]   File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
[Tue Mar 14 17:36:14.006214 2017] [:error] [pid 29154] [remote 10.47.45.131:208]     from puppetboard.app import app as application
[Tue Mar 14 17:36:14.006223 2017] [:error] [pid 29154] [remote 10.47.45.131:208]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 106, in <module>
[Tue Mar 14 17:36:14.006252 2017] [:error] [pid 29154] [remote 10.47.45.131:208]     abort.mapping[204] = NoContent
[Tue Mar 14 17:36:14.006268 2017] [:error] [pid 29154] [remote 10.47.45.131:208] AttributeError: 'function' object has no attribute 'mapping'
[Tue Mar 14 17:36:14.074832 2017] [:error] [pid 29154] [remote 10.47.45.131:55264] mod_wsgi (pid=29154): Target WSGI script '/srv/puppetboard/puppetboard/wsgi.py' cannot be loaded as Python module.
[Tue Mar 14 17:36:14.074865 2017] [:error] [pid 29154] [remote 10.47.45.131:55264] mod_wsgi (pid=29154): Exception occurred processing WSGI script '/srv/puppetboard/puppetboard/wsgi.py'.
[Tue Mar 14 17:36:14.074886 2017] [:error] [pid 29154] [remote 10.47.45.131:55264] Traceback (most recent call last):
[Tue Mar 14 17:36:14.074904 2017] [:error] [pid 29154] [remote 10.47.45.131:55264]   File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
[Tue Mar 14 17:36:14.074944 2017] [:error] [pid 29154] [remote 10.47.45.131:55264]     from puppetboard.app import app as application
[Tue Mar 14 17:36:14.074954 2017] [:error] [pid 29154] [remote 10.47.45.131:55264]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 106, in <module>
[Tue Mar 14 17:36:14.074967 2017] [:error] [pid 29154] [remote 10.47.45.131:55264]     abort.mapping[204] = NoContent
[Tue Mar 14 17:36:14.074982 2017] [:error] [pid 29154] [remote 10.47.45.131:55264] AttributeError: 'function' object has no attribute 'mapping'

which seems as if we have gotten "too new" upstream python modules or something, so its incompatible ?
Using puppetboard 2.9.0

**Comment by m4ce** [comment]
Same issue here.

**Comment by KlavsKlavsen** [comment]
I assume a download of flask to a previous major version would resolve the issue.. I haven't tested that idea though.

**Comment by m4ce** [comment]
Doubt that is Flask as I tried rolling back to 0.11.1 and 0.10.1 without success.

**Comment by m4ce** [comment]
Rolled back to puppetboard 0.2.0 and issue is gone

**Comment by TomaszUrugOlszewski** [comment]
Same on Debian Jessie and puppetboard installed with simple `pip install puppetboard`

**Comment by tparkercbn** [comment]
I have the same issue on some Jessie nodes and not others.  All with puppetboard 0.2.1 installed via pip install --upgrade puppetboard.  So far I have not been able to isolate any differences in puppetboard dependencies or python library versions.

**Comment by tparkercbn** [comment]
Working node: 
[QA] surclients:~ # pip list --format=columns
Package          Version 
---------------- --------
cffi             0.8.6   
chardet          2.3.0   
click            6.7     
colorama         0.3.2   
cryptography     0.6.1   
defusedxml       0.4.1   
docutils         0.12    
Flask            0.12    
Flask-WTF        0.13    
html5lib         0.999   
itsdangerous     0.24    
Jinja2           2.9.5   
MarkupSafe       0.23    
ndg-httpsclient  0.3.2   
Pillow           2.6.1   
pip              9.0.1   
ply              3.4     
puppetboard      0.2.1   
pyasn1           0.1.7   
pycparser        2.10    
Pygments         2.0.1   
pyOpenSSL        0.14    
pypuppetdb       0.3.2   
python-apt       0.9.3.12
python-debian    0.1.27  
python-debianbts 1.11    
reportbug        6.6.3   
requests         2.13.0  
roman            2.0.0   
setuptools       5.5.1   
six              1.8.0   
SOAPpy           0.12.22 
urllib3          1.9.1   
Werkzeug         0.11.15 
wheel            0.24.0  
wstools          0.4.3   
WTForms          2.1 

Not working node:
[QA] domclients:~ # pip list --format=columns
Package          Version 
---------------- --------
cffi             0.8.6   
chardet          2.3.0   
click            6.7     
colorama         0.3.2   
cryptography     0.6.1   
defusedxml       0.4.1   
docutils         0.12    
Flask            0.12    
Flask-WTF        0.13    
html5lib         0.999   
itsdangerous     0.24    
Jinja2           2.9.5   
MarkupSafe       1.0     
ndg-httpsclient  0.3.2   
Pillow           2.6.1   
pip              9.0.1   
ply              3.4     
puppetboard      0.2.1   
pyasn1           0.1.7   
pycparser        2.10    
Pygments         2.0.1   
pyOpenSSL        0.14    
pypuppetdb       0.3.2   
python-apt       0.9.3.12
python-debian    0.1.27  
python-debianbts 1.11    
reportbug        6.6.3   
requests         2.13.0  
roman            2.0.0   
setuptools       5.5.1   
six              1.8.0   
SOAPpy           0.12.22 
urllib3          1.9.1   
Werkzeug         0.12.1  
wheel            0.24.0  
wstools          0.4.3   
WTForms          2.1

**Comment by tparkercbn** [comment]
The culprit for me is: Werkzeug

[QA] domclients:~ # pip install Werkzeug==0.11.15
Collecting Werkzeug==0.11.15
  Using cached Werkzeug-0.11.15-py2.py3-none-any.whl
Installing collected packages: Werkzeug
  Found existing installation: Werkzeug 0.12.1
    Uninstalling Werkzeug-0.12.1:
      Successfully uninstalled Werkzeug-0.12.1
Successfully installed Werkzeug-0.11.15
[QA] domclients:~ # systemctl restart apache2

System is working:

[QA] domclients:~ # pip install --upgrade Werkzeug
Collecting Werkzeug
  Using cached Werkzeug-0.12.1-py2.py3-none-any.whl
Installing collected packages: Werkzeug
  Found existing installation: Werkzeug 0.11.15
    Uninstalling Werkzeug-0.11.15:
      Successfully uninstalled Werkzeug-0.11.15
Successfully installed Werkzeug-0.12.1
[QA] domclients:~ # systemctl restart apache2

System is now broken.

Reverting to 0.11.15 and everything is happy again.

**Comment by purplesrl** [comment]
seems the same bug as the open I reported #372 

the solution for me was to comment that line, all seems to work fine after that

**Comment by mterzo** [comment]
Updated.
