### ISSUE TITLE
centos 6 WSGI script 'wsgi.py' cannot be loaded as Python module

### ISSUE THREAD

**Issue by mmgit1** [voxpupuli/puppetboard#371]
Hello,

I've very intersted in using the puppetboard app.  I'm running puppetdb 4.3.  Below is what I'm running on for server/python/httpd/mod_wsgi versions.

CentOS 6.8
python 2.6.6
httpd-2.2.15-56.el6.centos.3.x86_64
httpd-devel-2.2.15-56.el6.centos.3.x86_64
mod_wsgi-3.2-7.el6.x86_64

When I try to hit http://localhost for puppetboard I get internal server error and a bunch of errors in the log.  See below for the details for settings and log files.  Puppetboard is installed on the same server as puppetdb.  Any help would be appreciated.

Thanks,
Mike

I ran pip install puppetboard

Location of puppetboard pip install: 
/usr/lib/python2.6/site-packages/puppetboard/

The /var/www/html/puppetboard/settings.py has this below.

import os

PUPPETDB_HOST = '192.168.2.230'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = True
PUPPETDB_KEY = '/etc/puppetlabs/puppetdb/ssl/private.pem'
PUPPETDB_CERT = '/etc/puppetlabs/puppetdb/ssl/public.pem'
PUPPETDB_TIMEOUT = 20
DEFAULT_ENVIRONMENT = 'production'
SECRET_KEY = os.urandom(24)
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
DEV_COFFEE_LOCATION = 'coffee'
UNRESPONSIVE_HOURS = 2
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
LOGLEVEL = 'info'
NORMAL_TABLE_COUNT = 100
LITTLE_TABLE_COUNT = 10
TABLE_COUNT_SELECTOR = [10, 20, 50, 100, 500]
OFFLINE_MODE = False
ENABLE_CATALOG = False
OVERVIEW_FILTER = None
GRAPH_TYPE = 'pie'
GRAPH_FACTS = ['architecture',
               'clientversion',
               'domain',
               'lsbcodename',
               'lsbdistcodename',
               'lsbdistid',
               'lsbdistrelease',
               'lsbmajdistrelease',
               'netmask',
               'osfamily',
               'puppetversion',
               'processorcount']
INVENTORY_FACTS = [('Hostname', 'fqdn'),
                   ('IP Address', 'ipaddress'),
                   ('OS', 'lsbdistdescription'),
                   ('Architecture', 'hardwaremodel'),
                   ('Kernel Version', 'kernelrelease'),
                   ('Puppet Version', 'puppetversion'), ]
REFRESH_RATE = 30
DAILY_REPORTS_CHART_ENABLED = True
DAILY_REPORTS_CHART_DAYS = 8

The /var/www/html/puppetboard/wsgi.py file has this below.

from __future__ import absolute_import
import os

# Needed if a settings.py file exists
os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/html/puppetboard/settings.py'
from puppetboard.app import app as application

The /etc/httpd/conf/httpd.conf has this in it

<VirtualHost *:80>
    ServerName localhost
    WSGIDaemonProcess puppetboard user=apache group=apache threads=5
    WSGIScriptAlias / /var/www/html/puppetboard/wsgi.py
    ErrorLog logs/puppetboard-error_log
    CustomLog logs/puppetboard-access_log combined

    Alias /static /usr/lib/python2.6/site-packages/puppetboard/static
    <Directory /usr/lib/python2.6/site-packages/puppetboard/static>
        Satisfy Any
        Allow from all
    </Directory>

    <Directory /usr/lib/python2.6/site-packages/puppetboard>
        WSGIProcessGroup puppetboard
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
</VirtualHost>

When I try to hit the app using http://localhost I get internal server.  Below is the /var/log/httpd/puppetboard-error_log.

[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12926): Target WSGI script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12926): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5] Traceback (most recent call last):
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5]   File "/var/www/html/puppetboard/wsgi.py", line 6, in <module>
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5]     from puppetboard.app import app as application
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 117, in <module>
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5]     abort.mapping[204] = NoContent
[Fri Mar 17 08:15:50 2017] [error] [client 192.168.2.5] AttributeError: 'function' object has no attribute 'mapping'
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12924): Target WSGI script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12924): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] Traceback (most recent call last):
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]   File "/var/www/html/puppetboard/wsgi.py", line 6, in <module>
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]     from puppetboard.app import app as application
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 117, in <module>
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]     abort.mapping[204] = NoContent
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] AttributeError: 'function' object has no attribute 'mapping'
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12922): Target WSGI script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] mod_wsgi (pid=12922): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] Traceback (most recent call last):
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]   File "/var/www/html/puppetboard/wsgi.py", line 6, in <module>
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]     from puppetboard.app import app as application
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 117, in <module>
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5]     abort.mapping[204] = NoContent
[Fri Mar 17 08:15:51 2017] [error] [client 192.168.2.5] AttributeError: 'function' object has no attribute 'mapping'

Below is the /var/log/httpd/error_log.

[Fri Mar 17 08:15:43 2017] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Mar 17 08:15:43 2017] [notice] Digest: generating secret for digest authentication ...
[Fri Mar 17 08:15:43 2017] [notice] Digest: done
[Fri Mar 17 08:15:43 2017] [notice] Apache/2.2.15 (Unix) DAV/2 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips mod_wsgi/3.2 Python/2.6.6 configured -- resuming normal operations
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Fri Mar 17 08:15:50 2017] [error]   from flask.ext.wtf import Form
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Fri Mar 17 08:15:50 2017] [error]   message='A query is required.')])
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:50 2017] [error]   class QueryForm(Form):
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:50 2017] [error]   class CatalogForm(Form):
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Fri Mar 17 08:15:50 2017] [error]   from flask.ext.wtf import Form
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Fri Mar 17 08:15:50 2017] [error]   message='A query is required.')])
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:50 2017] [error]   class QueryForm(Form):
[Fri Mar 17 08:15:50 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:50 2017] [error]   class CatalogForm(Form):
[Fri Mar 17 08:15:51 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Fri Mar 17 08:15:51 2017] [error]   from flask.ext.wtf import Form
[Fri Mar 17 08:15:51 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Fri Mar 17 08:15:51 2017] [error]   message='A query is required.')])
[Fri Mar 17 08:15:51 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:51 2017] [error]   class QueryForm(Form):
[Fri Mar 17 08:15:51 2017] [error] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 08:15:51 2017] [error]   class CatalogForm(Form):

permissions (httpd runs as apache:apache user:group):
directory: /var/www/html/
drwxr-xr-x 2 apache apache 4096 Mar 17 08:19 puppetboard

directory:/var/www/html/puppetboard/
-rw-r--r-- 1 apache apache 1399 Mar 17 08:11 settings.py
-rwxrwxrwx 1 apache apache  212 Mar 17 08:11 wsgi.py

**Comment by mmgit1** [comment]
UPDATE.  I got the wsg.pyi to load.  I'm running puppetboard 0.2.1 version.  What I did to get this to load was...

Added this below to the top of the /var/www/html/puppetboard/wsgi.py file:
#!/usr/bin/env python

Added these items to /etc/httpd/conf/httpd.conf:
Options ExecCGI Indexes FollowSymLinks
AddHandler cgi-script .cgi .py

The /var/log/httpd/error_log shows this now.
[Fri Mar 17 20:01:06 2017] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Mar 17 20:01:06 2017] [notice] Digest: generating secret for digest authentication ...
[Fri Mar 17 20:01:06 2017] [notice] Digest: done
[Fri Mar 17 20:01:06 2017] [notice] Apache/2.2.15 (Unix) DAV/2 mod_wsgi/3.2 Python/2.6.6 configured -- resuming normal operations

However, the new error in the /var/log/httpd/puppetboard-error_log shows this:

[Fri Mar 17 20:02:06 2017] [error] [client 192.168.2.5] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Fri Mar 17 20:02:06 2017] [error] [client 192.168.2.5]   from flask.ext.wtf import Form
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]   message='A query is required.')])
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5 /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]   class QueryForm(Form):
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]   class CatalogForm(Form):
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5] Traceback (most recent call last):
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]   File "/var/www/html/puppetboard/wsgi.py", line 7, in <module>
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]     from puppetboard.app import app as application
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 117, in <module>
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5]     abort.mapping[204] = NoContent
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5] AttributeError: 'function' object has no attribute 'mapping'
[Fri Mar 17 20:02:07 2017] [error] [client 192.168.2.5] Premature end of script headers: wsgi.py



Any ideas on this Premature end of script headers error?   The /var/www/html/puppetboard/wsgi.py script looks like this.

#!/usr/bin/env python
from __future__ import absolute_import
import os

# Needed if a settings.py file exists
os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/html/puppetboard/settings.py'
from puppetboard.app import app as application

**Comment by f951753** [comment]
Hi,

I have exactly the same problem with 0.3.0dev version installed with puppet-puppetboard puppet module.
I found a workaround that is, you need to modify the puppetboard/app.py on line 130 (for my version, seems line 117 on yours) and comment this line:
#abort.mapping[204] = NoContent

Now puppetboard work nicely but i don't see any reports in the report tab...

NB: You could check my puppetdbquery script, it's a command line puppetboard and can be usefull for you.

**Comment by f951753** [comment]
Forget my workaround, see issue : "flask incompatability ?" and the last comment of tparkercbn about the last Werkzeug version which broke puppetboard...

**Comment by mmgit1** [comment]
@f951753   Thank you for the suggestion.   I did comment out the line 117.  Now I'm getting the premature end of script headers below, which I assume is due to the Werkzeug issue you mentioned.


[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1]   from flask.ext.wtf import Form
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1]   message='A query is required.')])
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1]   class QueryForm(Form):
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1]   class CatalogForm(Form):
[Sun Mar 19 23:33:06 2017] [error] [client 33.33.33.1] Premature end of script headers: wsgi.py
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead., referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1]   from flask.ext.wtf import Form, referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired, referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1]   message='A query is required.')]), referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0., referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1]   class QueryForm(Form):, referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0., referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1]   class CatalogForm(Form):, referer: http://localhost/
[Sun Mar 19 23:33:08 2017] [error] [client 33.33.33.1] Premature end of script headers: wsgi.py, referer: http://localhost/
[Sun Mar 19 23:36:11 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Sun Mar 19 23:36:11 2017] [error] [client 33.33.33.1]   from flask.ext.wtf import Form
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1]   message='A query is required.')])
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1]   class QueryForm(Form):
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1]   class CatalogForm(Form):
[Sun Mar 19 23:36:12 2017] [error] [client 33.33.33.1] Premature end of script headers: wsgi.py

**Comment by mterzo** [comment]
pip install puppetboard==0.2.2

Will solve this problem.

**Comment by mmgit1** [comment]
Ran pip install puppetboard==0.2.2 and restarted web server.  Still get the premature end of script error below.

Mike


[Mon Mar 20 22:15:06 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Mon Mar 20 22:15:06 2017] [error] [client 33.33.33.1]   from flask.ext.wtf import Form
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1]   message='A query is required.')])
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1]   class QueryForm(Form):
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1]   class CatalogForm(Form):
[Mon Mar 20 22:15:07 2017] [error] [client 33.33.33.1] Premature end of script headers: wsgi.py

**Comment by mterzo** [comment]
Odd the warning shouldn't be exiting the code. Need to understand why this is occurring.

**Comment by mterzo** [comment]
So, I've created a couple of vagrant environments to test with.  I'm not sure If i want to push them to the main repo yet.

https://github.com/mterzo/puppetboard/tree/vagrant

I've also mixed it up, I'm not able to reproduce your problem.  I see a warning:

```
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/puppetboard/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Thu Mar 23 20:06:59 2017] [error]   from flask.ext.wtf import Form
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/puppetboard/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Thu Mar 23 20:06:59 2017] [error]   message='A query is required.')])
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/puppetboard/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Mar 23 20:06:59 2017] [error]   class QueryForm(Form):
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/puppetboard/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Mar 23 20:06:59 2017] [error]   class CatalogForm(Form):
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/virtenv-puppetboard/lib/python2.6/site-packages/requests/auth.py:45: DeprecationWarning: Non-string usernames will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (None) to a string or bytes object in the near future to avoid problems.
[Thu Mar 23 20:06:59 2017] [error]   category=DeprecationWarning,
[Thu Mar 23 20:06:59 2017] [error] /srv/puppetboard/virtenv-puppetboard/lib/python2.6/site-packages/requests/auth.py:55: DeprecationWarning: Non-string passwords will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (None) to a string or bytes object in the near future to avoid problems.
[Thu Mar 23 20:06:59 2017] [error]   category=DeprecationWarning,
```

Which will not cause premature header issues on wsgi.py

My WSGI looks like:

```
from __future__ import absolute_import

import os
import sys

os.environ['PUPPETBOARD_SETTINGS'] = '/srv/puppetboard/puppetboard/settings.py'
activate_this = '/srv/puppetboard/virtenv-puppetboard/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

me = os.path.dirname(os.path.abspath(__file__))
# Add us to the PYTHONPATH/sys.path if we're not on it
if not me in sys.path:
    sys.path.insert(0, me)

from puppetboard.app import app as application
```

**Comment by mterzo** [comment]
Also, 8081 is' puppetdb's SSL port unless you changed it.

**Comment by mterzo** [comment]
Looking at this, I think you are most likely running puppetboard on the puppetdb host.  If that's the case you can use '127.0.0.1' and 8080 without SSL 

```
PUPPETDB_HOST = '192.168.2.230'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = True
PUPPETDB_KEY = '/etc/puppetlabs/puppetdb/ssl/private.pem'
PUPPETDB_CERT = '/etc/puppetlabs/puppetdb/ssl/public.pem'
```

**Comment by mmgit1** [comment]
Yeah, I changed the port to 8081 with the SSL.   The puppetboard is running on the same host as the puppetdb.  I'm using vagrant for my test as well for this.  So I tried changing the settings.py to this below.

PUPPETDB_HOST = '127.0.0.1'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False

Restarted httpd and got this in the puppetboard-error_log file.

cat puppetboard-error_log
[Thu Mar 23 21:57:18 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Thu Mar 23 21:57:18 2017] [error] [client 33.33.33.1]   from flask.ext.wtf import Form
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:15: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1]   message='A query is required.')])
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1]   class QueryForm(Form):
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1] /usr/lib/python2.6/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1]   class CatalogForm(Form):
[Thu Mar 23 21:57:19 2017] [error] [client 33.33.33.1] Premature end of script headers: wsgi.py

**Comment by mterzo** [comment]
Post your wsgi I think there is something wrong with it. You should use puppet-puppet module.

**Comment by mmgit1** [comment]
Here you go.   Below are the permissions on the file.
[wsgi.txt](https://github.com/voxpupuli/puppetboard/files/866365/wsgi.txt)

-rwxr-xr-x 1 apache apache 234 Mar 20 22:11 /var/www/html/puppetboard/wsgi.py

**Comment by mterzo** [comment]
Follow my vagrant example for centos6, since you are using vagrant right now.

I'm uncertain why your having a problem.

**Comment by mmgit1** [comment]
Installed using the puppet module puppetboard and now it works.  I have no idea what I was missing.  Thank you for your time and help on this.  I'm good to go now.
