### ISSUE TITLE
Update supported Python versions? (README)

### ISSUE THREAD

**Issue by bittner** [voxpupuli/puppetboard#382]
The [README states](https://github.com/voxpupuli/puppetboard#puppetboard) that only Python 2.6 and 2.7 are supported, but the [passing tests on Travis CI](https://travis-ci.org/voxpupuli/puppetboard) suggest that also Python 3.5 and 3.6 are supported.

Shall I prepare a PR to update the supported versions in the README? (Or is there a reason why this has not yet been done?)

Maybe related to https://github.com/voxpupuli/puppetboard/issues/361#issuecomment-279673117?

**Comment by mterzo** [comment]
Doesn't work 100% on Python 3

**Comment by mterzo** [comment]
Works in python 3 as of 0.3.0

**Comment by larsnaesbye** [comment]
@bittner I guess this can be closed then?

**Comment by bittner** [comment]
"Computer says, no." --> https://travis-ci.org/voxpupuli/puppetboard
