### ISSUE TITLE
AttributeError when clicking path value on node page

### ISSUE THREAD

**Issue by kirkins** [voxpupuli/puppetboard#385]
I go to my nodes page, click on one of the nodes, scroll down to the value for `path`, and then click on the value.

Which in my case is: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`.

This brings me to a page with the url: 

> http://localhost:5000/%2A/fact/path//usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

This page displays the error:

> AttributeError
> AttributeError: 'NoneType' object has no attribute 'copy'
> 

**Traceback:**

> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
> return self.handle_http_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
> return handler(e)
> File "/var/www/puppetboard/puppetboard/app.py", line 150, in not_found
> return render_template('404.html', envs=envs), 404
> File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
> context, ctx.app)
> File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
> rv = template.render(context)
> File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
> return self.environment.handle_exception(exc_info, True)
> File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/var/www/puppetboard/puppetboard/templates/404.html", line 1, in top-level template code
> {% extends 'layout.html' %}
> File "/var/www/puppetboard/puppetboard/templates/layout.html", line 85, in top-level template code
> <a class="{% if '*' == current_env %}active {% endif %}item" href="{{url_for_field('env', '*')}}">All environments</a>
> File "/var/www/puppetboard/puppetboard/app.py", line 104, in url_for_field
> args = request.view_args.copy()
> AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by tux-o-matic** [comment]
Looks like some Fact require to be escaped or passed as an url param.

**Comment by mterzo** [comment]
Yeah, it's not escaping the forward slashes, but I'm not seeing the result that I would expect, so something is getting translated wrong into the query as well.
