### ISSUE TITLE
Feature request: Simple note function for nodes?

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#390]
When Inventory is used as a server overview, it would be very useful to be able to display/edit a note or some other type of editable text not fetched from facts.

**Comment by mterzo** [comment]
Puppetboard doesn't have a database or anyway of storing data.  Maintaining another database and keeping that database in sync with PuppetDB is out of scope.

If PuppetDB API allowed for adding new data to a node then this would be a viable feature.  Or if there was a service that had a REST API that could allow for notes to be added to a node and it was responsible for keeping those notes in sync with the node, that could also work.

For now this is out of scope of puppet board.

**Comment by larsnaesbye** [comment]
That sounds reasonable, yes. I will probably have to add a custom fact to Facter or similar.

**Comment by mterzo** [comment]
You could stuff it in your hiera data for the node and turn it into a fact.
