### ISSUE TITLE
centos 7  cannot be loaded as Python module

### ISSUE THREAD

**Issue by xjg2010go** [voxpupuli/puppetboard#391]
hi:  
    I have install puppetboard by manual.But when I access puppetboard website,It turn error follow this,
puppetboard version == 0.2.2.2 .How I debug it?where is wrong?

[Thu Jun 22 13:30:36 2017] [info] [client 10.129.148.212] mod_wsgi (pid=84929, process='', application='puppetboard|'): Loading WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Thu Jun 22 13:30:36 2017] [error] [client 10.129.148.212] mod_wsgi (pid=84929): Target WSGI script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
[Thu Jun 22 13:30:36 2017] [error] [client 10.129.148.212] mod_wsgi (pid=84929): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Thu Jun 22 13:30:36 2017] [error] [client 10.129.148.212] mod_wsgi (pid=84929): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.

[root@bizpuppetdb.sogou puppetboard]# cat wsgi.py 
#!/usr/bin/env python
from __future__ import absolute_import
import os
#activate_this = '/data/puppetboard/bin/activate_this.py'
#execfile(activate_this, dict(__file__ = activate_this))

#Needed if a settings.py file exists
#os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/html/puppetboard/settings.py'
from puppetboard.app import app as application
#application.secret_key = '\x03]\x9d\x93G\x90h\xa8<Z\xefo7\xaf\xc50\xca\x80\xc0\x1f\xb8\xec\x14\xd3'

[root@bizpuppetdb.sogou puppetboard]# cat /etc/httpd/conf.d/puppetboard.conf 

#WSGIPythonHome  "/usr/local/python/bin/python"
#WSGIPythonPath  /usr/local/python/lib/python2.7/site-packages
<VirtualHost *:80>
    ServerName puppetboard
    WSGIDaemonProcess puppetboard user=puppet group=puppet threads=5
    #WSGIPythonPath   /var/www/html/puppetboard/ 
    WSGIScriptAlias / /var/www/html/puppetboard/wsgi.py
    ErrorLog logs/puppetboard-error_log
    CustomLog logs/puppetboard-access_log combined
    LogLevel debug
    Alias /static /usr/local/python/lib/python2.7/static
    <Directory /usr/local/python/lib/python2.7/site-packages/puppetboard/static >
        Satisfy Any
        Allow from all
    </Directory>

    <Directory /usr/local/python/lib/python2.7/python2.7/site-packages/puppetboard>
        WSGIProcessGroup puppetboard
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
</VirtualHost>

**Comment by mterzo** [comment]
```
[Thu Jun 22 13:30:36 2017] [error] [client 10.129.148.212] mod_wsgi (pid=84929): Target WSGI \
     script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
```

What's the output of:
`python /var/www/html/puppetboard/wsgi.py`

I'm expecting it's this:

```
Traceback (most recent call last):
  File "wsgi.py", line 2, in <module>
    from future import absolute_import
ImportError: cannot import name absolute_import
```

Your `wsgi.py` should look more like:
```
from __future__ import absolute_import
import os
from puppetboard.app import app as application
```

**Comment by xjg2010go** [comment]
hi:
   thank you for your answer,I follow your advice, It turn this error.
 [root@bizpuppetdb.sogou puppetboard]# python /var/www/html/puppetboard/wsgi.py
/usr/local/python/lib/python2.7/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  from flask.ext.wtf import Form
/usr/local/python/lib/python2.7/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  class QueryForm(Form):
/usr/local/python/lib/python2.7/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  class CatalogForm(Form):

**Comment by mterzo** [comment]
Sure, using `python /var/www/html/puppetboard/wsgi.py` was to help you fix your syntax errors in the wsgi.py.  Those warnings are just warnings, you need to restart your webserver and give it a go.

**Comment by xjg2010go** [comment]
hi:
   I restart httpd server,but the error is exsit. Could you tell me that my apache config is right? 
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Shutdown requested 'puppetboard'.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Stopping process 'puppetboard'.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Destroying interpreters.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Destroying interpreters.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Cleanup interpreter ''.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Cleanup interpreter ''.
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Terminating Python.
'import site' failed; use -v for traceback
[Fri Jun 23 12:54:11 2017] [info] mod_wsgi (pid=34327): Python has shutdown.
[Fri Jun 23 12:54:12 2017] [info] mod_wsgi (pid=41362): Attach interpreter ''.
[Fri Jun 23 12:54:18 2017] [info] [client 10.129.148.212] mod_wsgi (pid=41363, process='', application='puppetboard|'): Loading WSGI script '/var/www/html/puppetboard/wsgi.py'.
[Fri Jun 23 12:54:18 2017] [error] [client 10.129.148.212] mod_wsgi (pid=41363): Target WSGI script '/var/www/html/puppetboard/wsgi.py' cannot be loaded as Python module.
[Fri Jun 23 12:54:18 2017] [error] [client 10.129.148.212] mod_wsgi (pid=41363): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'.


[root@bizpuppetdb.sogou puppetboard]# /etc/init.d/httpd stop
Stopping httpd:                                            [  OK  ]
[root@bizpuppetdb.sogou puppetboard]# /etc/init.d/httpd start
Starting httpd:                                            [  OK  ]


[root@bizpuppetdb.sogou puppetboard]# cat /etc/httpd/conf.d/puppetboard.conf 

WSGIPythonHome  "/usr/local/python/bin/python"
#WSGIPythonPath  /usr/local/python/lib/python2.7/site-packages
<VirtualHost *:80>
    ServerName puppetboard
    WSGIDaemonProcess puppet user=puppet group=puppet threads=5
    #WSGIPythonPath   /var/www/html/puppetboard/ 
    WSGIScriptAlias / /var/www/html/puppetboard/wsgi.py
    ErrorLog logs/puppetboard-error_log
    CustomLog logs/puppetboard-access_log combined
    LogLevel debug
    Alias /static /usr/local/python/lib/python2.7/static
    <Directory /usr/local/python/lib/python2.7/site-packages/puppetboard/static >
        Satisfy Any
        Allow from all
    </Directory>

    <Directory /usr/local/python/lib/python2.7/site-packages/puppetboard>
        WSGIProcessGroup puppet
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
</VirtualHost>
[root@bizpuppetdb.sogou puppetboard]# cat /var/www/html/puppetboard/wsgi.py 
#!/usr/bin/env python
from __future__ import absolute_import
import os
from puppetboard.app import app as application

#Needed if a settings.py file exists
os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/html/puppetboard/settings.py'
#application.secret_key = '\x03]\x9d\x93G\x90h\xa8<Z\xefo7\xaf\xc50\xca\x80\xc0\x1f\xb8\xec\x14\xd3'

**Comment by mterzo** [comment]
Just did a fresh install on centos7 using the puppetboard puppet module.

I'm not sure how you installed everything. Pip/rpm/git.  A lot of things don't look correct.

**Comment by xjg2010go** [comment]
hi:
 thank you for your reply.
 I install puppetboard with pip,Python is a cross-platform application language, do you quote a system special class？ I install pip follow this commands. 
#/usr/local/python/bin/pip install puppetboard
there is no error report when I finish to install puppetboard.

**Comment by xjg2010go** [comment]
hi:
   could you tell me how to debug  pupperboard,I want to find the reason that cause this error.

**Comment by mterzo** [comment]
I'm not sure what that is, sounds like you got some cert issues from your python install.

You never posted your puppet config, so i'm assuming you are using the default config, which assumes your puppetdb server is running on the local host and is listening on 8080.

**Comment by xjg2010go** [comment]
hi:
   I reinstall python and apache ,after that I resolve "cannot be loaded as Python module" error. the reason is that mod_wcgi could load python envionment. I recompile wcgi again with parameter "--with-python=/usr/local/python/bin/python".
  here is my puppet and puppetdb config.
[root@puppetserver.sogou puppet]# cat puppet.conf 
[main]
pluginsync = true
reports = store,puppetdb
storeconfigs = true
storeconfigs_backend = puppetdb

[master]
vardir = /var/lib/puppetlabs/
logdir = /var/log/puppetlabs/
rundir = /var/run/puppetlabs/
codedir = /etc/puppetlabs/code
confdir =  /etc/puppetlabs/puppet 
certname = puppetserver
ca = false
reportdir = /data/puppet/reports
ssl_client_verify_header = SSL_CLIENT_VERIFY
ssl_client_header = SSL_CLIENT_S_DN
environmentpath = $codedir/environments



[agent]
    classfile = $vardir/classes.txt
    localconfig = $vardir/localconfig
    runinterval = 600
    how_diff=true
    report = true
    environment = production
    masterport = 8140
    server = xxxxxxx
    ca_server = xxxxx
[root@puppetserver.sogou puppet]# cat puppetdb.conf 
[main]
server_urls = https://bizpuppetdb.sogou:8081
soft_write_failure = true

[root@puppetserver.sogou puppet]# cat routes.yaml
---
master:
  facts:
    terminus: puppetdb
    cache: yaml

[root@bizpuppetdb.sogou ~]# cat /var/www/puppetboard/mysettings.py
#!/usr/bin/env python
import os

PUPPETDB_HOST = 'bizpuppetdb.sogou'
PUPPETDB_PORT = 8081
PUPPETDB_SSL_VERIFY = '/opt/puppetlabs/puppet/cache/ssl/certs/ca.pem'
PUPPETDB_CERT = '/opt/puppetlabs/puppet/cache/ssl/certs/bizpuppetdb.sogou.pem'
PUPPETDB_KEY = '/opt/puppetlabs/puppet/cache/ssl/private_keys/bizpuppetdb.sogou.pem' 
PUPPETDB_TIMEOUT = 20
DEFAULT_ENVIRONMENT = 'production'

**Comment by mterzo** [comment]
Sounds like your puppetdb cert wasn't signed correctly. Since you are running on the same host you don't need ssl. You can use localhost 8080 and set the SSL_VERIFY to false

**Comment by vinzent** [comment]
@xjg2010go you might want to give the RPM a try: https://github.com/vinzent/puppetboard-rpm/releases/tag/v0.0.1

**Comment by mterzo** [comment]
Is the rpm current?

**Comment by mterzo** [comment]
Any Luck turning off SSL using `PUPPETDB_SSL_VERIFY = False`?

Also, this looks suspicious, I don't think the SSL certs should be installed in `../cache/`
```
PUPPETDB_SSL_VERIFY = '/opt/puppetlabs/puppet/cache/ssl/certs/ca.pem'
```

**Comment by mterzo** [comment]
Gonna close this since it's looks to be a very custom python installation.
