### ISSUE TITLE
Overview Timeline?

### ISSUE THREAD

**Issue by kirkins** [voxpupuli/puppetboard#398]
I've seen other people post screenshots in the issues like this:

![timeline screenshot](https://user-images.githubusercontent.com/112836/27348085-e56c58b0-55c0-11e7-9977-5c5a21b4d237.png)

On my own setup I never see this timeline widget. I've pulled to make sure everything is up to date.

![untitled](https://user-images.githubusercontent.com/9503662/28031771-69430048-6576-11e7-9b93-d0534df46781.png)

How do you display the timeline, or should it do so by default?

**Comment by mterzo** [comment]
That's daily charts and was introduced in 0.2.1

**Comment by mterzo** [comment]
You need to add these to your settings file.
```
DAILY_REPORTS_CHART_ENABLED = True
DAILY_REPORTS_CHART_DAYS = 8
```

**Comment by kirkins** [comment]
@mterzo great it's working now. Looks awesome 👍

**Comment by mterzo** [comment]
@manuq Added it props to him.
