### ISSUE TITLE
Allow for overriding templates

### ISSUE THREAD

**Issue by nikdoof** [voxpupuli/puppetboard#402]
Probably quite an edge case, but for my current production Puppetboard installation I've had to modify the radiator template to fit in the style of our existing dashboard. At the moment this consists of replacing the ```radiator.html``` whenever I upgrade the package.

It would be nice if we could override the templates, I've been having a look around the Flask documentation (as its been a few years) and it should be possible using a custom Jinja2 loader set on the Flask application.

If this sounds like a sensible plan i'll give it a crack.

**Comment by mterzo** [comment]
If you set the accept header to `application/json` to the endpoint /radiator you get back json. You can write simple HTML page that uses jquery and your done.

**Comment by nikdoof** [comment]
Ahh, now that sounds like a much better solution. I missed that in the code. Thanks @mterzo

**Comment by kirkins** [comment]
If you have a private mod you might find this useful:

https://help.github.com/articles/syncing-a-fork/

In my case we have a private repo that extends Puppetboard by adding some pages where we set rules for our ENC.

Whenever changes are committed here we just run `git fetch upstream && git merge upstream/master`.
