### ISSUE TITLE
Failed node breaks date sorting

### ISSUE THREAD

**Issue by kirkins** [voxpupuli/puppetboard#405]
If you have a node that fails Catalog value will be unknown which breaks the date sorting for everything below or above, depending on sort type:

![untitled](https://user-images.githubusercontent.com/9503662/28175448-42ce92c6-67c2-11e7-9e0e-2a56634ae578.png)

**Comment by gdubicki** [comment]
I assume that this is fixed by the commit mentioned above and therefore closing this issue. Please reopen if it is not.

**Comment by gdubicki** [comment]
Oups, sorry, just noticed that is fixed only in a fork. Can you please open a PR with this fix, @kirkins ?

**Comment by gdubicki** [comment]
I am not seeing the issue on a current version of Puppetboard:

![Screenshot 2022-02-05 at 12 36 12](https://user-images.githubusercontent.com/566632/152642419-e89ae728-aa23-483f-8c30-108538e84511.png)

Please reopen if you still have it after an update. Thanks!
