### ISSUE TITLE
Repeat javascript on main page

### ISSUE THREAD

**Issue by kirkins** [voxpupuli/puppetboard#406]
- `c3.min.js`, included 4 times
- `d3.min.js`, included 3 times
- `dailychart.js` included 2 times

![untitled](https://user-images.githubusercontent.com/9503662/28177221-1c34e77c-67c8-11e7-9d32-737930023de1.png)

**Comment by kirkins** [comment]
I noticed that on the index removing this from `layout.html`:

    {% block head %} {% endblock head %}

Removes lines 46-52 and nothing else. Do you know where the head block defined?

**Comment by mterzo** [comment]
It's defined here: https://github.com/voxpupuli/puppetboard/blob/3867e1aa77e2b24eae56f796df69777e1c955988/puppetboard/templates/layout.html#L60  We still want to keep the block, just need to remove the these from the index.html template.

**Comment by gdubicki** [comment]
As #441 is merged I assume that we can close this issue. Please reopen if needed.
