### ISSUE TITLE
boolean facts are not treated in some places

### ISSUE THREAD

**Issue by ap-16** [voxpupuli/puppetboard#407]
Hey,

it's a great job you have done so far with puppetboard development and I've just a tiny feature request.

It would be a great idea to graph some Boolean facts (apt_reboot_required, apt_updates) and to have  it sort-able by "Inventory" ('Reboot required', 'apt_reboot_required').

I've tried to add this to settings.py:

`
GRAPH_FACTS = ['architecture',
               'clientversion',
               'domain',
               'lsbcodename',
               'lsbdistcodename',
               'lsbdistid',
               'lsbdistrelease',
               'lsbmajdistrelease',
               'netmask',
               'osfamily',
               'puppetversion',
               'apt_reboot_required',
               'apt_updates',
               'processorcount']

INVENTORY_FACTS = [('Hostname', 'fqdn'),
                   ('IP Address', 'ipaddress'),
                   ('OS', 'lsbdistdescription'),
                   ('Architecture', 'hardwaremodel'),
                   ('Kernel Version', 'kernelrelease'),
                   ('Reboot required', 'apt_reboot_required'), 
                   ('Puppet Version', 'puppetversion'), ]
`

The corresponding web page _/fact/apt_updates_ is then empty
and in the _/inventory_ web page the column "Reboot required" isn't sort-able.

Thank you

**Comment by emlun007** [comment]
@ap-16 , Did you solve the problem with apt_reboot_required?

**Comment by smortex** [comment]
@ap-16, the boolean facts bug was fixed in 484727b62c7891c42fede4ecbdc2cb70aa796519, this issue can be closed :wink:
