### ISSUE TITLE
Radiator status wrong color

### ISSUE THREAD

**Issue by quentinsch** [voxpupuli/puppetboard#409]
The radiator view in v0.2.2 gives wrong colors for "Changed" and "Unchanged".
Seems like they are swapped.

![schermafbeelding 2017-07-26 om 11 53 49](https://user-images.githubusercontent.com/7438854/28615463-6b2b1c30-71f9-11e7-8aa9-5a5cafd8e3ad.png)

**Comment by dominiquearpin** [comment]
see #365 ....

**Comment by mterzo** [comment]
in 0.3.0
