### ISSUE TITLE
Daily charts not showing | Facts showed in one column

### ISSUE THREAD

**Issue by jaimegdpr** [voxpupuli/puppetboard#410]
Hi!
I have some issues with the Puppetboard web interface.

**First problem**: Daily charts aren't showed. Instead of them, there is a white 'rectangle' DAILY_REPORTS_CHART_ENABLED = False
![screenshot from 2017-08-09 11-44-50](https://user-images.githubusercontent.com/28893182/29115713-dfdf2e5e-7cf8-11e7-882a-93a4c942782c.png)

DAILY_REPORTS_CHART_ENABLED = True
![screenshot from 2017-08-09 11-46-03](https://user-images.githubusercontent.com/28893182/29115746-f8d4ab82-7cf8-11e7-9612-dc9db7f07c0d.png)

**Second "issue"**: in the Facts tab, the facts are only showed in a column, instead of using several columns.
![screenshot from 2017-08-09 11-52-30](https://user-images.githubusercontent.com/28893182/29115848-4a262696-7cf9-11e7-8d72-bc0f7211ceac.png)

I check with other browsers but there is no changes. The rest of the features are working fine. I left the settings below, maybe they can help to solve the problems.

```
#/var/www/html/puppetboard/wsgi.py
from __future__ import absolute_import
import os

# Needed if a settings.py file exists
os.environ['PUPPETBOARD_SETTINGS'] = '/var/www/html/puppetboard/settings.py'
from puppetboard.app import app as application
```
```
#/etc/httpd/conf.d/puppetboard.conf
WSGIDaemonProcess puppetboard user=apache group=apache threads=5
WSGIScriptAlias /puppetboard /var/www/html/puppetboard/wsgi.py
ErrorLog logs/puppetboard-error_log
CustomLog logs/puppetboard-access_log combined

Alias /puppetboard/static /usr/lib/python2.7/site-packages/puppetboard/static
<Directory /usr/lib/python2.7/site-packages/puppetboard/static>
    Satisfy Any
    Allow from all
</Directory>

<Directory /usr/lib/python2.7/site-packages/puppetboard>
    WSGIProcessGroup puppetboard
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
```
Thanks for your help

**Comment by mterzo** [comment]
Both have been fixed in master and waiting on a release.  Thanks for the submission. 

I'll close this issue when we release 0.3.0

**Comment by mterzo** [comment]
Now in the 0.3.0 Release.
