### ISSUE TITLE
Update jquery-tablesort to latest (0.0.11) version

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#414]
This adds, among other things, a compare option to tablesort, wherein a custom sorting function can be added, like, say, a naturalsort that takes into account the datatypes. This could be real handy.

It's a simple matter of updating the folder and references, but if you'd prefer a pull request I can provide one :-)

**Comment by kirkins** [comment]
Anything to improve the sorting is welcome. I pointed this out in #401 but the sorting is bad in a few places across puppetboard. 

Using this daily with a large amount of nodes and it is a bit annoying:

![untitled](https://user-images.githubusercontent.com/9503662/31549732-146d0c7c-affd-11e7-8f85-9b3e495a14b4.png)

**Comment by larsnaesbye** [comment]
I'll make a pull request, and then I would suggest we lobby hard for a 0.2.3 release :-D

**Comment by larsnaesbye** [comment]
@kirkins : can you test if this works for you? Note that by itself it shouldn't be noticeable at all, as the main reason for it is to provide the compare() hook for us to supply a custom sorting function. But I want to know if I missed something broken.

**Comment by larsnaesbye** [comment]
Merged in release 0.3.0
