### ISSUE TITLE
Remove mention to puppetboard's stability and youth in README

### ISSUE THREAD

**Issue by johanfleury** [voxpupuli/puppetboard#421]
Hi.

The README states that Puppetboard is young and considered unstable:

```
Word of caution
===============

Puppetboard is very, very young but it works fairly well.

That being said a lot of the code is very experimental, just trying
to figure out what works and what not, what we need to do different
and what features we need on the PuppetDB side of things.

As such you should be at least comfortable handling a few errors
this might throw at you.
```

I think this should be removed as it does not represent the current state of the project. It's a 4 years old warning and Puppetboard have seen a lot of changes.

I recently tried to push Puppetboard in my company and I've been denied because of this specific comment. Please consider it harmful for the promotion of this project.

**Comment by mterzo** [comment]
Good point. Your welcome to help help write something up that would help sell it in your company.

**Comment by larsnaesbye** [comment]
#422 simply removes it for now.

**Comment by johanfleury** [comment]
Thank you :)

**Comment by mterzo** [comment]
#422 Closes this.
