### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#434]
Shouldn't Puppetboard get its own logo, displayed to the left of the title? Like a stylized puppet theater or similar?

**Comment by kirkins** [comment]
Custom printed official Puppetboard t-shirts? ... I'm down.

**Comment by mterzo** [comment]
Would be nice. Not in my skillset.

**Comment by mterzo** [comment]
The little vox logo holding a 2x4 in a threatening way, kinda like its gonna beat servers down if they aren’t doing what they are supposed to.

**Comment by larsnaesbye** [comment]
Or the vox puppet holding a tablet-like instrument?

**Comment by mterzo** [comment]
Oh a clipboard an a lab coat.

**Comment by emlun007** [comment]
I was thinking of something like

![vox_in_a_coat3](https://user-images.githubusercontent.com/32731446/32483878-1260d0da-c39e-11e7-8e2f-d63b59b01b58.jpg)

**Comment by larsnaesbye** [comment]
I fully approve of this logo and I think it should go into v 1.0 :-)

**Comment by emlun007** [comment]
@larsnaesbye , I will make some changes to make it even better :)

**Comment by emlun007** [comment]
Better contrast
![better_contrast_vib2](https://user-images.githubusercontent.com/32731446/33092213-cc5e2a62-cef9-11e7-898f-7facb3cb8624.jpg)

**Comment by larsnaesbye** [comment]
Should this replace the text 'Puppetboard' in the top left corner?

**Comment by larsnaesbye** [comment]
@emlun007 : Are you up for donating the second version of the logo to Puppetboard? :-)

**Comment by bastelfreak** [comment]
Hey @emlun007, I'm so sorry for the low responses here. This issue somehow slipped through my radar. The logo looks awesome! Could you provide it as a vector graphics?

**Comment by larsnaesbye** [comment]
Since this has more or less died out, I propose that it be closed. @bastelfreak ?

**Comment by larsnaesbye** [comment]
Could we instead use the generic VoxPupuli icon?
