### ISSUE TITLE
Clicking on fact goes to page with no entries

### ISSUE THREAD

**Issue by kirkins** [voxpupuli/puppetboard#437]
When I go to the fact page I can click on a fact value. For example Linux below:

![untitled](https://user-images.githubusercontent.com/9503662/32506712-4af34684-c3b3-11e7-8ec3-b498aa18fb2b.png)

It goes to an empty page http://localhost:5000/fact/kernel/Linux:

![untitled](https://user-images.githubusercontent.com/9503662/32506800-7f4813b0-c3b3-11e7-8e8d-caf15ca57378.png)

May be related to #302 ?

**Comment by kirkins** [comment]
![untitled](https://user-images.githubusercontent.com/9503662/32507184-cb603f2e-c3b4-11e7-941d-b486128f9a27.png)

**Comment by emlun007** [comment]
I could not reproduce the error. When I click on kernel I get all windows and and linux nodes sorted. 

I think the issue could be in default_settings.py that you need to specify the fact which seems to be a problem for DataTables as the fact doesn't exist.

**Comment by mterzo** [comment]
Something more going on there, I'm unable to reproduce as well.  Structure facts, aren't clickable.  I can't tell what version you have from that screen shot.  There was a fix a while ago #395 which fixed facts causing URL errors.

**Comment by ryebread157** [comment]
I see this behavior on 0.3.0, but only when my environment is listed as 'All environments'

**Comment by emlun007** [comment]
@kirkins , it a problem with loading json, not with dataTable. What do you see in error log?

**Comment by emlun007** [comment]
@ryebread157 , You can't load json due to permission error, you should set right user and group ownership

**Comment by ryebread157** [comment]
@emlun007 Thanks, might you advise where permissions are the issue? I've looked at the error logs more and am unable to tell. For good measure, I changed owner to apache:apache (user:group that runs httpd) recursively to /usr/lib/python2.7/site-packages/{flask,puppetboard}, but no difference in behavior. Regards!
