### ISSUE TITLE
Uptime is not sorted correct

### ISSUE THREAD

**Issue by emlun007** [voxpupuli/puppetboard#440]
Uptime in facts is sorted alphabetically, and hours are treated as days:
![uptime2](https://user-images.githubusercontent.com/32731446/32595854-bf3022d6-c531-11e7-9020-b7df007d928d.jpg)

I am trying to create a class for sorting but I cannot find the right way to capture the values in ('.dataTable td'). Any suggestions?

**Comment by mterzo** [comment]
The Fact section doesn't know anything about the data it's sorting on, it's all string sort.

**Comment by emlun007** [comment]
@mterzo, I have been trying to detect and convert uptime to string and them make sorting.  Something like:

day_search=/(days)/g;
str.match(day_search);
alert(parseInt(day_search,10));

function sortNumber(a,b) {
   return a - b;
};

But still it doesn't work. What is wrong with the code?

**Comment by kirkins** [comment]
I have come the conclusion that @emlun007 is a troll account.

**Comment by larsnaesbye** [comment]
Nope, @emlun007 is my coworker and not a troll.

**Comment by emlun007** [comment]
@kirkins , it is definately not a small patch. I've been trying to make a class for ip addresses and it is a lot of work as I need to make changes in layout.html and marcos.html

**Comment by emlun007** [comment]
This is solved in PR 435:

https://github.com/voxpupuli/puppetboard/pull/435

Closing the issue

**Comment by dal00** [comment]
Why was this never merged? :(
