### ISSUE TITLE
Architecture overview/ documentation in README

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#442]
The flow of data from PuppetDB through backend and frontend isn't that clear to me. Shouldn't we have a section in the README about Puppetboard's architecture so it's easier for people to contribute?

Maybe a simple diagram is enough.

**Comment by mterzo** [comment]
At its simpiliest pypuppetdb just provides a bunch of helper python APIs to make calling PuppetDBs rest APIs.  A clean way of separating the front end UI to the database layer.

**Comment by larsnaesbye** [comment]
OK, if this is enough for most people maybe a diagram isn't needed.
