### ISSUE TITLE
Report corrective changes

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppetboard#447]
Corrective changes are sort of [Puppet Enterprise feature](https://puppet.com/docs/pe/2017.3/inspecting_infrastructure/analyze_changes_across_runs.html#event-types), nonetheless the agent is the same for both the open-source and the enterprise version. The metrics are normally reported by the agent (I'm not sure from which version), so I guess we can use them.

Typically Puppet reports something like this:
```
resources.changed: 2.0
resources.corrective_change: 2.0
resources.out_of_sync: 2.0
resources.failed: 0.0
events.success: 2.0
```
`corrective_change` stands for modification that is done repeatedly like starting service that has previously crashed or changing line in configuration file that was rewritten by another process. Corrective changes should be subset of all changes. Typically it's kind of a change that we should pay attention to. I was thinking if such change could be highlighted on overview dashboard (e.g. yellow or orange color) or introduce another field next to "changes" (but it's already included in changes value).

Any thoughts?

**Comment by tux-o-matic** [comment]
Duplicates #377

**Comment by gdubicki** [comment]
Closing as duplicate.
