### ISSUE TITLE
Error'd node shows as "Unchanged"

### ISSUE THREAD

**Issue by jimr6007** [voxpupuli/puppetboard#449]
Node shows as unchanged on nodes and node detail page but the node summary page shows the node correctly as error'd.

Installed via pip on a a clean CentOS 7 VM, default Python 2.7.5
PuppetDB 4.4.0
Puppetserver 4.10.9

[root@centos-template-7:(NYM) nginx]$ pip list --format=legacy
apipkg (1.4)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.5.3)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
CommonMark (0.7.2)
configobj (4.7.2)
cov-core (1.15.0)
coverage (4.3.4)
decorator (3.4.0)
execnet (1.5.0)
Flask (0.12.2)
Flask-WTF (0.14.2)
funcsigs (1.0.2)
future (0.16.0)
idna (2.6)
iniparse (0.4)
itsdangerous (0.24)
Jinja2 (2.10)
kitchen (1.1.1)
MarkupSafe (1.0)
mock (1.3.0)
pbr (3.1.1)
pep8 (1.7.0)
perf (0.1)
pip (9.0.1)
puppetboard (0.3.0)
py (1.5.2)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pypuppetdb (0.3.3)
pytest (3.0.7)
pytest-cache (1.0)
pytest-cov (2.4.0)
pytest-mock (1.5.0)
pytest-pep8 (1.0.6)
python-linux-procfs (0.4.9)
pyudev (0.15)
pyxattr (0.5.1)
requests (2.18.4)
schedutils (0.4)
setuptools (0.9.8)
six (1.11.0)
slip (0.4.0)
slip.dbus (0.4.0)
urlgrabber (3.10)
urllib3 (1.22)
uWSGI (2.0.15)
Werkzeug (0.14.1)
WTForms (2.1)
yum-metadata-parser (1.1.4)
[root@centos-template-7:(NYM) nginx]$

**Comment by jimr6007** [comment]
<img width="1568" alt="screen shot 2018-01-27 at 12 16 46 pm" src="https://user-images.githubusercontent.com/8090613/35474525-694aed96-035d-11e8-9b1c-a84e9a34a70e.png">

**Comment by jimr6007** [comment]
could someone please take a quick look and let me know if they think this is a puppetboard bug or if perhaps upgrading to PuppetDB 5 might fix.
Thanks !

**Comment by jimr6007** [comment]
this is kinda huge right? 
or, I mean, someone tell me "not super critical" because...

because of this, I can't trust Puppetboard to tell me if I have nodes with issues. 

I tried in a Python 3 test env, no luck there.

**Comment by mterzo** [comment]
We still may have an issue in relation to #283.
Puppet reported Ok but didn't actually succeed.  

I can't see your report ID on the URL you sent.  

Can you provide output of: 

```
curl -XGET localhost:8080/pdb/query/v4/reports -d 'query=["=", "hash", "<REPORT_ID>"]'
```

**Comment by jimr6007** [comment]
[{"catalog_uuid":"84206f33-6458-4def-8818-e7718aee48a6","receive_time":"2018-02-05T17:02:19.607Z","producer":"puppet.nym1.placeiq.net","hash":"b850d96259cf158767fd793da9c623346d585b12","transaction_uuid":"46ae8857-1485-4e45-b4cc-0fb10997e495","puppet_version":"4.10.9","noop":false,"corrective_change":null,"logs":{"data":[{"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:01:54.596952988Z", "level": "info", "source": "Puppet", "message": "Using configured environment 'production'"}, {"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:01:54.597426055Z", "level": "info", "source": "Puppet", "message": "Retrieving pluginfacts"}, {"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:01:54.696322675Z", "level": "info", "source": "Puppet", "message": "Retrieving plugin"}, {"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:01:55.382142308Z", "level": "info", "source": "Puppet", "message": "Loading facts"}, {"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:02:02.903694985Z", "level": "info", "source": "Puppet", "message": "Caching catalog for galadriel-165.nym1.placeiq.net"}, {"file": null, "line": null, "tags": ["info"], "time": "2018-02-05T17:02:03.186415102Z", "level": "info", "source": "Puppet", "message": "Applying configuration version '1517850121'"}, 

{"file": null, "line": null, "tags": ["err"], "time": "2018-02-05T17:02:19.236319753Z", "level": "err", "source": "Puppet", "message": "Failed to apply catalog: Section \"pgdg96\" is already defined, cannot redefine in /etc/yum.repos.d/pgdg-96-redhat.repo"}],"href":"/pdb/query/v4/reports/b850d96259cf158767fd793da9c623346d585b12/logs"},"report_format":6,"start_time":"2018-02-05T17:01:54.217Z","producer_timestamp":"2018-02-05T17:02:19.509Z","cached_catalog_status":"not_used","end_time":"2018-02-05T17:02:10.519Z","resource_events":

{"data":null,"href":"/pdb/query/v4/reports/b850d96259cf158767fd793da9c623346d585b12/events"},"status":"unchanged","configuration_version":"1517850121","environment":"production","code_id":null,"noop_pending":false,"certname":"galadriel-165.nym1.placeiq.net","metrics":{"data":[{"name": "changed", "value": 0, "category": "resources"}, {"name": "corrective_change", "value": 0, "category": "resources"}, {"name": "failed", "value": 0, "category": "resources"}, {"name": "failed_to_restart", "value": 0, "category": "resources"}, {"name": "out_of_sync", "value": 0, "category": "resources"}, {"name": "restarted", "value": 0, "category": "resources"}, {"name": "scheduled", "value": 0, "category": "resources"}, {"name": "skipped", "value": 0, "category": "resources"}, {"name": "total", "value": 74, "category": "resources"}, {"name": "config_retrieval", "value": 1.814362933, "category": "time"}, {"name": "exec", "value": 2.704443196, "category": "time"}, {"name": "file", "value": 7.899154344, "category": "time"}, {"name": "file_line", "value": 0.000228572, "category": "time"}, {"name": "package", "value": 3.7779644329999997, "category": "time"}, {"name": "service", "value": 0.105637311, "category": "time"}, {"name": "total", "value": 16.301790789000002, "category": "time"}, {"name": "total", "value": 0, "category": "changes"}, {"name": "failure", "value": 0, "category": "events"}, {"name": "success", "value": 0, "category": "events"}, {"name": "total", "value": 0, "category": "events"}],"href":"/pdb/query/v4/reports/b850d96259cf158767fd793da9c623346d585b12/metrics"}}]
~

**Comment by jimr6007** [comment]
part of me says "this is Puppet's fault" because the following indicates no error.

But, clearly at least on the Summary screen for the node in Puppetboard, it seems Puppetboard knows something is wrong.

If it already sees the error there, why can't we get that same indication on the Overview page?

[root@galadriel-165:(NYM) yum.repos.d]$ cat /opt/puppetlabs/puppet/cache/state/last_run_summary.yaml
---
version:
  config: 1517850121
  puppet: 4.10.9
resources:
  changed: 0
  corrective_change: 0
  failed: 0
  failed_to_restart: 0
  out_of_sync: 0
  restarted: 0
  scheduled: 0
  skipped: 0
  total: 74
time:
  config_retrieval: 1.814362933
  exec: 2.704443196
  file: 7.899154344
  file_line: 0.000228572
  package: 3.7779644329999997
  service: 0.105637311
  total: 16.301790789000002
  last_run: 1517850139
changes:
  total: 0
events:
  failure: 0
  success: 0
  total: 0

**Comment by mterzo** [comment]
I agree, this is a puppet issue.  Though we can work around it.  We can look at the log section looking for "err".

```
        {
          "file": null,
          "level": "err",
          "line": null,
          "message": "Failed to apply catalog: Section \"pgdg96\" is already defined, cannot redefine in /etc/yum.repos.d/pgdg-96-redhat.repo",
          "source": "Puppet",
          "tags": [
            "err"
          ],
          "time": "2018-02-05T17:02:19.236319753Z"
        }
```

**Comment by mterzo** [comment]
pypuppetdb should handle this and mark the node as failed.

**Comment by gdubicki** [comment]
It probably won't be very helpful, but I got interested in this problem and checked how current puppetboard 0.3.0 behaves with:
* puppetdb 5.2.4,
* puppetserver 5.3.3,
* puppet 5.5.3,

..for similar problems with puppet runs:
* catalog compilation error,
* duplicate resources (duplicate declaration)
* dependency cycles

...and all of them are  **correctly** shown as "failed" in puppetboard.

But my for my test duplicate declaration run I am getting:

```
[root@xxx.yyy:~]# puppet agent -t
Info: Using configured environment 'qa'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/root/.gitlabform] is already declared at (file: /etc/puppetlabs/code/environments/qa/modules/profiles/manifests/common/files.pp, line: 17); cannot redeclare (file: /etc/puppetlabs/code/environments/qa/modules/profiles/manifests/gitlab_tools.pp, line: 36) (file: /etc/puppetlabs/code/environments/qa/modules/profiles/manifests/gitlab_tools.pp, line: 36, column: 3) on node xxx.c.yyy.internal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

..which means that the problem occurs earlier, at catalog compilation, so the whole puppet run is skipped. In @jimr6007 's case catalog is compiled correctly, but gives error during applying.

Anyway: did you have chance to ping pypuppetdb guys about this, @mterzo ?

**Comment by initrd** [comment]
> pypuppetdb should handle this and mark the node as failed.

I've opened [#161](https://github.com/voxpupuli/pypuppetdb/issues/161) at pypuppetdb. This is a major blocker for us, migrating from Foreman. We lose visibility of significantly large errors without the dashboard reporting nodes that fail.

**Comment by gdubicki** [comment]
I have tested this again with the following versions:

* agent - 5.5.22
* server - 5.3.9
* puppetdb - 5.2.8
* puppetboard - 2.2.0

And a puppet run failing in as similar to @jimr6007 's :
```
[root@es-master02.foobar:~]# puppet agent -t --skip_tags ''
Info: Using configured environment 'internal_qa'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Failed to apply catalog: Not a directory @ rb_file_s_lstat - /etc/node_exporter/foobar_puppet_facts.prom
```
..is **correctly** reported as failed in the Puppetboard:

![Screenshot 2021-03-21 at 10 05 50](https://user-images.githubusercontent.com/566632/111899461-065f4380-8a2d-11eb-94e9-878cbae285c6.png)

I am closing this issue then, but please open a new one if you notice this issue again using Puppet 5+ and an up to date Puppetboard, because I completely agree that this is a very important thing.

**Comment by gdubicki** [comment]
It just hit me that maybe I am not seeing this because we are using `WITH_EVENT_NUMBERS = False`, which causes different logic to be applied when determining the nodes' statuses (!), but my test node is reported as failed with that flag enabled too:

![Screenshot 2021-03-21 at 21 00 30](https://user-images.githubusercontent.com/566632/111919121-8ebf0200-8a88-11eb-9fa6-13b7093421f6.png)

**Comment by iglov** [comment]
The same behavior here with puppet 5.5 and centos 7.
Can someone reopen the issue?

**Comment by matejzero** [comment]
Your problem is due to `usecacheonfailure` setting in puppet agent. This is set to `true` by default. Set it to `false` and you will have failed node.

> Whether to use the cached configuration when the remote configuration will not compile. This option is useful for testing new configurations, where you want to fix the broken configuration rather than reverting to a known-good one.

**Comment by iglov** [comment]
Can't approve right now, cuz a haven't broken nodes at this moment, but i'll try to broke some node and then set `usecacheonfailure` .

**Comment by iglov** [comment]
Yep, that's worked 4 me, thx @mterzo !
I just added on all agents into puppet.conf :
```
[agent]
# https://github.com/voxpupuli/puppetboard/issues/449
usecacheonfailure = false
```
Now, instead of "Applied catalog" on broken nodes i have "Not using cache on failed catalog" and puppetboard shows the nodes as failed.

**Comment by gdubicki** [comment]
Thanks @matejzero ! If this fixed your issue @iglov , then I am closing this again. Please reopen if needed.
