### ISSUE TITLE
Pulling the unreported nodes details using curl/DB query

### ISSUE THREAD

**Issue by pradeepatta** [voxpupuli/puppetboard#453]
Hi,

I want pull only the node's host name using either Curl/database query based on node's status.

For example: I want to know the 29 nodes which are not reporting as shown in the below screenshot

![image](https://user-images.githubusercontent.com/36001514/36298059-1fe62962-131c-11e8-9c99-7de5b3c89671.png)

I tried below commands but they are giving complete information but I just need the host names which are "failed" or "changed" or "Pending" or "Unreported"

curl http://localhost:8080/pdb/query/v4/nodes
curl http://localhost:8080/pdb/query/v4/nodes?unreported

Let's say, If I run Database query/Curl statement for nodes whose status is "failed" then it should give the output as below:
host2
host13
host15
host17

Is there any way to do that? Please let me know

**Comment by tskirvin** [comment]
<https://pypi.org/project/puppetdb-tools/>

I've got scripts built into there for `puppetdb-failed` and `puppetdb-tooquiet`.

**Comment by gdubicki** [comment]
Thanks for sharing your tool @tskirvin, looks very useful!
Closing as it seems to fix @pradeepatta ’s problem. Please reopen if needed.
