### ISSUE TITLE
js, and css fetched externaly

### ISSUE THREAD

**Issue by schlitzered** [voxpupuli/puppetboard#464]
puppetboard should ship all js and css files itself, instead of including them from 3rd parties.

currently the following is included from the web as far as i can tell:

https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/css/dataTables.semanticui.min.css
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/js/jquery.dataTables.min.js
https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/js/dataTables.semanticui.min.js
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js

http://fonts.googleapis.com/css?family=Open+Sans
https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin

**Comment by volans-** [comment]
For completeness, see also #458 and #459

**Comment by schlitzered** [comment]
thx for pointing out that there is a switch.

but enabling offline mode results in a broken puppetboard:

there is a http 500 in:

http://puppetboard.example.com/offline/Semantic-UI-2.1.8/semantic.min.css

**Comment by mterzo** [comment]
Those HTTP references in min.css are in comments.

https://github.com/voxpupuli/puppetboard/blob/master/puppetboard/static/Semantic-UI-2.1.8/semantic.min.css

**Comment by volans-** [comment]
@schlitzered see the 2 issues I've referenced earlier above. I guess you've installed the version on PyPi like I did.

**Comment by larsnaesbye** [comment]
This should be fixed in the 1.0.0 release, which is on PyPi now.
