### ISSUE TITLE
puppetboard 0.3.0 in docker offline_mode

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/puppetboard#471]
When i use offline mode as environment variable passed into the docker container, the pages are not rendering properly (simplistic html - sans fancy js controls)

Using this:
https://github.com/dot1q/puppet-in-docker/blob/master/puppetboard/Dockerfile

**Comment by mterzo** [comment]
Can you try `terzom/puppetboard:latest`

**Comment by rismoney** [comment]
This works most excellently!  Thank you very much.

**Comment by mterzo** [comment]
Awesome. There was a bug that was fixed on master that addressed that afte the 0.3.0 release.
