### ISSUE TITLE
Missing functionality when using PuppetDB 5.2.x

### ISSUE THREAD

**Issue by mpepping** [voxpupuli/puppetboard#473]
As per PuppetDB 5.2.x, the PuppetDB database schema changed. This has some consequences for Puppetboard. It not possible to see Catalogs of list nodes per Environment (only '*' shows all nodes).

**Comment by mpepping** [comment]
Possible more a [vvoxpupuli/pypuppetdb](https://github.com/voxpupuli/pypuppetdb) related issue?

**Comment by larsnaesbye** [comment]
I cannot reproduce this problem. When selecting a different environment, I get the nodes in that environment only. Using PuppetDB 5.2.8 here.

**Comment by mpepping** [comment]
I've tested again with PuppetDB 5.2.1 and 5.2.6. Just to check with your test:

I see all nodes on `/nodes`, but when switching to an environment (eg. `/production/nodes`) not a single node is listed.

When running PuppetBoard with `ENABLE_CATALOG=true`, the `/catalogs` endpoint remains empty.

Will check with PuppetDB 5.2.8 at my end.
