### ISSUE TITLE
Internal Server Error after a few minutes

### ISSUE THREAD

**Issue by witchbutter** [voxpupuli/puppetboard#474]
I am able to get Puppetboard to run briefly but sooner or later the connection fails with an error like this in the logs:

`ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:15672 over HTTPS.
ERROR:puppetboard.utils:HTTPSConnectionPool(host='puppet.somedomain.com', port=15672): Max retries exceeded with url: /pdb/query/v4/reports?query=%5B%22extract%22%2C%5B%5B%22function%22%2C%22count%22%5D%2C%22status%22%5D%2C%5B%22and%22%2C%5B%22%3E%3D%22%2C+%22start_time%22%2C+%222018-06-20T00%3A00%3A00.000000Z%22%5D%2C%5B%22%3C%22%2C+%22start_time%22%2C+%222018-06-21T00%3A00%3A00.000000Z%22%5D%2C%5B%22%3D%22%2C+%22environment%22%2C+%22staging%22%5D%5D%2C%5B%22group_by%22%2C%22status%22%5D%5D (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:726)'),))
ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:15672 over HTTPS.
ERROR:puppetboard.utils:('Connection aborted.', error(104, 'Connection reset by peer'))
10.29.0.15 - - [27/Jun/2018:23:25:07 +0000] "GET /daily_reports_chart.json HTTP/1.1" 500 3542 "http://pboard-01.somedomain.com:9080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0"
ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:15672 over HTTPS.
ERROR:puppetboard.utils:HTTPSConnectionPool(host='puppet.somedomain.com', port=15672): Max retries exceeded with url: /pdb/query/v4/reports?query=%5B%22extract%22%2C%5B%5B%22function%22%2C%22count%22%5D%2C%22status%22%5D%2C%5B%22and%22%2C%5B%22%3E%3D%22%2C+%22start_time%22%2C+%222018-06-20T00%3A00%3A00.000000Z%22%5D%2C%5B%22%3C%22%2C+%22start_time%22%2C+%222018-06-21T00%3A00%3A00.000000Z%22%5D%2C%5B%22%3D%22%2C+%22environment%22%2C+%22staging%22%5D%5D%2C%5B%22group_by%22%2C%22status%22%5D%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc0392871d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

I used the port 15672 as a test because I know for sure that port is not firewalled.  It will work 5-10 minutes and some information displays but as soon as this error occurs a few times it goes to an internal server error page.  There is no latency between the puppet master and this server.

I don't suspect SSL because the connections work fine for a while, however:
`root@someserver:~# curl https://puppet.somedomain.com:15672
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.`

I did specify the certs that the server in question has from the puppet agent signing request and the specified CA.  I've also increased the timeout to up to 600 seconds with no effect.  What can I do to figure this out?

**Comment by witchbutter** [comment]
I replaced the internal domain names with somedomain for use on github.  I'm sure it connects because like I said it functions for about 10 minutes.  I can also see the accesses in the puppetdb access log from the master.

**Comment by mterzo** [comment]
Are you running puppetboard in a container on the master?

**Comment by witchbutter** [comment]
I've tried running it in container on the master and in a container on an external server, yes

**Comment by mterzo** [comment]
Ah. That explains why you it’s not working on the puppet server. Localhost in the container is the container not the host machine. 

Why it’s failing externally I’m not sure. I’ve never seen that failure scenario.  Are there any logs from your puppetdb server?

**Comment by witchbutter** [comment]
It looks like once the request gets too large it fails to respond.  This access failed:
`ip-10-29-1-144.ec2.internal - - [28/Jun/2018:21:46:24 +0000] "GET /pdb/query/v4/resources?query=%5B%22extract%22%2C%5B%5B%22function%22%2C%22count%22%5D%5D%2C%5B%22%3D%22%2C+%22environment%22%2C+%22staging%22%5D%5D HTTP/1.1" 200 17 "-" "-" 10827`

This is logged by puppetboard at the same time:
`ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:8081 over HTTPS.
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/puppetboard/app.py", line 176, in index
    for node in nodes:
  File "/usr/local/lib/python2.7/site-packages/pypuppetdb/api.py", line 406, in nodes
    nodes = self._query('nodes', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pypuppetdb/api.py", line 343, in _query
    auth=auth)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:8081 over HTTPS.
ERROR:puppetboard.utils:HTTPSConnectionPool(host='puppet.somedomain.com', port=8081): Max retries exceeded with url: /pdb/query/v4/environments (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3764ef3ad0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by witchbutter** [comment]
I've tried running puppetdb connections over 8080 with no SSL.  There are fewer crashes but the problem persists:

`ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:8080 over HTTP.
ERROR:puppetboard.utils:('Connection aborted.', BadStatusLine("''",))
ERROR:pypuppetdb.api:Could not reach PuppetDB on puppet.somedomain.com:8080 over HTTP.
ERROR:puppetboard.utils:('Connection aborted.', error(104, 'Connection reset by peer'))`

Shortly after an error like this I get:

`[2018-07-02 17:17:26 +0000] [5] [CRITICAL] WORKER TIMEOUT (pid:275)
[2018-07-02 17:17:26 +0000] [275] [INFO] Worker exiting (pid: 275)
[2018-07-02 17:17:26 +0000] [594] [INFO] Booting worker with pid: 594`

This is running on the puppetmaster in a docker container using puppet/puppetboard which is version 0.3.0.

**Comment by witchbutter** [comment]
Additionally I have tried dropping the puppetdb and allowing it to be recreated.  This changes nothing.

**Comment by witchbutter** [comment]
I have manually installed puppetboard via pip on 16.04, bypassed SSL connecting directly to PuppetDB on a puppet master and I am still getting crashes:

`ERROR:pypuppetdb.api:Could not reach PuppetDB on localhost:8080 over HTTP.
ERROR:puppetboard.utils:('Connection aborted.', error(104, 'Connection reset by peer'))
ERROR:pypuppetdb.api:Could not reach PuppetDB on localhost:8080 over HTTP.
ERROR:puppetboard.utils:('Connection aborted.', error(104, 'Connection reset by peer'))`

I have no idea what I could possibly be doing wrong here.

**Comment by witchbutter** [comment]
I have solved my issue.  Fundamentally the issue was with PuppetDB.  I removed the database in postgres, purged the puppetdb package and erased all old config files carried over from puppet 4.5 or so in /etc/puppetlabs/puppetdb/conf.d and /opt/puppetlabs/server/data/puppetdb, upgraded to puppetdb 5 and then used the puppetlabs/puppetdb forge module to restore puppetdb, rather than a manual install.  After this reports began flowing in as expected and all queries from the docker container puppet/puppetboard began working.  If you watch the puppetdb log you should see entries containing 'replace facts', 'replace catalog', and 'store report' if your puppetdb is functioning correctly.
