### ISSUE TITLE
Filter report messages

### ISSUE THREAD

**Issue by bmack94** [voxpupuli/puppetboard#481]
To make debugging easier it would be nice to sort the view by resource status.
When i click on a report to see which resource failed, i want to have a drop down to select my view, for example warnings and errors. so i only see the things that failed, not the things that succeeded.
If you used / use foreman, there it is possible, i would like to have a similar option in Puppetboard.

Regards,
bmack

**Comment by gdubicki** [comment]
Related to  #641.

**Comment by gdubicki** [comment]
Please check out v3.5.0rc1 with this feature, @bmack94. A final release will be done within a few days.

**Comment by gdubicki** [comment]
Final [v3.5.0](https://github.com/voxpupuli/puppetboard/releases/tag/v3.5.0) released.
