### ISSUE TITLE
Data recovery problem

### ISSUE THREAD

**Issue by mentohs** [voxpupuli/puppetboard#482]
Hello,

Here is my installation:
puppetboard => 0.3
pypuppuetdb => 3.3
puppetdb => 4.4.2
puppet => 4.8.2

Everything is installed on the same machine.
All the installations went well, the site is functional but no data is displayed in puppetboard.

In the logs, I have the following errors:
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_url called with endpoint: environments and path: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /pdb/query/v4/environments HTTP/1.1" 200 27
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_query called with endpoint: nodes, path: None, query: ["extract",[["function","count"]],["and",["=", "catalog_environment", "puppetTest"],["=", "facts_environment", "puppetTest"]]], limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_url called with endpoint: nodes and path: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /pdb/query/v4/nodes?query=%5B%22extract%22%2C%5B%5B%22function%22%2C%22count%22%5D%5D%2C%5B%22and%22%2C%5B%22%3D%22%2C+%22catalog_environment%22%2C+%22puppetTest%22%5D%2C%5B%22%3D%22%2C+%22facts_environment%22%2C+%22puppetTest%22%5D%5D%5D HTTP/1.1" 200 13
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_query called with endpoint: resources, path: None, query: ["extract",[["function","count"]],["=", "environment", "puppetTest"]], limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_url called with endpoint: resources and path: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /pdb/query/v4/resources?query=%5B%22extract%22%2C%5B%5B%22function%22%2C%22count%22%5D%5D%2C%5B%22%3D%22%2C+%22environment%22%2C+%22puppetTest%22%5D%5D HTTP/1.1" 200 13
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_query called with endpoint: nodes, path: None, query: ["and",["=", "catalog_environment", "puppetTest"],["=", "facts_environment", "puppetTest"]], limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_url called with endpoint: nodes and path: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /pdb/query/v4/nodes?query=%5B%22and%22%2C%5B%22%3D%22%2C+%22catalog_environment%22%2C+%22puppetTest%22%5D%2C%5B%22%3D%22%2C+%22facts_environment%22%2C+%22puppetTest%22%5D%5D HTTP/1.1" 200 2
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_query called with endpoint: event-counts, path: None, query: ["=", "latest_report?", true], limit: None, offset: None, summarize_by certname, count_by None, count_filter: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:pypuppetdb.api:_url called with endpoint: event-counts and path: None
[wsgi:error] [pid 16827] [client IP_Client:59899] DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /pdb/query/v4/event-counts?query=%5B%22%3D%22%2C+%22latest_report%3F%22%2C+true%5D&summarize_by=certname HTTP/1.1" 200 2

when I try with "curl", the result seems to me coherent.

Thank you for your help

**Comment by gdubicki** [comment]
Closing as outdated. Please reopen if you still experience such problem with the current version of the Puppetboard.
