### ISSUE TITLE
Add "environment" column in Nodes view

### ISSUE THREAD

**Issue by nasjomach** [voxpupuli/puppetboard#484]
It might be quite helpful to have the "environment" column in the "Nodes" of puppetboard.
This would allow for quick overview of all nodes per env, instead of having to toggle the environments with the button at the right.

**Comment by gdubicki** [comment]
Hi @nasjomach, thanks for the suggestion! I think that #522 is about the same thing and I already suggested what we can do there so I will close this ticket as a duplicate.
