### ISSUE TITLE
how to connect multiple puppet masters to puppetdb

### ISSUE THREAD

**Issue by Hemantt91** [voxpupuli/puppetboard#492]
Hi All,

Suppose I have puppet01-hem and puppet02-hem puppet master and one puppet db node i.e puppetdb01-hem 

How i can connect my both puppet master to puppet db ??

**Comment by ryebread157** [comment]
One of the masters needs to be the single CA server, and the other needs to be set to use it as its CA server. The second master needs to join the first as agent, then made a master. Once this is complete, need to set the option (documented) on the second master for it to *not* be a CA in /etc/puppetlabs/puppetserver/services.d/ca.cfg. All agents and masters need to have the first master listed as ca_server in the [main] section of their puppet.conf.

Then, the puppetdb server needs to also use the same CA server. This will allow both your masters to send agent reports to the same puppetdb.

This is all possible with Puppet community edition, and I am doing it. Puppet Inc does not document this terribly well, I imagine they would encourage Puppet Enterprise once you start needing to scale up.

**Comment by njegosrailic** [comment]
Hi,

you need to add the puppetdb conf file: 

/etc/puppetlabs/puppet/puppetdb.conf

with content: 

```
[main]
server_urls = https://puppetdb-server:8081/
soft_write_failure = true
```

If you want to store reports you shoud add to the master section:

```
reports = puppetdb
storeconfigs = true
storeconfigs_backend = puppetdb
```

Also, there are a lot of public modules to manage this file/settings for exampe : https://github.com/theforeman/puppet-puppet or puppetdb module. 

Because this isn't a issue it could be closed.

**Comment by larsnaesbye** [comment]
I agree that this could be closed, unless the OP has a comment.

**Comment by gdubicki** [comment]
Closing, please reopen if needed.
