### ISSUE TITLE
default sort order

### ISSUE THREAD

**Issue by fragfutter** [voxpupuli/puppetboard#493]
The order of data has a insconsistend sorting order between different pages.

the overview (/) shows node status details. This list is sorted by report date in ascending order (oldest first)

The nodes overview (/nodes) is sorted by catalog date in ascending order
Node details page (/node/NAME) have their entry sorted in descending order (newest first)

reports overview page (/reports) is sorted in ascending order.

Would it make sense that any page/table that is sorted by a date column by default uses the same ordeer. And the order should be descending (newest first)?

**Comment by gdubicki** [comment]
Hi @fragfutter!

As of v3.4.0RC4 all of the pages you listed have their nodes/reports lists sorted by report date in descending order (newest first), except /nodes which uses the _catalog_ date but also newest first.

Please update Puppetboard and reopen if you still see inconsistency in the latest version.
