### ISSUE TITLE
Puppet 6.x?

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#499]
Not an issue as such, but we're contemplating upgrading from Puppet 5.5 to 6.x. Does Puppetboard 0.3.0 support this?

**Comment by othalla** [comment]
For me, it should work as it rely on puppetdb.
However, we have to check on this side.

**Comment by ZeroPointEnergy** [comment]
We run Puppet 6 with the newest PuppetDB and Puppetboard and it works fine. The PuppetDB API did not change AFAIK

**Comment by larsnaesbye** [comment]
Thank you all for the answers. We’ll upgrade :)
