### ISSUE TITLE
Internal network can not access outside javascipt file

### ISSUE THREAD

**Issue by samz-github** [voxpupuli/puppetboard#500]
I have setup Puppetboard inside internal network which can not acccess outside internet. As a result, some javascipt files can not be download through internet. And puppetboard become very slow! Can you provide option to advoid to download javascipt files from outside internet?

![image](https://user-images.githubusercontent.com/15801510/57607011-b85d9700-759c-11e9-8123-df2b48e3d410.png)

**Comment by volans-** [comment]
@samz-github see the `OFFLINE_MODE` settings and #464 for some additional context. In particular if you've installed it from PyPI see also #458  and #459.

I think this could be closed as duplicate of #464.

**Comment by samz-github** [comment]
@volans- As the instructions https://github.com/voxpupuli/puppetboard/commit/e5c9b300efb312d9a64d50fad274de322b227b18, I have  done these:
1. Set the OFFLINE_MODE=True
2. Replaced from external url to css/google_fonts.css on semantic.min.css 
3. Added css/google_fonts.css file 
It's faster now. But I still get the 500 error when try to get semantic.min.css, any wrong?
![image](https://user-images.githubusercontent.com/15801510/57615629-bdc3dd00-75ae-11e9-8fe9-b7c043c5bbc3.png)

**Comment by volans-** [comment]
@samz-github the PyPI release unfortunately doesn't include e5c9b30, so either you apply it manually or install it from the repository at a later commit than the last release.
Join #426 to ask for a new release.

**Comment by samz-github** [comment]
Awesome! After I  replaced the puppetboard dir under Python site-packages dir with Github puppetboard dir, it works now. Thanks @volans- !

**Comment by larsnaesbye** [comment]
Version 1.0.0 is out now with the changes included :-)

**Comment by samz-github** [comment]
Well done! @larsnaesbye
