### ISSUE TITLE
Error: Class 'puppetboard' is already defined

### ISSUE THREAD

**Issue by Jmkgabriel** [voxpupuli/puppetboard#507]
Greetings, i'm fairly new to using puppet and am trying to get puppetboard working but have run into an installation issue.  I have PuppetDB running on its own server and succesfully collecting reports from all of the agents, version 6.3.2 on CentOS 7.  I'm using the installation directions from the puppet forge but when i try to apply (puppet apply init.pp), I get the following error message:  

Error: Class 'puppetboard' is already defined (file: /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp, line: 166); cannot redefine (file: /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp, line: 166) on node 

The init.pp file is mostly default at this point except for defining the puppetmaster class, i've attached it below.  Any help would be greatly appreciated.  The init.pp file is below but in .txt format:  

[init.txt](https://github.com/voxpupuli/puppetboard/files/3229465/init.txt)

**Comment by bastelfreak** [comment]
Hi @Jmkgabriel. Do I see this correctly that you enabled the example within the init.pp of this module? The example(s) are meant to work in a standalone file that than calls this module. I suggest you take a look at the `roles and profiles pattern`. This is a design principle that provides a easy method to call external "component modules" (a puppet module that manages a specific component, like this puppetboard module).

**Comment by Jmkgabriel** [comment]
This gave me the hint i needed.  It's now up and running and couldn't be more pleased, thanks for the nudge in the right direction.
