### ISSUE TITLE
Milestones and progress

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#510]
We agreed to get 1.0 out fast and then work on the next. Some pull requests seem perfectly valid, like #438 #439 and #441 .

I suggest we create a 1.0.1 (or 1.1) milestone, and close or move the open issues from the 0.3.0 milestone to it. Does that seem reasonable?

**Comment by othalla** [comment]
Agreed!

**Comment by othalla** [comment]
@larsnaesbye think we can go further, seems we still have couple of bugs like https://github.com/voxpupuli/puppetboard/pull/521 that need to be checked.

I also noticed slow page loading while running on large puppet environments, guess we should check https://github.com/voxpupuli/puppetboard/pull/512

I think we can also work on python 2.7 removal ?

**Comment by bastelfreak** [comment]
@othalla +1 for dropping python 2.7 :)

**Comment by larsnaesbye** [comment]
@othalla Yes absolutely. Python 2.7 is dead and should be removed.

**Comment by larsnaesbye** [comment]
I added #525 to at least warn people for now.

**Comment by larsnaesbye** [comment]
Now that the awesome 1.1.0 release is out, I'm closing this issue :-)
