### ISSUE TITLE
Some facts just don't display ...

### ISSUE THREAD

**Issue by Philrobots** [voxpupuli/puppetboard#514]
So when I am on the Puppetboard, I go in the "Nodes" section and I click on a random certname to see all the details&facts  of this server and the Facts tell me "No data available in table", so I just can't see the facts of the server. I will drag a picture of it.

![facts not find](https://user-images.githubusercontent.com/47373969/59949428-0473e500-9441-11e9-8ab2-f6f8139fb965.png)

So I have put the '*' in the default settings in the code , I have also delete the lines of codes query.add(EqualsOperator('facts_environment', env)) in the app.py but it still does not show me the facts ..

Can please some of you help me or tell me where to look in the code to debug this ?

thanks you guys
Have a great weekend

**Comment by basti-nis** [comment]
Got the same problem with Fact "puppetversion".
Nothing show's up since i upgraded to v1.0.0.

**Comment by Philrobots** [comment]
> Got the same problem with Fa
ct "puppetversion".
> Nothing show's up since i upgraded to v1.0.0.

**Comment by Philrobots** [comment]
> Got the same problem with Fact "puppetversion".
> Nothing show's up since i upgraded to v1.0.0.

I am currently trying to debug this, I will keep you update

**Comment by Philrobots** [comment]
> Got the same problem with Fact "puppetversion".
> Nothing show's up since i upgraded to v1.0.0.

I am presently trying to debug the puppetboard, I will keep you update

**Comment by othalla** [comment]
@Philrobots could you check?

**Comment by basti-nis** [comment]
Hi all,
for me it's fixed in version 1.1.0!
Now i've got another problem, but that's not related to this.

**Comment by larsnaesbye** [comment]
@basti-nis : So, can this be closed? :-)

**Comment by basti-nis** [comment]
@larsnaesbye for me it can be closed :)
