### ISSUE TITLE
[Low Prio, but nasty] 404 on empty puppetdb

### ISSUE THREAD

**Issue by spali** [voxpupuli/puppetboard#515]
Not sure if this is only in my case with everything dockerized.
But at least it provokes it a bit more.

I tried almost a day to find out was was wrong 🙈  with just setup a simple test environment (all dockerized). And puppetboard always failed to start (heathlcheck of the container returned always 404.
Then I had an spontaneous intuition ... puppetdb was empty, because I let never run an agent agains the test environment. After let a docker puppet agent run, it worked magically 🏁 

Maybe it would be nice to catch this case for and empty puppetdb. And do not return 404 error code. Maybe return an empty Overview page or with a note. That would also solve the problem of the healthcheck that would fail otherwise till a report comes in.
if this would be based on the environment that is empty, this could also makes debugging the case of issue #460 easier.

**Comment by gdubicki** [comment]
This should be fixed in [v3.6.0](https://github.com/voxpupuli/puppetboard/releases/tag/v3.6.0), released today. Please comment if it is not, @spali.
