### ISSUE TITLE
[Low Prio] invalid seek in docker

### ISSUE THREAD

**Issue by spali** [voxpupuli/puppetboard#516]
Docker Version: 18.09.6
OS: Debian Stretch

Running in Docker returns invalid seek error on /dev/stdout and fails to start.
There are multiple issues around on github about this.
Regarding gunicorn, I would suggest to change 
https://github.com/voxpupuli/puppetboard/blob/3b50062af06986fc81ac8812e351e76bb136ee25/Dockerfile#L15
to use
`--access-logfile=-` which is also the documented way of gunicorn to log to stdout.
I currently run puppetboard with your dockerfile but overriding the command in the compose file to `--access-logfile=-` and it works flawlessly.

**Comment by spali** [comment]
Side note... didn't want to create another issue just for this, but would be cool to allow to configure the gunicorn workers with an environment variable:
`--workers="${PUPPETBOARD_WORKERS}"`, setting this to a higher value than the default of 1 increases the loading times of puppetboard drastically. I'm currently run it with 4.

Let me know if I should open a new Issue for this.

**Comment by bastelfreak** [comment]
@spali are you able to provide PRs for this?

**Comment by spali** [comment]
Sure, but be patient, bit busy currently, even is a small change.

**Comment by spali** [comment]
Fixed in master ed29577
