### ISSUE TITLE
c3.js was removed from the layout.html template but is required for certain facts

### ISSUE THREAD

**Issue by regner** [voxpupuli/puppetboard#520]
The c3 JS files required to render a graph only get pulled in if DAILY_REPORTS_CHART_ENABLED is set to true: https://github.com/voxpupuli/puppetboard/blob/15e2fc80c09ccf187dc901626dba28b1ec20ceb7/puppetboard/templates/node.html#L8

The facts.html template doesn't care about that and attempts to render the graph if render_graph is set to true: https://github.com/voxpupuli/puppetboard/blob/master/puppetboard/templates/fact.html#L11

render_graph gets set irregardless of the DAILY_REPORTS_CHART_ENABLED setting: https://github.com/voxpupuli/puppetboard/blob/master/puppetboard/app.py#L678

So if DAILY_REPORTS_CHART_ENABLED is not set (the forge module for puppetboard doesn't set this value by default) then going to any of the facts in list of default facts fails to load as c3 doesn't exist.

render_graph should only get set to true if DAILY_REPORTS_CHART_ENABLED is also set to true or including c3 shouldn't rely on DAILY_REPORTS_CHART_ENABLED and just always happen.

**Comment by regner** [comment]
Actually I lied, that setting only applies to the node.html template. I wasn't paying attention.

layout.html had c3 removed: https://github.com/voxpupuli/puppetboard/commit/e08ede01c77edb7510f9f3615e5cc6fdf099a506

It is required for these fact pages.

**Comment by regner** [comment]
Quick fix is to set `GRAPH_FACTS` to an empty array.

**Comment by blackknight36** [comment]
This appears to be what is causing #520.

**Comment by blackknight36** [comment]
I've confirmed that reverting #e08ede0 allows graphs to load.

**Comment by regner** [comment]
#519 is the same issue for sure. I did some searching but missed that. Thanks for pointing that out. I shall close this issue.
