### ISSUE TITLE
jquery out of date

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppetboard#529]
puppetboard ships with jquery 2.1.1 which is has been released over 4 years ago. it's also not the latest supported version of the 2.1.x series (2.1.4). and obviously it's not the latest jquery release either (now at 3.4.1).

this makes it hard to package in debian (among other thigns) because Debian (currently) ships with jquery 3.3. I also suspects it might have security vulnerabilities, at least cvedetails lists two XSS:

https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-11031/version_id-286384/Jquery-Jquery-2.1.1.html

so it seems like upgrading jquery might be a good idea here. :p

**Comment by larsnaesbye** [comment]
Seconded. Any arguments against jumping to 3.4.1 right away?

**Comment by bastelfreak** [comment]
I'm always +1 for up2date dependencies. Anybody here wants to propose and test a PR?

**Comment by kevgreen-ebay-com** [comment]
With thanks to the supportive open source contribution friendly policy of my employer, I've got some patched code for this.

Long story why, but I couldn't properly test a patch against the latest version. so I've got a patched version of the 1.1.0 tree with upgraded jquery ready to upload to a branch here, but no access. If someone could grant me access to create a new branch for it, or suggest an alternative way for me to upload I'll do it ASAP.

It looks like nothing changed regards jquery between 1.1.0 and latest version anyway, so this should just apply cleanly to the latest.

PS. It would be great if python 3.5 support for the current latest could be put back and kept a little while longer.

**Comment by anarcat** [comment]
to provide patches here, you need to "fork" the repo, push patches to your git repo, and issue a "pull request". more details on how pull requests work is available here:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

if i misunderstood your question: sorry for stating the obvious. :)

also feel free to just copy-paste the patch here if that process is too cumbersome - it's better to have a half-working suggestion than nothing at all!

same comment regarding py3.5 - maybe we could still support that if the patch is minimal, but that should be a separate issue.

**Comment by kevgreen-ebay-com** [comment]
Ah, yes, that's a pattern I'm familiar with, just not really done it that way before. Hopefully I've done it right as above :)

https://github.com/voxpupuli/puppetboard/pull/549/files

**Comment by anarcat** [comment]
thanks for the patch! and yes, you did fine :)
