### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ryangatesatUS** [voxpupuli/puppetboard#534]
When I try to access the puppboard, I see the following error.

> Internal Server Error
> This error usually occurs because:
> 
> We were unable to reach PuppetDB;
> The query to be executed was malformed resulting in an incorrectly encoded request.
> Please have a look at the log output for further information.

Where can I find the log file?

**Comment by basti-nis** [comment]
i think this is duplicated issue #527

**Comment by ryangatesatUS** [comment]
In our case, we doubled the java heapspace and increased the timeout from 20-40 seconds. I know it's not a permanent fix, but it has helped.

**Comment by gdubicki** [comment]
Closing as OP’s problem seems to be resolved. Please reopen if needed.
