### ISSUE TITLE
Daily charts missing

### ISSUE THREAD

**Issue by jplindquist** [voxpupuli/puppetboard#539]
Since #438 the daily chart is missing on the overview and node view when Puppetboard is not on a root path (ex: behind a proxy).  This change forces all requests for this to be on the root path.  Alternative setups, like reverse proxies, could have Puppetboard under a subdirectory.

Ex:
Base URL: https://puppet.example.com/puppetboard/
Requests for `daily_reports_chart.json` go to https://puppet.example.com/daily_reports_chart.json and result in a 404, where they should be routed to https://puppet.example.com/puppetboard/daily_reports_chart.json

**Comment by bastelfreak** [comment]
thanks for raising this issue @jplindquist. Are you able to provide a pull request?

**Comment by jplindquist** [comment]
@bastelfreak We've worked around it for the time being, but I can try and look into a possible fix.  I have an idea that would require an additional configuration setting for the base/root path and include changing the dailychart.js file into a template so it can render the URL based on the configuration setting.  I don't know what effect this might have on anything else yet though...

**Comment by nmaludy** [comment]
Closed by #557

**Comment by nmaludy** [comment]
Release `2.1.1` was just created with this fix included.
