### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by larsnaesbye** [voxpupuli/puppetboard#540]
Wouldn't it be nice with a docker-compose.yml to replace the lengthy `docker run` command?

I've been talking to @runejuhl about this, and I know he's got one that will suit this purpose.

**Comment by bastelfreak** [comment]
sounds good to me :)

**Comment by metalcated** [comment]
docker-compose.yml goes in the root directory of the source from git.

`version: '2'
services:
  deamon:
    image: 'puppetboard:latest'
    build: './'
    restart: always
    environment:
      - PUPPETDB_HOST=<server fqdn>
      - PUPPETDB_PORT=8081
      - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppetdb/ssl/ca.pem
      - PUPPETDB_KEY=/etc/puppetlabs/puppetdb/ssl/private.pem
      - PUPPETDB_CERT=/etc/puppetlabs/puppetdb/ssl/public.pem
      - INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddress'
      - ENABLE_CATALOG=True
      - GRAPH_FACTS='architecture,puppetversion,osfamily'
    ports:
      - "9080:80"
    volumes:
      - '/etc/puppetlabs/puppet/ssl:/etc/puppetlabs/puppet/ssl'
      - '/etc/puppetlabs/puppetdb/ssl:/etc/puppetlabs/puppetdb/ssl'`

**Comment by rismoney** [comment]
is there a reason for the puppet/ssl volume mount?

**Comment by metalcated** [comment]
> is there a reason for the puppet/ssl volume mount?

Yeah you probably don't need that to be honest. I had it on there at one point troubleshooting something.

**Comment by larsnaesbye** [comment]
Closing this as an official image has been designated.
