### ISSUE TITLE
Reports can no longer be displayed in 2.0.0

### ISSUE THREAD

**Issue by ZeroPointEnergy** [voxpupuli/puppetboard#543]
We upgraded our puppetboard from 1.0.0 to 2.0.0. With the new version when you click on a report to display the events (/report/{id} path) we just get a internal server error.

Anyone else got this behavior as well?

**Comment by nmaludy** [comment]
@ZeroPointEnergy i just tested on the master branch and do not have this issue. Can you look in `/var/log/http/puppet.dev.encore.tech_error_ssl.log` for any stack traces?

**Comment by ZeroPointEnergy** [comment]
Yes, this issue still persists for us with version 2.1.1. Reverting to 1.0.0 fixes the issue.

I'm unable to get the application to log any more than just that it is an internal server error. We use passenger and I configured logging the way it is documented in the README, but nothing ever gets written to it. The only output I ever see is from apache/passenger.

**Comment by ZeroPointEnergy** [comment]
We finally figured this out. It was an error on our end, where our deployment had some issues and the virtualenv did not get updated with the correct dependencies. I'm closing this. Sorry for the inconvenience.
