### ISSUE TITLE
Reinstating python 3.5 support in the next version would be nice.

### ISSUE THREAD

**Issue by kevgreen-ebay-com** [voxpupuli/puppetboard#551]
As mentioned in https://github.com/voxpupuli/puppetboard/issues/529 it would be great if you could reinstate python 3.5 support if it's not too much trouble.

It looks like support was removed with only two simple commits, and those commits didn't actually make a *functional* change. In fact, it just looks like housekeeping done alongside deprecating python 2.x, so I'm guessing it was only notional or metadata anyway and not too difficult to reverse?

https://github.com/voxpupuli/puppetboard/commit/77949e9d5bb049b354c34475e15287a9eac982ea
https://github.com/voxpupuli/puppetboard/commit/34ec9daf1bb2aaa960d058988630c420c61e3097

I'm afraid I don't really know enough python to provide a PR that I'm confident will work, sadly.

**Comment by bastelfreak** [comment]
Hi,
my initial impression was that 3.5 is EOL already, but that does not seem to be the case? https://devguide.python.org/devcycle/#end-of-life-branches

If you're able to provide a PR that adds it back to the CI matrix we can merge it.

**Comment by kevgreen-ebay-com** [comment]
Thanks b4ldr!

Apropos, I looked at the link about EOL branches above, and it appears a general rule of python releases lasting 5 years from release to EOL has emerged, and given 3.5 was released September 13, 2015, I suspect we'll see it go EOL on September 13th. That has interesting implications for Debian users on anything less than Debian 10 as well.

**Comment by nmaludy** [comment]
Release `2.1.1` was just created with this fix included.
