### ISSUE TITLE
Create a docker image on docker hub

### ISSUE THREAD

**Issue by fe80** [voxpupuli/puppetboard#554]
HI,

It's possible to add a docker image on docker hub with voxpupuli account ?

The older images was puppetlabs (an archived project https://github.com/puppetlabs/puppet-in-docker)

Regards,

**Comment by bastelfreak** [comment]
hi, thanks for the request. We already have a dockerfile here, so this shouldn't be too hard. However we first need to fix https://github.com/voxpupuli/puppetboard/issues/553 . If you like you can have a look at our dockerfile and provide feedback / patches to that.

**Comment by larsnaesbye** [comment]
@bastelfreak #553 is closed, so is anything else holding it up?

**Comment by raphink** [comment]
Feel free to use ours https://hub.docker.com/r/camptocamp/puppetboard

**Comment by gdubicki** [comment]
Thanks @raphink ! I have proposed to provide a link to your image in https://github.com/voxpupuli/puppetboard/pull/601 .

PS There is no code for image with app v2.2.0 in the [camptocamp/docker-puppetboard](https://github.com/camptocamp/docker-puppetboard) repo, I suppose that you forgot to push it. :)

**Comment by raphink** [comment]
No. iirc, I used the `Dockerfile` from the `puppetboard` repository for the latest image.
