### ISSUE TITLE
Missing trailing 'u' character in facts with hashes

### ISSUE THREAD

**Issue by yakatz** [voxpupuli/puppetboard#567]
In an educational institution, we have a very large number of facts that end with `.edu`, but in puppetboard, all of them inside hashes show up as `.ed `. Running `puppet facts` on the systems show the correct value.

For example, `fqdn` is correct, but `trusted['certname']` is missing the trailing `u`.

Puppetboard:
![image](https://user-images.githubusercontent.com/93333/79252763-1dc2a380-7e50-11ea-87b2-0c22c126fe02.png)

And in Chrome inspector:
![image](https://user-images.githubusercontent.com/93333/79253050-97f32800-7e50-11ea-9557-bd5f4b4fd360.png)

**Comment by epackorigan** [comment]
I see the same where `os::name` shows `Ubunt` for a lot of my machines. Same for `os::id`. `operatingsystem` is showing the correct value.

**Comment by epackorigan** [comment]
It appears that there is code removing the u at the end of values [here](https://github.com/voxpupuli/puppetboard/blob/c72d3e88639a5c62c9a3577c5efcc9c464552fbf/puppetboard/templates/_macros.html#L65)
I don't have enough context to understand why that code is doing this there.

**Comment by yakatz** [comment]
Starting a string with `u'` in python means it is Unicode-encoded. I am not sure how I missed this in my searching. I will see if I can work up a patch.

**Comment by gdubicki** [comment]
Fixed in v3.3.0 released today. Please check it out @yakatz . :)

**Comment by yakatz** [comment]
Thanks. Resolves the issue.
