### ISSUE TITLE
sles 12.3 issues including Flask >=1.1.1 should be Flask ==1.1.1 and modified puppetdb python modules for python 2.7.13

### ISSUE THREAD

**Issue by felipezbofh** [voxpupuli/puppetboard#568]
use your puppet module to install puppetboard on sles 12.3 with system python.

Steps required to make it work.

Flask 1.1.2 threw errors  downgrade to Flask 1.1.1 solved this.  (updated requirements.txt)

ERROR:puppetboard.core:Exception on /daily_reports_chart.json [GET]
 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 1169, in daily_reports_chart return jsonify(result=result)
  File "/usr/lib/python2.7/site-packages/flask/json/__init__.py", line 371, in jsonify KeyError: 'JSONIFY_MIMETYPE'

also to make this work on sles 12.3 I 

pip install six 

then modified

lib/python2.7/site-packages/pypuppetdb/api.py
line 8
from
from urllib.parse import quote
to
from six.moves.urllib.parse import quote

Python 2.7 Sles 12.3
pip list installed

Package             Version
------------------- -----------
appdirs             1.4.3
certifi             2020.4.5.1
cffi                1.5.2
chardet             3.0.4
click               7.1.1
commonmark          0.9.1
configparser        4.0.2
contextlib2         0.6.0.post1
cpuset              1.5.6
cryptography        1.3.1
distlib             0.3.0
enum34              1.1.3
filelock            3.0.12
Flask               1.1.1
Flask-WTF           0.14.3
future              0.18.2
httpretty           0.9.6
idna                2.8
importlib-metadata  1.6.0
importlib-resources 1.4.0
ipaddress           1.0.14
itsdangerous        1.1.0
Jinja2              2.11.1
MarkupSafe          1.1.1
pathlib2            2.3.5
pip                 20.0.2
pyasn1              0.1.9
pycparser           2.10
pygobject           3.20.1
pyOpenSSL           16.0.0
pypuppetdb          2.1.0
requests            2.22.0
scandir             1.10.0
setuptools          44.1.0
singledispatch      3.4.0.3
six                 1.13.0
SSSDConfig          1.13.4
typing              3.7.4.1
urllib3             1.25.8
virtualenv          20.0.17
Werkzeug            1.0.1
wheel               0.34.2
WTForms             2.2.1
zipp                1.2.0

**Comment by gdubicki** [comment]
Hey @felipezbofh !

This issue seems to be Python 2-specific and we don't support Python 2 since v2.0.0 released on Jan 13, 2020...

I am closing this issue then.
