### ISSUE TITLE
Backport metrics v2 support to v1 (Python 2)?

### ISSUE THREAD

**Issue by Bouke** [voxpupuli/puppetboard#569]
We're currently on CentOS 7, which unfortunately doesn't provide Python 3 WSGI. While we are planning upgrading to CentOS 8 at some point, we don't have an immediate plans. So we're looking at running puppetboard v1 with Python 2 support for some time. This currently means that the metrics v1 is the only version that the package supports. However with PuppetDB 5.2.13 disabling that endpoint, puppetboard is now broken for us. See also #560.

We previously "solved" this by downgrading to 5.2.12, however this prevents us from keeping our packages updated. To make matters worse, auto-update rolled out 5.2.14 and downgrading to 5.2.12 is no longer possible (assertion failure somewhere in PuppetDB).

Would there be interest in shipping an update to v1 to support (backport) the metrics v2 endpoint?

**Comment by gdubicki** [comment]
Hi @Bouke ! Are you still having this issue?

**Comment by moonbaseDelta** [comment]
Hello, I use python3 and puppetboard/gunicorn3 on CentOS7 on regular basis. 

There's no problem for python3, but newer versions usually not on default repositories so you need to follow instructions like that one: https://www.liquidweb.com/kb/how-to-install-python-3-on-centos-7/

**Comment by gdubicki** [comment]
As of now we are also using Puppetboard with Centos 7, Python 3.6 and PuppetDB 5.2.19 without issues in one of our envs.

Closing then, please reopen if needed, @Bouke.
