### ISSUE TITLE
Internal Server Error on overview page

### ISSUE THREAD

**Issue by blackknight36** [voxpupuli/puppetboard#570]
puppetboard is returning a 500 error when attempting to access the overview page for all environments.  For example, the following URL results in an error.

https://puppetboard.example.com/%2A/

Accessing the same page for a specific environment works without any errors.

The logs show what appears to be a puppetdb error however there have been no changes made to the puppetdb configuration.

```uwsgi[2097]: DoesNotComputeError: java.lang.Exception : No access from client 192.168.0.5 allowed```

**Comment by bgibson710** [comment]
See issue 566 for a probable solution to this issue.  I have a feeling the config file changes will fix the access issue.

**Comment by blackknight36** [comment]
> See issue 566 for a probable solution to this issue. I have a feeling the config file changes will fix the access issue.

Looks like the solution posted in #566 does stop the errors.  Thanks for the help.
