### ISSUE TITLE
on the node detail page, facts are ordered in reverse alphabetical order

### ISSUE THREAD

**Issue by epackorigan** [voxpupuli/puppetboard#572]
When looking at the details of a report for a given node, the facts on the right side are ordered in reverse alphabetical order. Would it be possible to get the order in ascending order for that table?

**Comment by gdubicki** [comment]
Hi @epackorigan !

Thanks to @jokreliable 's contribution this will be fixed in the next puppetboard release.

**Comment by gdubicki** [comment]
Fixed in v3.0.0.
