### ISSUE TITLE
Official Docker Image for Puppetboard

### ISSUE THREAD

**Issue by Xtigyro** [voxpupuli/puppetboard#574]
Hi Voxpupuli Team - firstly, thank you very much for your hard work on Puppetboard!

It appears there hasn't been released an official Docker image yet. Is that really the case?

CC: @underscorgan

**Comment by larsnaesbye** [comment]
A combined Puppet and Puppetboard Docker image would be awesome.

**Comment by gdubicki** [comment]
Let's close this issue in favor of #554 which is about the same thing but has more attention.

**Comment by gdubicki** [comment]
As documented in https://github.com/voxpupuli/puppetboard#using-docker , the camptocamp/puppetboard is the "official" image now.
