### ISSUE TITLE
Facts are not displayed in puppetboard

### ISSUE THREAD

**Issue by naby625** [voxpupuli/puppetboard#578]
Hi everyone,
I install latest version of puppetboard in RHEL 7 (I needed to compile mod_wsgi with python 3).
I access to the board but the facts are not displayed. Nevertheless when I query the puppetDB directly I got them. Below I snapshot of what I get. Anyone faced thius issue ?
![PrtScr capture_4](https://user-images.githubusercontent.com/2511061/86362117-181d7280-bc75-11ea-8165-4975bb112097.jpg)

**Comment by naby625** [comment]
here is my puppetboard configuration  : 
`node 'node1' {
$mod_wsgi_package_name = 'mod_wsgi'


class { 'puppetboard::apache::vhost':
  vhost_name => 'puppetboard.example.com',
  port => 8080,
}
# configure mod_wsgi for python3
class { 'apache::mod::wsgi':
  mod_path           => 'modules/mod_wsgi.so',
  package_name       => $mod_wsgi_package_name,
  wsgi_socket_prefix => '/var/run/wsgi',
}

class { 'puppetboard':
  # use python3 when setting up the virtualenv for puppetboard
  virtualenv_version => '3',
  reports_count       => 30,
  default_environment => 'production',
  puppetdb_host         => 'my_puppetdbserver',
  puppetdb_port         => 9090,
  revision            => 'v1.0.0',
}
`

**Comment by naby625** [comment]
Finally I fix this by replacing 'unicode' by 'bytes' on 

File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 724, in fact_ajax
[Thu Jul 02 21:41:58.275525 2020] [wsgi:error] [pid 26723] [remote 172.18.2.4:44690]     if isinstance(fact_value, unicode) or isinstance(fact_value, str):
[Thu Jul 02 21:41:58.275530 2020] [wsgi:error] [pid 26723] [remote 172.18.2.4:44690] NameError: name 'unicode' is not defined
change at this lines unicode by bytes

**Comment by gdubicki** [comment]
Hey @naby625 , sorry that you had to wait so long for a reply!

This issue has been fixed by @dom-nie in https://github.com/voxpupuli/puppetboard/commit/70c1455a133c4656376200a6802e720f9d1f3c1f , released in v2.0.0.
