### ISSUE TITLE
Link in Readme to Docker package is bad

### ISSUE THREAD

**Issue by nacengineer** [voxpupuli/puppetboard#579]
This link to maintained docker image 

https://github.com/voxpupuli/puppetboard#packages-1

Just goes to a locked down docker hub account. I'm guessing that dude has punted on maintaining it.

**Comment by larsnaesbye** [comment]
Yup. There's no voxpupuli/puppetboard official Docker Hub image. #554 and #574 address the same problem, basically.

**Comment by gdubicki** [comment]
This is fixed with #601.
