### ISSUE TITLE
Request - Improvements to pagination speed

### ISSUE THREAD

**Issue by mike406** [voxpupuli/puppetboard#599]
Hello, I am putting in a request for performance improvements on the pagination logic. It's currently nearly impossible for me to navigate past page 5 on any sort of results list, mainly reports. What I notice is that the time it takes for the next page to load is longer the higher up the pagination you go. Meaning, page 3 takes longer to load than 2, 4 takes longer to load than 3 and so on. It gets to a point where it takes minutes for the next page in the table to load and usually the server times out by then. Using a late row lookup pattern might be able to help with this.

Edit, I notice the code uses your pypuppetdb reports() function for generating the reports table. The way the limits and offsets are implemented in the PuppetDB API is probably where the loss of performance is coming from. The only way I see around this is by issuing raw SQL commands using late row lookup patterns. 

If someone can do testing on their instance of Puppetboard/PuppetDB it would be interesting to see results for comparison. I have roughly 1200 nodes in my environment.

**Comment by bastelfreak** [comment]
Hey @mike406, thanks for the feedback. Is there a chance you can provide a PR for this feature? I'm happy to review this, but I currently don't have the time to implement this myself.

**Comment by mike406** [comment]
Understood. If I find the time I don't mind taking a crack at it.

**Comment by mike406** [comment]
So, all of a sudden the pagination issue completely went away on its own. I can get to page 1000 in my reports in around ~20-30 seconds of query time which is not bad at all. I am really not sure what changed to fix the performance issue. The only thing that comes to mind is on my Puppet Server I turned off storing reports in the cache and only send them to PuppetDB (Using `reports = puppetdb` rather than `reports = store,puppetdb` in puppet.conf). However I'm not sure why that would matter because I have PuppetDB and Puppet Server on two separate machines...so maybe something else fixed it.
