### ISSUE TITLE
[Question] SSL Certificate verify failed for puppetboard

### ISSUE THREAD

**Issue by sai-ns** [voxpupuli/puppetboard#600]
Hi, I have followed the instructions and was able to setup Flask for puppetboard but ran into an issue accessing flask directly or even from apache with an SSL CERTIFICATE_VERIFY_FAILED error communicating with puppetDB.

ERROR:pypuppetdb.api:Could not reach PuppetDB on 127.0.0.1:8081 over HTTPS.
ERROR:puppetboard.utils:HTTPSConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /pdb/query/v4/environments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
INFO:werkzeug:10.250.36.200 - - [13/Nov/2020 16:47:59] "GET / HTTP/1.1" 500 -

I have puppetDB running on the same machine and certs are placed at a location which are put in settings.py file.

Direct call using curl with passing certs as options works just fine. As of now, my only guess is that the python program is trying to communicate with an https endpoint and is failing to find certs that are required for an SSL handshake.

Just wanted to check if there is anything else I am missing as part of the setup or need additional steps outside of puppetboard setup to make it work. 

Have anyone faced this issue before or have any thoughts on how to fix this?

**Comment by gdubicki** [comment]
Hey @sai-ns , so you still have this issue?

If yes the please share your config, especially/at least the env variables starting with `PUPPETDB` and your Puppetboard version.

**Comment by sai-ns** [comment]
@gdubicki after further troubleshooting it was identified that puppet dashboard application was not picking up puppet environment. After running puppet agent on the VM, proper env was loaded and dashboard was able to access the Puppet DB. 
Should've updated here but anyways its resolved and am closing this issue/question.
