### ISSUE TITLE
Numerical facts don't get filtered properly

### ISSUE THREAD

**Issue by mike406** [voxpupuli/puppetboard#612]
I noticed an issue with trying to filter numeric facts. For example I need to track version upgrades for our 600 Windows 10 PCs so I use the /fact/windows_release_id fact. If I want to view version 1909 for example, I would put /fact/windows_release_id/1909. However when I do this, it shows me all Windows 10's regardless of version number. I instead have to use the search box and type in "1909" to get the filter I need.

**Comment by gdubicki** [comment]
Fixed in v3.3.0 released today. Please check it out @mike406 . :)
