### ISSUE TITLE
3.1.0 tag not pushed to ghcr.io/voxpupuli/puppetboard

### ISSUE THREAD

**Issue by vainkop** [voxpupuli/puppetboard#623]
I don't see tag 3.1.0 for current latest release pushed to
```ghcr.io/voxpupuli/puppetboard:3.1.0```

Any plans to do that?

3.0.0 works ok:
```ghcr.io/voxpupuli/puppetboard:3.0.0```

https://github.com/orgs/voxpupuli/packages/container/package/puppetboard
![image](https://user-images.githubusercontent.com/28118190/120192081-69d2d200-c223-11eb-8854-0416e03d82ef.png)

![image](https://user-images.githubusercontent.com/28118190/120192209-8f5fdb80-c223-11eb-96d0-a8d9549e762e.png)

**Comment by gdubicki** [comment]
See explanation in #624 .
