### ISSUE TITLE
3.0.0 to 3.1.0 upgrade?

### ISSUE THREAD

**Issue by vainkop** [voxpupuli/puppetboard#624]
Currently using 3.0.0 in docker from ghcr.io/voxpupuli/puppetboard:3.0.0

Please provide the best way / known caveats to upgrade 3.0.0 to 3.1.0 

Aside from tag 3.1.0 not pushed yet https://github.com/voxpupuli/puppetboard/issues/623

Specifically interested if an update of docker tag from 3.0.0 to 3.1.0 breaks anything in existing postgresql schema or a migration is supposed to happen or maybe nothing changed & it's considered safe?

**Comment by gdubicki** [comment]
Hi @vainkop !

There is „3.1.0post2” tag as we had to retry build of 3.1.0 three times until we managed to build the Docker image with right tags.

I suggest using more generic tag „3.1” though to get patches automatically or if you trust us a bit more even tag „3”. As we try to follow semver nothing should break.

**Comment by vainkop** [comment]
@gdubicki Thanks!
