### ISSUE TITLE
Feature Request - Add datetime filter to Reports

### ISSUE THREAD

**Issue by mike406** [voxpupuli/puppetboard#625]
It would be very useful to be able to filter the Reports history by a date and time. It's not very practical to have to click through the pagination to get to a certain time in the past, and in some cases is impossible depending how far back into the history you want to go.

**Comment by sebastianrakel** [comment]
@mike406 i provided a PR with a screenshot in it, this should fix your issue

**Comment by gdubicki** [comment]
Released in v3.2.0. :)
