### ISSUE TITLE
How to access the puppetboard UI

### ISSUE THREAD

**Issue by liquidoshin** [voxpupuli/puppetboard#626]
This is a super basic question but I can't seem to find out how to actually pull up the puppetboard UI. There's nothing in the readme about it. If this is a duplicate issue I apologize and please point me to the original post.

**Comment by ghoneycutt** [comment]
try http://$PUPPETDB_HOST/ if you specified a different port, add that to your URL.

**Comment by gdubicki** [comment]
Please reopen if this does not answer your question, @liquidoshin . :)

**Comment by liquidoshin** [comment]
documentation says the default port is 8081 and I have that port specified in my default_settings.py file. When I add that port to the url the page fails to load. I understand this could be many things causing this issue. Is there a log file I can look at?

**Comment by liquidoshin** [comment]
Hi. So regarding the issue I opened, I saw another user state that if this doesn't resolve my issue, to reopen the case but I don't think I have those privileges. I did respond yesterday but due to it being closed you may have not been informed about it. Could you reopen this issue and continue to assist?

Thanks.

[signature_61897647]

Derek T Walker
Software Develop
NIE-CDS

Office: 505 667 8291
Mobile: 505 551 4256

Los Alamos National Laboratory
lanl.gov

[https://mymail.lanl.gov/owa/?bO=1]<https://www.instagram.com/losalamosnatlab/>[https://mymail.lanl.gov/owa/?bO=1]<https://twitter.com/LosAlamosNatLab>[https://mymail.lanl.gov/owa/?bO=1]<https://www.linkedin.com/company/los-alamos-national-laboratory/>[https://mymail.lanl.gov/owa/?bO=1]<https://www.facebook.com/LosAlamosNationalLab/>




________________________________
From: Garrett Honeycutt ***@***.***>
Sent: Wednesday, June 23, 2021 4:51:55 PM
To: voxpupuli/puppetboard
Cc: Walker, Derek Trent; Author
Subject: [EXTERNAL] Re: [voxpupuli/puppetboard] How to access the puppetboard UI (#626)


try http://$PUPPETDB_HOST/ if you specified a different port, add that to your URL.

**Comment by gdubicki** [comment]
8081 is the default port for PuppetDB as a backend for Puppetboard. The default listening port for the app run in a dev mode is 5000.

The production setup however should utilise WSGI server, like Apache HTTPD with mod_wsgi. Please see https://github.com/voxpupuli/puppetboard/tree/master/docs for more info about it.

**Comment by liquidoshin** [comment]
I'm looking into the documentation from the link you posted. It gives instructions on how to setup this up for EL7. Is this only compatible on EL7? Our server that I'm trying to get this to work on is RHEL 8

**Comment by gdubicki** [comment]
I can’t find explicit info about this but https://forge.puppet.com/modules/puppet/puppetboard should be compatible with RHEL 8.

**Comment by liquidoshin** [comment]
I finally got it working. It was due to some internal system settings we needed to remedy. Thank you for all your time.
