### ISSUE TITLE
Remove tabs for disabled features

### ISSUE THREAD

**Issue by nick-markowski** [voxpupuli/puppetboard#627]
Setting ENABLE_QUERY, ENABLE_CATALOG to False should remove the Query and Catalogs tabs, respectively.

Presently, the Query and Catalogs tabs persist when their respective features are disabled, and accessing the tab results in a 'Forbidden' page. Experienced on Puppetboard v3.1.0

**Comment by sebastianrakel** [comment]
Hey, i provided a PR with changes that should fix it

**Comment by nick-markowski** [comment]
@sebastianrakel @gdubicki thank you!
