### ISSUE TITLE
allow app prefix setting in Docker image

### ISSUE THREAD

**Issue by lesinigo** [voxpupuli/puppetboard#633]
As far as I can tell the currently published Docker image (tag `3.1.0.post4` as of this writing) does not have any way to pass the `prefix` setting to Flask app constructor and there is no way to specify a prefix later, this makes it impossible to access Puppetboard under a sub-uri like `https://my_revproxy/puppetboard`.

References for this information can be found in issue #225 and are well summarized by @BcTpe4HbIu in https://github.com/voxpupuli/puppetboard/issues/225#issuecomment-203164874 .

@m4ce solved this with its own image in https://github.com/m4ce/docker-puppetboard

It would be cool if the same solution could be ported inside the "official" docker image and exposed in any way to let people enable / disable / customize it.

**Comment by gdubicki** [comment]
Hi @lesinigo ! Sounds like a good idea. Perhaps you could provide a Pull Request for it?

**Comment by gdubicki** [comment]
Ops, sorry @lesinigo, it looks like it was already possible and just the docs about it have been lost. Restored in the commit above.
