### ISSUE TITLE
Improve formatting of the Logs in the Report view

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/puppetboard#641]
It would be nice when looking throught the logs, that the columns were not even sizes and instead try to remove excess whitespace.  TimeStamp,Source,Tags, should be much narrower I think than message.  Message is typically where troubleshooting details reside.  Ideally it would be nice to exclude a column like tags, if it isn't relevant.

**Comment by gdubicki** [comment]
That's a very reasonable proposal, @rismoney ! As always, we are open to PRs. But perhaps after some work with Datatables that I did for facts in #644, I may try to improve logs view too. :)

**Comment by gdubicki** [comment]
Please check out [v3.5.0rc1](https://github.com/voxpupuli/puppetboard/releases/tag/v3.5.0rc1) with this feature, @rismoney. A final release will be done within a few days.

**Comment by gdubicki** [comment]
Final [v3.5.0](https://github.com/voxpupuli/puppetboard/releases/tag/v3.5.0) released.

**Comment by rismoney** [comment]
Big improvement!  This looks way better.  TYVM!
