### ISSUE TITLE
Feature: Accept certificate and key as strings

### ISSUE THREAD

**Issue by SeanHood** [voxpupuli/puppetboard#669]
Hey folks, I'm setting up Puppetboard in AWS Fargate. I am running into a well known problem that in AWS Fargate you can't mount files to tasks (https://github.com/aws/containers-roadmap/issues/56).

So the feature I'm proposing is for the Puppetboard docker image to accept the certificate/key/ssl_verify files as strings via environment variables. Then taking those strings and writing them out to files.

Perhaps something like:
```
PUPPETDB_SSL_VERIFY_STRING
PUPPETDB_KEY_STRING
PUPPETDB_KEY_STRING
```

Or perhaps a variable to flag if they're strings or files.

Would there be interest in such a feature? I'm happy to attempt a PR if so.

**Comment by gdubicki** [comment]
Hi @SeanHood!

Sure, we are open to PRs with such feature. Perhaps you could implement autodetection if the passed values are strings with certs or paths to such certs so we won’t have to introduce new env variables? I feel that we have too many already. 😅
