### ISSUE TITLE
PyPi package for 3.4.0 is broken

### ISSUE THREAD

**Issue by Rewerson** [voxpupuli/puppetboard#677]
After upgrading puppetboard package with pip, there is an error on app start, like:
```
File "/usr/local/lib/python3.9/dist-packages/puppetboard/app.py", line 11, in <module>
     import puppetboard.views.catalogs  # noqa: F401
ModuleNotFoundError: No module named 'puppetboard.views'
```
Packaged module doesn't have folder `views` near the `app.py`.
Downloaded this folder from this repo, placed in `/usr/local/lib/python3.9/dist-packages/puppetboard/` and only then it works.

**Comment by gdubicki** [comment]
Sorry for that and thanks for reporting, @Rewerson! Please check out v3.4.0.post1 and reopen the issue if this doesn't help.
