### ISSUE TITLE
git tags and releases criteria.

### ISSUE THREAD

**Issue by GermanG** [voxpupuli/puppetboard#678]
Trying to package this in our internal repositories, I've found a couple of issues that I'd like to share here.
First the tagging cannot be ascii sorted
```
$ git tag -l --sort=v:refname | tail
v3.3.0rc1
v3.4.0
v3.4.0.post1
v3.4.0.post2
v3.4.0rc1
v3.4.0rc2
v3.4.0rc3
v3.4.0rc4
v3.4.0rc5
v3.4.0rc6
```
this was easily solved with 
```
$ git tag --sort=creatordate  | tail
v3.3.0
v3.4.0rc1
v3.4.0rc2
v3.4.0rc3
v3.4.0rc4
v3.4.0rc5
v3.4.0rc6
v3.4.0
v3.4.0.post1
v3.4.0.post2
```
This will be valid as long as you don't tag back some code.

The second thing is the package manager and the way it compares versions, that cannot be solved so easily.
```
	package puppetboard-3.4.0rc1-1.ad8.x86_64 (which is newer than puppetboard-3.4.0.post2-1.ad8.x86_64) is already installed
```
Our automation takes the tag and uses it as a version, I wonder if you also face this challenge and if it's something that can be considered to improve.

Regarding this, I plan to use my own tagging so the new version won't be considered a downgrade.

I don't think this is an issue per se, but it'll be nice to talk about this, that's why I'm using this channel.

Regards.

**Comment by gdubicki** [comment]
Hi @GermanG!

> First the tagging cannot be ascii sorted (...)

I think that sorting tags alphanumerically and expecting the result to be correct order according to some versioning scheme is _very optimistic_, to put it mildly.

Even clean [semver](https://semver.org) versions are not sortable this way. Take for example these versions: `1.0.0`, `2.0.0`, `10.0.0`. If you sort them alphanumerically you will get:
```
1.0.0
10.0.0
2.0.0
```

> The second thing is the package manager and the way it compares versions, that cannot be solved so easily.

This project uses a standard Pythonic versioning according to [PEP440](https://peps.python.org/pep-0440/) and within the the X.Y.Z part of the version we strive to follow semver.

If I am getting it right that you are repackaging these into some Linux distro native packages, like RPM, then you should modify the versions somehow to make them compliant with the target versioning scheme.

Note that if you want me (or someone else here) to help you more then you should share what is your target packaging.

**Comment by gdubicki** [comment]
The natural way to get the latest release according to the Python versioning scheme is to use some Python lib that handles it. I have used [luddite](https://pypi.org/project/luddite/) for this purpose in another project, gitlabform. You can check out the code [here](https://github.com/gdubicki/gitlabform/blob/e619fc5139da1d4da36df859dba94bea481d1f13/gitlabform/ui.py#L49-L49).

**Comment by gdubicki** [comment]
I’ll close this issue as I assume that you got what you need, @GermanG. Please reopen if needed.
