### ISSUE TITLE
Add option to show friendly error messages when in report view on a specific node

### ISSUE THREAD

**Issue by mike406** [voxpupuli/puppetboard#685]
Error messages are cut off when viewing a specific node's report due to error being wrapped in `<pre>` tags. Can the friendly error messages feature be implemented on this screen as well so that the errors will wrap on the page? I'm on the latest version 3.4.2.

Edit: Only happens on certain error messages, not sure why that is though.

![image](https://user-images.githubusercontent.com/3455235/165366266-27789ceb-32d0-400a-bfea-f8027f947719.png)

**Comment by gdubicki** [comment]
Hi @mike406, thanks for filing the issue!

I was thinking about doing this together with #641 but I haven't found the time for that just yet... But we are open to PRs from anyone who is willing to improve this. :)

**Comment by mike406** [comment]
I went with a simpler solution. I just added this to puppetboard/static/css/puppetboard.css
``
pre {
 white-space: pre-wrap;
}
``

![image](https://user-images.githubusercontent.com/3455235/167505362-d93856af-72f0-4540-9ec5-aa88c71e8b4e.png)

**Comment by gdubicki** [comment]
Cool, can you make a PR with such change @mike406?

**Comment by gdubicki** [comment]
Please check out [v3.5.0rc1](https://github.com/voxpupuli/puppetboard/releases/tag/v3.5.0rc1) with this feature, @mike406. A final release will be done within a few days.

**Comment by gdubicki** [comment]
Final [v3.5.0](https://github.com/voxpupuli/puppetboard/releases/tag/v3.5.0) released.

**Comment by mike406** [comment]
Hi @gdubicki  sorry for the late reply, this change looks great! Thank you for implementing.
