### ISSUE TITLE
Puppetdb health check on homepage

### ISSUE THREAD

**Issue by ArthurWuTW** [voxpupuli/puppetboard#691]
I was in the situation my puppetdb was dead, and I had no any evidence on puppetboard, because I got internal server error from it.
So I was wondering to add a feature to show puppetdb connection status on puppetboard homepage.

- [ ] Able to show homepage even if puppetdb connection failed.
- [ ] Able to show homepage after puppetdb start and no agent yet.
- [ ] Add a puppetdb connection status hint on the banner.

 I've already done this feature and it looks like...

* Run puppetboard only
![image](https://user-images.githubusercontent.com/36653598/172033807-f1035ac4-e68c-48f4-8159-009b1820fed8.png)

* Run puppetboard and puppetdb, but no agent yet
![image](https://user-images.githubusercontent.com/36653598/172033809-998199e4-9a06-4073-880f-e695dc835f0a.png)

* Run puppetboard and puppetdb with agents
![image](https://user-images.githubusercontent.com/36653598/172033810-2ea6aa08-498e-411a-a35a-c28cd045f935.png)

any suggestions?

**Comment by gdubicki** [comment]
Hi @ArthurWuTW!

Thanks for reporting this and taking the time to propose specific UI changes. :) I agree that currently Puppetboard handles cases where PuppetDB is not working or when it is empty particularly badly.

However I think that on the first screenshot the content is contradicting itself - if the PuppetDB connection has failed then the Puppetboard _doesn't know_ what are the numbers of nodes in each state, so it should not show zeros. How about we show something like this in such case instead:

<img width="1280" alt="Screenshot 2022-06-06 at 08 34 03" src="https://user-images.githubusercontent.com/566632/172108158-44b12759-afaf-4627-a2ef-b1f3fd67cbb4.png">

What do you think?

Also we really should finally fix #515 and #562 by showing something helpful when the PuppetDB is empty/doesn't contain anything in a given env. This would require some investigation about how to distinguish these cases though.

**Comment by ArthurWuTW** [comment]
yeah you are right, error message is enough
I just modify the code to have error message when puppetdb connection failed.
No need to have the status light on the banner as well.
