### ISSUE TITLE
errors are showing unchanged instead of failed

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/puppetboard#698]
On the nodes tab, if I pick out a machine that I know had a failure, is showing "green unchanged" but if I click in on it, there is an error.  I think somewhere the logic is broken, in determining this failure.

```<html>
<body>
<!--StartFragment-->

2:07:42 | err | Error while evaluating a Resource Statement:Duplicate declaration: Package[textpad] is already declared at (file: …/master/modules/workstation/manifests/windows.pp, line: 4); cannot redeclare (file: …/master/modules/editor/manifests/textpad.pp, line: 3)…in …/master/modules/editor/manifests/textpad.pp, line: 3, column: 3. |  
-- | -- | -- | --
12:07:53 | notice | Applied catalog in 10.69 seconds

<!--EndFragment-->
</body>
</html>
```

**Comment by rismoney** [comment]
To add more info I am running on the following containers:

 puppet/puppetdb:7.8.0 
 ghcr.io/voxpupuli/puppetboard:3.6.1 
 puppet/puppetserver:7.8.0

**Comment by rismoney** [comment]
![pboard1](https://user-images.githubusercontent.com/1273576/176476377-32f9132c-e40c-4371-9907-dbd7fa52addb.png)
![pboard2](https://user-images.githubusercontent.com/1273576/176476387-fa974ffd-0512-4b89-8214-196ec7e5ae07.png)

**Comment by gdubicki** [comment]
Thanks @rismoney.

It looks like the same case as discussed in #449, please check it out.

**Comment by rismoney** [comment]
I haven't seen this, and will reopen if I see a scenario where a resource was unchanged but things changed within.
