### ISSUE TITLE
Auto Refresh/Radiator

### ISSUE THREAD

**Issue by sirloper** [voxpupuli/puppetboard#70]
Enhancement Request:  Auto Refresh setting and/or Radiator style view

**Comment by Breeze773** [comment]
Is there any progress on this feature?  I agree it's a good idea to have the option to disable it, but a radiator with static information is as helpful as staring at a wall.

**Comment by fgimian** [comment]
A pull request has been provided which uses the meta tag here https://github.com/puppet-community/puppetboard/pull/99 although I personally am more keen on an AJAX-based solution.

Thoughts? :smile: 
Fotis

**Comment by nibalizer** [comment]
I would like to see an AJAX solution. Really I'd like to see puppetboard also provide json versions of all the views. I've personally seen people write scripts that parse the html tables of puppetboard.

**Comment by corey-hammerton** [comment]
Auto fresh implemented in 177f6c234a975afc80938385ee17448de89ad33b

A radiator view is still planned.

**Comment by corey-hammerton** [comment]
Refresh and Radiator view has been added.
