### ISSUE TITLE
Failed deployments go to "unchanged" on next run and are lost ?

### ISSUE THREAD

**Issue by JLoCascio** [voxpupuli/puppetboard#709]
Had an issue where a deploy to a node failed. This showed as red on the puppetboard.

However when the next deployment run happened,, because the deployment was still in error, the node then showed as "unchanged" and continued to do so for a month.

Am I misunderstanding the behaviour of puppetboard here ? It seems a strange behaviour if by design. Or is there a config somewhere ?

**Comment by gdubicki** [comment]
Hi @JLoCascio! Thanks for reporting. Can you share a screenshot for a better understanding of your issue?

**Comment by JLoCascio** [comment]
Certainly.

Here is what I am seeing in puppetboard 
![image](https://user-images.githubusercontent.com/100676700/183077686-2a879196-dfb1-4654-96c1-b031630597fd.png)

So it *looks* "unchanged.

However, drill into it and you see that actually, the node is sitting in error (and had been for a month)

![image](https://user-images.githubusercontent.com/100676700/183078017-87518d7a-824a-4c90-89fd-5c55ac77487d.png)

There is a sort of logic to this as it is true to say that the last puppet run left the node "unchanged". However that isn't quite what I need to know.

If I have misunderstood, and there is a deep config setting to show a node which hasn't had a successful deploy in time period <x> then could someone explain how I enable it.

**Comment by gdubicki** [comment]
Are you using this setting https://github.com/voxpupuli/puppetboard/issues/449#issuecomment-824900379 ?

**Comment by JLoCascio** [comment]
Wow - a lot to read ! If you don't hear from me again that was the issue and I found a fix !

**Comment by gdubicki** [comment]
😅 You only need to check if setting `usecacheonfailure` to `false` helps.

**Comment by JLoCascio** [comment]
I've checked the puppet.conf for the node in question and that value was not set. So the default behaviour was to revert to the last known good config which (now I realise it) may not have been a bad thing.

Certainly I'm not going to make a mass change yet :)

Many thanks for such a quick reply and solution. Have a great weekend.

**Comment by gdubicki** [comment]
You are welcome. 😊 Have a good one too!
