### ISSUE TITLE
Level-err does not shown as Failure in Puppetboard

### ISSUE THREAD

**Issue by erdoking** [voxpupuli/puppetboard#713]
**Describe the bug**

I got the message "Syntax error at end of input .." with Error-Level because of missing bracket at the end of the class.
But Puppetboard doesn't notice it. The node is marked as unchanged.

**Puppetboard version**

F.e. 4.0.3

**Environment and installation method**

F.e.:
* Debian 11 on LXC-Container
* installed with the Forge module v9.0.0 and using the PyPI package (default).

**Comment by erdoking** [comment]
I checked all of my 47 nodes manually and found 2 more server with errors that not shown on the board.
Puppetboard was one of this two ;)

```
Error while evaluating a Function Call:  
'pip' installation method uses $version parameter to specify version, not $revision.

…in /etc/puppetlabs/code/nodes/erdo.dmz/puppetboard/modules/puppetboard/manifests/init.pp, line: 145, column: 9.
```

this because of https://github.com/voxpupuli/puppet-puppetboard/commit/2d3e85027d18d9b8846405a4a6e79684afd9bd2e where they changed the default install method from vcsrepo tot pip.

You can test it when you change      

```
  class { 'puppetboard':
    install_from        => 'vcsrepo',
    install_from        => 'vcsrepo',
  }
```

**Comment by gdubicki** [comment]
Hi @erdoking! Thanks for reporting this.

I am guessing that you are using the default `usecacheonfailure = true` in your puppet.conf which causes the puppet runs to not really fail if there is a compilation issue as the cached catalog is used then.

See https://github.com/voxpupuli/puppetboard/issues/449#issuecomment-829132117 and other messages in that issue for more info.

Is that your case?

If so, then we should probably add this info to the docs as you are not the first person that stumbles upon it...

**Comment by erdoking** [comment]
Hi @gdubicki 

this works for me! fantastic thank you. 
Documentation sounds fantastic ;)
