### ISSUE TITLE
Please Fix auto-resize in radiator view

### ISSUE THREAD

**Issue by REHICode** [voxpupuli/puppetboard#718]
**Describe the bug**

Hi, I think the auto-resize in radiator view is broken.
It already got fixed in 3.5, maybe the code was changed again?

**Puppetboard version**
4.1

**Environment and installation method**
Tested on Ubuntu 20.04 with Firefox (latest) and Chromium (latest)

Thank you for your awesome work ...

Kind Regards
Rene

**Comment by gdubicki** [comment]
Hi @REHICode! Thanks for reporting and for your kind words. 😊 

I am not sure what the issue is though. The radiator looks like this on one of my instances:

<img width="1920" alt="Screenshot 2022-09-30 at 15 36 23" src="https://user-images.githubusercontent.com/566632/193294475-8d425f6e-3aaa-430a-9933-a8a0a18b89cc.png">

What are you seeing? Can you share a screenshot too please?

Of course if you know how to fix this then a PR with a fix is very welcome too. :)

**Comment by REHICode** [comment]
Hi @gdubicki , it basically looks the same.
But if you resize your browser window, the radiator view should resize as well.
That is not the case anymore ;)

**Comment by gdubicki** [comment]
Strange - it resizes for me.

Are you using the offline mode perhaps?

**Comment by REHICode** [comment]
Okay, that is really strange. If it resizes on your machine, then I'll have to test some things on my end.
I am on vacation for 2weeks now so not able to do the testing.
I will close this issue and hopefully will not have to ask you to open it again ;-)

Thank you

**Comment by REHICode** [comment]
@gdubicki, finally I had the time to investigate the issue.
Just for documentation reasons ...

Yes we are using offline mode.
In /srv/puppetboard/virtenv-puppetboard/lib64/python3.8/site-packages/puppetboard/templates/radiator.html the jquery.min.js for offline mode could not be found.

I had to replace:
`    <script src="{{ url_for('static', filename='jquery-3.6.0/jquery.min.js') }}"></script>`
with
`    <script src="{{ url_for('static', filename='libs/jquery/jquery.min.js') }}"></script>`

**Comment by gdubicki** [comment]
Nice catch! Can you make a PR to fix it, @REHICode?

**Comment by REHICode** [comment]
Thanks, sure thing - see: https://github.com/voxpupuli/puppetboard/pull/763

**Comment by gdubicki** [comment]
Thanks, merged and released in [v4.2.6](https://github.com/voxpupuli/puppetboard/releases/tag/v4.2.6) today.
