### ISSUE TITLE
Unable to setup puppetboard on ubuntu

### ISSUE THREAD

**Issue by dplandigi** [voxpupuli/puppetboard#859]
Hi Team,

I have setup Puppetagent, Puppetmaster and Puppetdb on ubuntu server and when i am trying to configure puppetboard is not working. I have tried installing it manually and using module. now i am using docker setup still getting 404 error. Can you please help me to fix this issues.

Thank you
Deepak

**Comment by gdubicki** [comment]
Hey @dplandigi, sorry, I missed this issue. Did you manage to solve your problem?
