### ISSUE TITLE
Provide an option to not display value for some events?

### ISSUE THREAD

**Issue by zoredache** [voxpupuli/puppetboard#86]
Within my puppet manifests I have code like so.  The actual password is coming from encrypted storage though.

```
user{'localadmin'
    password=>'theplaintextpassword',
    provider=>'windows_adsi';
}
```

The problem of course is that when the above is applied to a system, it gets logged into puppetdb.  Then it gets displayed for everyone with access puppetboard to see.  The json for the specific event is below.

```
{
  "containment-path" : [ "Stage[main]", "Localauth", "Localauth::User[localadmin]", "User[localadmin]" ],
  "new-value" : "theplaintextpassword",
  "containing-class" : "Localauth",
  "report-receive-time" : "2014-07-02T22:08:31.286Z",
  "report" : "1892d84ef0bbbd6d909e572782f360d21598e1eb",
  "resource-title" : "localadmin",
  "property" : "password",
  "file" : "/srv/puppet/environments/win_production/modules/localauth/manifests/user.pp",
  "old-value" : "absent",
  "run-start-time" : "2014-07-02T22:06:42.286Z",
  "line" : 22,
  "status" : "success",
  "run-end-time" : "2014-07-02T22:08:15.428Z",
  "resource-type" : "User",
  "timestamp" : "2014-07-02T22:08:02.318Z",
  "configuration-version" : "1404338814",
  "certname" : "thecomputer.example.org",
  "message" : "created password"
},
```

It sure would be nice to have some way in puppetboard to set some kind of filter on the server if an event has "resource-type" : "User", and "property" : "password", then the old and new values are hidden from the display.

I suspect this would also be useful for other types of resources where a secret would be displayed as part of the new/old value.

**Comment by Pitje06** [comment]
I apologize for my necromancy, but it appears that this will be fixed in puppet. I haven't read through all the bugs/fixes referenced, but maybe it's in a workable state already.
https://tickets.puppetlabs.com/browse/PUP-6433

**Comment by juniorsysadmin** [comment]
The Sensitive data type is in 4.6.1 , Puppetdb might be oblivious to it though:
https://www.devco.net/archives/2016/09/05/puppet-4-sensitive-data-types.php
