### ISSUE TITLE
Show catalog failures in overview node list

### ISSUE THREAD

**Issue by henderb** [voxpupuli/puppetboard#95]
I wish nodes whose catalog compilation failed would show in the node list.

**Comment by gdubicki** [comment]
Hey, I would also be happy to see compilation errors in puppetboard. And if I got https://tickets.puppetlabs.com/browse/PDB-16 right and if that info is still up to date, then information about such run actually *is* pushed to puppetdb, so it can be pulled out by puppetboard. So can we please reopen this ticket?

**Comment by bastelfreak** [comment]
@gdubicki I reopened the ticket. Are you interested in providing a patch for this?

**Comment by gdubicki** [comment]
Actually it seems that with latest puppetboard and puppetdb the former _does_ show compilation errors. Sorry for making you think otherwise, @bastelfreak . I think that this issue can be closed as "resolved".

**Comment by gdubicki** [comment]
I have put results of my verification that it does work in #449.

**Comment by gdubicki** [comment]
Resolved with https://github.com/voxpupuli/puppetboard/commit/ead45c99b4721d46799198b9ad279733a3e12ad2.
