### ISSUE TITLE
Pattern for python_version do not allow 3.11

### ISSUE THREAD

**Issue by jza34** [voxpupuli/puppetboard#969]
**Describe the bug**

The pattern regex for python_version do not allow 3.11, it only allows one digit(eg. 3.8) 

**Puppetboard version**

Current from puppet forge : 9.0.0

**Environment and installation method**

* Debian 12 and Python 3.11 from official debian repo,
* installed with the Forge module v9.0.0

**Comment by tolid** [comment]
I confirm the bug. Seems like the line 62 in init.pp
should be changed from Pattern[/^3\.\d$/] $python_version, to Pattern[/^3\.\d\d/] $python_version, or Pattern[/^3\.\d\d$/] $python_version,

**Comment by jza34** [comment]
Hi,
I should have posted this issue into the repository #puppet-puppetboard. Some repository admin may do it? Sorry.
The good news are someone fixed it lastly. The new pattern is ''Pattern[/^3\.\d+$/]'' which allow one or two digits.
Not released yet I guess. I manualy did the fix on my host.
Cheers

**Comment by kenyon** [comment]
Done in https://github.com/voxpupuli/puppet-puppetboard/pull/385.
